#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM ghcr.io/uniget-org/tools/go:latest AS go

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=go / /usr/local/
WORKDIR /go/src/github.com/google/trillian
ARG name
ARG version
COPY trillian_log_server.service.go-template /uniget_bootstrap/etc/systemd/system/
COPY trillian_log_signer.service.go-template /uniget_bootstrap/etc/systemd/system/
RUN --mount=type=cache,target=/root/go/pkg/mod <<EOF
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/google/trillian .
export CGO_ENABLED=0
go build -ldflags "-w -s" -o "${prefix}/bin/trillian_log_server" ./cmd/trillian_log_server
go build -ldflags "-w -s" -o "${prefix}/bin/trillian_log_signer" ./cmd/trillian_log_signer
go build -ldflags "-w -s" -o "${prefix}/bin/createtree" ./cmd/createtree
EOF