#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM ghcr.io/uniget-org/tools/go:latest AS go

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:b0b654de801604e256237f2c27a907a4b61b59ebd83423ad0e0e465c0a3ba9cd AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=go / /usr/local/
WORKDIR /go/src/github.com/google/trillian
ARG name
ARG version
COPY trillian_log_server.service.go-template /uniget_bootstrap/etc/systemd/system/
COPY trillian_log_signer.service.go-template /uniget_bootstrap/etc/systemd/system/
RUN --mount=type=cache,target=/root/go/pkg/mod <<EOF
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/google/trillian .
export CGO_ENABLED=0
go build -ldflags "-w -s" -o "${prefix}/bin/trillian_log_server" ./cmd/trillian_log_server
go build -ldflags "-w -s" -o "${prefix}/bin/trillian_log_signer" ./cmd/trillian_log_signer
go build -ldflags "-w -s" -o "${prefix}/bin/createtree" ./cmd/createtree
EOF