#syntax=docker/dockerfile

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/kubetail-org/kubetail/releases/download/cli/v${version}/kubetail-linux-${alt_arch}.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "kubetail-org/kubetail" "cli/v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin" --no-same-owner \
    kubetail
EOF
RUN <<EOF
"${prefix}/bin/kubetail" completion bash >"${prefix}/share/bash-completion/completions/kubetail"
"${prefix}/bin/kubetail" completion fish >"${prefix}/share/fish/vendor_completions.d/kubetail.fish"
"${prefix}/bin/kubetail" completion zsh >"${prefix}/share/zsh/vendor-completions/_kubetail"
EOF