#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:059b11407572b2fd733e7bcd1c528852394d7fe1abef7119a1a97356983cab76 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/php/frankenphp/releases/download/v${version}/frankenphp-linux-${arch}"
filename="$( basename "${url}" )"

check-github-release-asset "php/frankenphp" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/frankenphp"


"${prefix}/bin/frankenphp" completion bash >"${prefix}/share/bash-completion/completions/frankenphp"
"${prefix}/bin/frankenphp" completion fish >"${prefix}/share/fish/vendor_completions.d/frankenphp.fish"
"${prefix}/bin/frankenphp" completion zsh >"${prefix}/share/zsh/vendor-completions/_frankenphp"
EOF