#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS ubuntu2604

FROM ubuntu2604 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/containers/kubernetes-mcp-server/releases/download/v${version}/kubernetes-mcp-server-linux-${alt_arch}"
filename="$( basename "${url}" )"

check-github-release-asset "containers/kubernetes-mcp-server" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/kubernetes-mcp-server"
EOF