#syntax=docker/dockerfile

ARG version
FROM registry.gitlab.com/components/opentofu/gitlab-opentofu:${version}-alpine AS gitlab-tofu

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --from=gitlab-tofu /usr/bin/gitlab-tofu /uniget_bootstrap/bin/
COPY --from=gitlab-tofu /usr/bin/gitlab-tofu-ctl /uniget_bootstrap/bin/
