#syntax=docker/dockerfile:1.8.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:6ff62e5ed6b1c33f0ae1644692a354281534a37ec4d752cf480850e19a94d16d AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "structurizr/cli" "v${version}" "structurizr-cli-${version}.zip"
url="https://github.com/structurizr/cli/releases/download/v${version}/structurizr-cli-${version}.zip"
filename="$(basename "${url}")"
curl --silent --show-error --location --fail --remote-name "${url}"
mkdir -p "${prefix}/opt/structurizr-cli"
unzip -q -o -d "${prefix}/opt/structurizr-cli" "${filename}"
ln --symbolic --relative --force "${prefix}/opt/structurizr-cli/structurizr.sh" "${prefix}/bin/structurizr"
EOF