#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM ghcr.io/uniget-org/tools/go:latest AS go
FROM ghcr.io/uniget-org/tools/make:latest AS make

FROM registry.gitlab.com/uniget-org/images/build-essential:26.04@sha256:5ee01cd64296e795943405f10d803592dbd27cad7d35cd6ee1271bf177a71146 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=go / /usr/local/
COPY --link --from=make / /usr/local/
RUN <<EOF
apt-get update
apt-get -y install \
    binutils-gold \
    bash \
    clang \
    llvm \
    libbpf-dev \
    libcapstone-dev
EOF
WORKDIR /tmp/tracer
ARG name
ARG version
RUN <<EOF
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/kubeshark/tracer .
EOF
RUN --mount=type=cache,target=/root/go/pkg/mod <<EOF
./install-capstone.sh
make -j$(nproc) bpf
make -j$(nproc) build
cp tracer "${prefix}/bin/"
EOF