#syntax=docker/dockerfile:1.23.0@sha256:2780b5c3bab67f1f76c781860de469442999ed1a0d7992a5efdf2cffc0e3d769

FROM ghcr.io/uniget-org/tools/go:latest AS go
FROM ghcr.io/uniget-org/tools/make:latest AS make

FROM registry.gitlab.com/uniget-org/images/build-essential:26.04@sha256:3901744f09ec45ce90b9d531ccdb1ab69a8b3c8632bb6575e2c7c26f37418bb8 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=go / /usr/local/
COPY --link --from=make / /usr/local/
RUN <<EOF
apt-get update
apt-get -y install \
    binutils-gold \
    bash \
    clang \
    llvm \
    libbpf-dev \
    libcapstone-dev
EOF
WORKDIR /tmp/tracer
ARG name
ARG version
RUN <<EOF
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/kubeshark/tracer .
EOF
RUN --mount=type=cache,target=/root/go/pkg/mod <<EOF
./install-capstone.sh
make -j$(nproc) bpf
make -j$(nproc) build
cp tracer "${prefix}/bin/"
EOF