#syntax=docker/dockerfile:1.6.0

FROM ghcr.io/uniget-org/tools/go-md2man:latest AS go-md2man

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:da13a27933fac882122e16292dad3e4869a53dbbc52a73b4a5ddfbcde6902a99 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --from=go-md2man / /usr/local/
ARG name
ARG version
RUN <<EOF
check-github-release-asset "koalaman/shellcheck" "v${version}" "shellcheck-v${version}.linux.${arch}.tar.xz"
curl --silent --location --fail "https://github.com/koalaman/shellcheck/releases/download/v${version}/shellcheck-v${version}.linux.${arch}.tar.xz" \
| tar --extract --xz --directory="${prefix}/bin/" --strip-components=1 --no-same-owner \
    shellcheck-v${version}/shellcheck
curl --silent --location --fail --output "${prefix}/share/man/man1/shellcheck.1.md" \
    "https://github.com/koalaman/shellcheck/raw/v${version}/shellcheck.1.md"
go-md2man \
    -in "${prefix}/share/man/man1/shellcheck.1.md" \
    -out "${prefix}/share/man/man1/shellcheck.1"
rm "${prefix}/share/man/man1/shellcheck.1.md"
EOF