#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM ghcr.io/uniget-org/tools/make:latest AS make

FROM registry.gitlab.com/uniget-org/images/build-base:3.23@sha256:e66b0c6fe2a1aabcc6a1898fa94b2a1fa4eb3c83874b491e4b5496d1318ebcc5 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
RUN --mount=type=cache,target=/var/cache/apk <<EOF
apk update
apk add --update-cache \
    gettext \
    gettext-dev \
    gettext-static
EOF
COPY --link --from=make / /usr/local/
WORKDIR /tmp/pv
ARG name
ARG version
# Static linking causes "undefined refererence to printf
RUN <<EOF
curl --silent --show-error --location --fail "https://www.ivarch.com/programs/sources/pv-${version}.tar.gz" \
| tar --extract --gzip --strip-components=1
./configure --prefix="${prefix}"
make -j$(nproc) LDFLAGS=-static
make install
EOF