#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:rolling AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
curl --silent --show-error --location --fail --remote-name "https://dot.net/v1/dotnet-install.sh"
bash dotnet-install.sh --channel STS --version "${version}" --install-dir "${prefix}/opt/dotnet"
ln --symbolic --relative --force "${prefix}/opt/dotnet/dotnet" "${prefix}/bin/dotnet"
EOF