#syntax=docker/dockerfile:1.15.1@sha256:9857836c9ee4268391bb5b09f9f157f3c91bb15821bb77969642813b0d00518d

FROM registry.gitlab.com/uniget-org/images/ubuntu:rolling AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
curl --silent --show-error --location --fail --remote-name "https://dot.net/v1/dotnet-install.sh"
bash dotnet-install.sh --channel STS --version "${version}" --install-dir "${prefix}/opt/dotnet"
ln --symbolic --relative --force "${prefix}/opt/dotnet/dotnet" "${prefix}/bin/dotnet"
EOF