#syntax=docker/dockerfile:1.17.1@sha256:38387523653efa0039f8e1c89bb74a30504e76ee9f565e25c9a09841f9427b05

FROM registry.gitlab.com/uniget-org/images/ubuntu:rolling AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
curl --silent --show-error --location --fail --remote-name "https://dot.net/v1/dotnet-install.sh"
bash dotnet-install.sh --channel STS --version "${version}" --install-dir "${prefix}/opt/dotnet"
ln --symbolic --relative --force "${prefix}/opt/dotnet/dotnet" "${prefix}/bin/dotnet"
EOF