#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:059b11407572b2fd733e7bcd1c528852394d7fe1abef7119a1a97356983cab76 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
PLUGIN_VERSION="$( cut -d- -f1 <<< "${version}" )"
JOB_ID="$( cut -d- -f2 <<< "${version}" )"

mkdir -p "${prefix}/opt/luckperms"
for TYPE in Bukkit Forge NeoForge Sponge; do
    url="https://download.luckperms.net/${JOB_ID}/${TYPE,,}/loader/LuckPerms-${TYPE}-${PLUGIN_VERSION}.jar"
    filename="$( basename "${url}" )"

    check-download "${url}"
    curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
        "${url}"

    install --mode=0644 \
        "${uniget_cache_download}/${filename}" \
        "${prefix}/opt/luckperms/luckperms-${TYPE,,}.jar"
done
for TYPE in Fabric Velocity; do
    url="https://download.luckperms.net/${JOB_ID}/${TYPE,,}/LuckPerms-${TYPE}-${PLUGIN_VERSION}.jar"
    filename="$( basename "${url}" )"

    check-download "${url}"
    curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
        "${url}"

    install --mode=0644 \
        "${uniget_cache_download}/${filename}" \
        "${prefix}/opt/luckperms/luckperms-${TYPE,,}.jar"
done
EOF