#syntax=docker/dockerfile:1.7.0

FROM ghcr.io/uniget-org/tools/rust:latest AS rust

FROM ghcr.io/uniget-org/images/build-essential:24.04@sha256:ba81b156baf23840a73ed0dea64f1f6e70b0ff1f28451f29c84eafe613da87f7 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=rust / /usr/local/
WORKDIR /tmp/github.com/dandavison/delta
ARG name
ARG version
RUN <<EOF
git clone -q --config advice.detachedHead=false --depth 1 --branch "${version}" https://github.com/dandavison/delta .
export CARGO_HOME=/usr/local/cargo
export RUSTUP_HOME=/usr/local/rustup
export RUSTFLAGS='-C target-feature=+crt-static'
cargo build --release --target "${arch}-unknown-linux-gnu"
cp "target/${arch}-unknown-linux-gnu/release/delta" "${prefix}/bin/"
EOF