#syntax=docker/dockerfile

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
ln --symbolic --relative --force "${prefix}/opt/node22/bin/node" "${prefix}/bin/"
ln --symbolic --relative --force "${prefix}/opt/node22/bin/npm" "${prefix}/bin/"
EOF