#syntax=docker/dockerfile:1.7.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:98429d8ee1c7cf7d06f65b692870d983f0965f1c1cdffa1dd04ef878b56293b6 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]

ARG name
ARG version

RUN <<EOF
check-github-release-asset "roboll/helmfile" "v${version}" "helmfile_linux_${alt_arch}"
curl --silent --location --fail --output "${prefix}/bin/helmfile" \
    "https://github.com/roboll/helmfile/releases/download/v${version}/helmfile_linux_${alt_arch}"
chmod +x "${prefix}/bin/helmfile"
curl --silent --location --fail --output "${prefix}/share/bash-completion/completions/helmfile" \
    "https://github.com/roboll/helmfile/raw/v${version}/autocomplete/helmfile_bash_autocomplete"
curl --silent --location --fail --output "${prefix}/share/zsh/vendor-completions/_helmfile" \
    "https://github.com/roboll/helmfile/raw/v${version}/autocomplete/helmfile_zsh_autocomplete"
EOF