# yaml-language-server: $schema=https://tools.uniget.dev/schema.yaml
name: helmfile
description: Deploy Kubernetes Helm Charts
license:
  name: MIT License
  link: https://github.com/roboll/helmfile/blob/master/LICENSE
homepage: https://github.com/roboll/helmfile
repository: https://github.com/roboll/helmfile
version: "0.144.0"
tags:
- type/cli
- kubernetes
- templating
- lang/go
- state/stale
- k8s
- helm
check: ${binary} --version | cut -d' ' -f3 | tr -d v
platforms:
- linux/amd64
renovate:
  datasource: github-releases
  package: roboll/helmfile
  extractVersion: ^v(?<version>.+)$
