#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:b0b654de801604e256237f2c27a907a4b61b59ebd83423ad0e0e465c0a3ba9cd AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
echo "### Setting architecture string for ${TARGETPLATFORM}"
case "${arch}" in
    x86_64)
        export arch_suffix="${arch}"
        ;;
    aarch64)
        export arch_suffix="${alt_arch}"
        ;;
    *)
        echo "ERROR: Unsupported architecture ${arch}."
        exit 1
        ;;
esac
echo "    Using ${arch_suffix}"

url="https://github.com/charmbracelet/gum/releases/download/v${version}/gum_${version}_Linux_${arch_suffix}.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "charmbracelet/gum" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin/" --strip-components=1 --no-same-owner \
    "gum_${version}_Linux_${arch_suffix}/gum" \
    "gum_${version}_Linux_${arch_suffix}/manpages/gum.1.gz"
mv "${prefix}/bin/manpages/gum.1.gz" "${prefix}/share/man/man1/"
rmdir "${prefix}/bin/manpages"

"${prefix}/bin/gum" completion bash >"${prefix}/share/bash-completion/completions/gum"
"${prefix}/bin/gum" completion fish >"${prefix}/share/fish/vendor_completions.d/gum.fish"
"${prefix}/bin/gum" completion zsh >"${prefix}/share/zsh/vendor-completions/_gum"
EOF
