#syntax=docker/dockerfile:1.8.1

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:178a01206383923b589ecfe3bace55431c4b8528086909ffcdc1ef88de4da10f AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]

ARG name
ARG version

RUN <<EOF
check-github-release-asset "rupor-github/win-gpg-agent" "v${version}" "win-gpg-agent.zip"
curl --silent --show-error --location --fail --remote-name "https://github.com/rupor-github/win-gpg-agent/releases/download/v${version}/win-gpg-agent.zip"
unzip -q -o -d "/tmp" "win-gpg-agent.zip"
rm "win-gpg-agent.zip"
mv "/tmp/sorelay.exe" "${prefix}/bin"
EOF