#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/kubernetes-sigs/bom/releases/download/v${version}/bom-amd64-linux"
filename="$( basename "${url}" )"

check-github-release-asset "kubernetes-sigs/bom" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/bom"
"${prefix}/bin/bom" completion bash >"${prefix}/share/bash-completion/completions/bom"
"${prefix}/bin/bom" completion fish >"${prefix}/share/fish/vendor_completions.d/bom.fish"
"${prefix}/bin/bom" completion zsh >"${prefix}/share/zsh/vendor-completions/_bom"
EOF