#syntax=docker/dockerfile:1.10.0@sha256:865e5dd094beca432e8c0a1d5e1c465db5f998dca4e439981029b3b81fb39ed5

FROM ghcr.io/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "ovh/venom" "v${version}" "venom.linux-${alt_arch}"
curl --silent --show-error --location --fail --output "${prefix}/bin/venom" \
    "https://github.com/ovh/venom/releases/download/v${version}/venom.linux-${alt_arch}"
chmod +x "${prefix}/bin/venom"

"${prefix}/bin/venom" completion bash >"${prefix}/share/bash-completion/completions/venom"
"${prefix}/bin/venom" completion fish >"${prefix}/share/fish/vendor_completions.d/venom.fish"
"${prefix}/bin/venom" completion zsh >"${prefix}/share/zsh/vendor-completions/_venom"
EOF
