#syntax=docker/dockerfile:1.6.0

FROM ghcr.io/uniget-org/tools/cosign:latest AS cosign

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:da13a27933fac882122e16292dad3e4869a53dbbc52a73b4a5ddfbcde6902a99 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --from=cosign / /usr/local/
ARG name
ARG version
COPY kubelet.service ${prefix}/etc/systemd/system/
RUN <<EOF
curl --silent --location --fail --output "${prefix}/bin/kubeadm" \
    "https://storage.googleapis.com/kubernetes-release/release/v${version}/bin/linux/${alt_arch}/kubeadm"
chmod +x "${prefix}/bin/kubeadm"

if test "$(echo -e "1.26.0-beta.0\n${version}" | sort -V | head -n 1)" == "1.26.0-beta.0"; then
    echo "Verifying keyless signature for kubeadm"
    curl --silent --location --fail --output "/tmp/kubeadm.sig" \
        "https://dl.k8s.io/release/v${version}/bin/linux/${alt_arch}/kubeadm.sig"
    curl --silent --location --fail --output "/tmp/kubeadm.cert" \
        "https://dl.k8s.io/release/v${version}/bin/linux/${alt_arch}/kubeadm.cert"
    COSIGN_EXPERIMENTAL=1 cosign verify-blob "${prefix}/bin/kubeadm" \
        --signature "/tmp/kubeadm.sig" \
        --certificate "/tmp/kubeadm.cert" \
        --certificate-oidc-issuer https://accounts.google.com \
        --certificate-identity krel-staging@k8s-releng-prod.iam.gserviceaccount.com
    rm -f \
        "/tmp/kubeadm.sig" \
        "/tmp/kubeadm.cert"
fi

"${prefix}/bin/kubeadm" completion bash >"${prefix}/share/bash-completion/completions/kubeadm"
"${prefix}/bin/kubeadm" completion zsh >"${prefix}/share/zsh/vendor-completions/_kubeadm"
EOF