#syntax=docker/dockerfile:1.21.0@sha256:27f9262d43452075f3c410287a2c43f5ef1bf7ec2bb06e8c9eeb1b8d453087bc

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
check-github-release-asset "cheat/cheat" "${version}" "cheat-linux-${alt_arch}.gz"
curl --silent --show-error --location --fail "https://github.com/cheat/cheat/releases/download/${version}/cheat-linux-${alt_arch}.gz" \
| gunzip \
>"${prefix}/bin/cheat"
chmod +x "${prefix}/bin/cheat"

curl --silent --show-error --location --fail --output "${prefix}/share/man/man1/cheat.1" \
    "https://github.com/cheat/cheat/raw/${version}/doc/cheat.1"
EOF