#syntax=docker/dockerfile

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04 AS ubuntu2604

FROM ubuntu2604 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://cli.upbound.io/stable/v${version}/bin/linux_${alt_arch}/up"
filename="$( basename "${url}" )"

check-download "${url}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/up"
EOF
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://cli.upbound.io/stable/v${version}/bin/linux_${alt_arch}/docker-credential-up"
filename="$( basename "${url}" )"

check-download "${url}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/docker-credential-up"
EOF