#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
check-github-release-asset "sbt/sbt" "v${version}" "sbt-${version}.tgz"
mkdir -p "${prefix}/opt/sbt"
curl --silent --show-error --location --fail "https://github.com/sbt/sbt/releases/download/v${version}/sbt-${version}.tgz" \
| tar --extract --gzip --directory="${prefix}/opt/sbt" --strip-components=1 --no-same-owner \
    sbt/bin/sbt \
    sbt/bin/sbt-launch.jar \
    sbt/bin/sbtn-x86_64-pc-linux
ln --symbolic --relative --force "${prefix}/opt/sbt/bin/sbt" "${prefix}/bin/sbt"
EOF