#syntax=docker/dockerfile:1.8.1

FROM ghcr.io/uniget-org/tools/nodejs:${ref} AS nodejs
FROM ghcr.io/uniget-org/tools/npm:${ref} AS npm

FROM ghcr.io/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=nodejs / /
COPY --link --from=npm / /
WORKDIR /uniget_bootstrap/libexec/inshellisense
ARG name
ARG version
RUN <<EOF
npm install \
    --omit=dev \
    "@microsoft/inshellisense@${version}"
ln --symbolic --relative --force "${prefix}/libexec/inshellisense/node_modules/.bin/inshellisense" "${prefix}/bin/"
EOF