#syntax=docker/dockerfile:1.6.0

FROM ghcr.io/uniget-org/images/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
mkdir -p "${prefix}/etc/containers/registries.conf.d"
curl --silent --location --fail --output "${prefix}/etc/containers/registries.conf.d/00-shortnames.conf" \
    "https://github.com/containers/shortnames/raw/v${version}/shortnames.conf"
EOF