#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/uniget-org/tools/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
check-download "https://gitlab.alpinelinux.org/api/v4/projects/5/packages/generic//v${version}/${arch}/apk.static"

curl --silent --location --fail --output "${prefix}${target}/bin/apk" \
    "https://gitlab.alpinelinux.org/api/v4/projects/5/packages/generic//v${version}/${arch}/apk.static"
chmod +x "${prefix}${target}/bin/apk"
EOF