#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
RUN <<EOF
apt-get update
apt-get -y install --no-install-recommends \
    python3-pip \
    python3-setuptools \
    python3-venv \
    python-is-python3
EOF
WORKDIR /tmp/openapi2jsonschema
RUN <<EOF
git clone -q --config advice.detachedHead=false --depth 1 --branch master https://github.com/yannh/openapi2jsonschema .
EOF
RUN --mount=type=cache,target=/root/.cache/pip <<EOF
pip install --requirement requirements.txt --no-build-isolation --break-system-packages .
EOF
ARG name
ARG version
RUN <<EOF
echo "${name} ${version}"
mkdir -p "${prefix}/share/kubernetes/${version}"
mkdir -p "/tmp/openapi2jsonschema/${prefix}/usr/local/share/kubernetes/${version}"
python /tmp/openapi2jsonschema/openapi2jsonschema/command.py -o "${prefix}/share/kubernetes/${version}" --expanded --kubernetes --stand-alone --strict "https://github.com/kubernetes/kubernetes/raw/v${version}/api/openapi-spec/swagger.json"
python /tmp/openapi2jsonschema/openapi2jsonschema/command.py -o "${prefix}/share/kubernetes/${version}"            --kubernetes --stand-alone --strict "https://github.com/kubernetes/kubernetes/raw/v${version}/api/openapi-spec/swagger.json"
EOF
