#syntax=docker/dockerfile:1.6.0

FROM ghcr.io/uniget-org/tools/nodejs:latest AS nodejs
FROM ghcr.io/uniget-org/tools/npm:latest AS npm

FROM nicholasdille/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
COPY --link --from=nodejs / /
COPY --link --from=npm / /
WORKDIR ${prefix}${target}/libexec/github-copilot-cli
ARG name
ARG version
RUN <<EOF
npm install \
    --omit=dev \
    "@githubnext/github-copilot-cli@${version}"
ln --symbolic --relative --force "${prefix}${target}/libexec/github-copilot-cli/node_modules/.bin/github-copilot-cli" "${prefix}${target}/bin/"
EOF
COPY <<EOF ${prefix}${target}/etc/profile.d/github-copilot-cli.sh
eval "$(github-copilot-cli alias -- "$0")"
EOF
