#syntax=docker/dockerfile:1.6.0

FROM ghcr.io/uniget-org/tools/nodejs:latest AS nodejs
FROM ghcr.io/uniget-org/tools/npm:latest AS npm

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:da13a27933fac882122e16292dad3e4869a53dbbc52a73b4a5ddfbcde6902a99 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
COPY --link --from=nodejs / /usr/local/
COPY --link --from=npm / /usr/local/
WORKDIR /uniget_bootstrap/libexec/github-copilot-cli
ARG name
ARG version
RUN <<EOF
npm install \
    --omit=dev \
    "@githubnext/github-copilot-cli@${version}"
ln --symbolic --relative --force "${prefix}/libexec/github-copilot-cli/node_modules/.bin/github-copilot-cli" "${prefix}/bin/"
EOF
COPY <<EOF ${prefix}/etc/profile.d/github-copilot-cli.sh
eval "$(github-copilot-cli alias -- "$0")"
EOF
