#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/uniget-org/tools/nodejs:${ref} AS nodejs
FROM ghcr.io/uniget-org/tools/npm:${ref} AS npm

FROM ghcr.io/uniget-org/tools/base:${ref} AS prepare
ARG name
ARG version
COPY --link --from=nodejs / /
COPY --link --from=npm / /
WORKDIR ${prefix}${target}/libexec/github-copilot-cli
ARG name
ARG version
RUN <<EOF
npm install \
    --omit=dev \
    "@githubnext/github-copilot-cli@${version}"
ln --symbolic --relative --force "${prefix}${target}/libexec/github-copilot-cli/node_modules/.bin/github-copilot-cli" "${prefix}${target}/bin/"
EOF
COPY <<EOF ${prefix}${target}/etc/profile.d/github-copilot-cli.sh
eval "$(github-copilot-cli alias -- "$0")"
EOF
