#syntax=docker/dockerfile:1.25.0@sha256:0adf442eae370b6087e08edc7c50b552d80ddf261576f4ebd6421006b2461f12

FROM ghcr.io/uniget-org/tools/gh:latest AS gh

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:059b11407572b2fd733e7bcd1c528852394d7fe1abef7119a1a97356983cab76 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=gh / /usr/local/
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
check-github-release-asset "github/gh-copilot" "v${version}" "linux-${alt_arch}"
mkdir -p "${prefix}/share/gh/extensions/gh-copilot"
curl --silent --show-error --location --fail --output "${prefix}/share/gh/extensions/gh-copilot/gh-copilot" \
    "https://github.com/github/gh-copilot/releases/download/v${version}/linux-${alt_arch}"
chmod +x "${prefix}/share/gh/extensions/gh-copilot/gh-copilot"
EOF
COPY <<EOF uniget_bootstrap/share/gh/extensions/gh-copilot/manifest.yml.go-template
owner: github
name: gh-copilot
host: github.com
tag: v{{ .Version }}
ispinned: true
path: {{ .Target }}/share/gh/extensions/gh-copilot/gh-copilot
EOF