#syntax=docker/dockerfile:1.21.0@sha256:27f9262d43452075f3c410287a2c43f5ef1bf7ec2bb06e8c9eeb1b8d453087bc

FROM ghcr.io/uniget-org/tools/gh:latest AS gh

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=gh / /usr/local/
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
check-github-release-asset "github/gh-copilot" "v${version}" "linux-${alt_arch}"
mkdir -p "${prefix}/share/gh/extensions/gh-copilot"
curl --silent --show-error --location --fail --output "${prefix}/share/gh/extensions/gh-copilot/gh-copilot" \
    "https://github.com/github/gh-copilot/releases/download/v${version}/linux-${alt_arch}"
chmod +x "${prefix}/share/gh/extensions/gh-copilot/gh-copilot"
EOF
COPY <<EOF uniget_bootstrap/share/gh/extensions/gh-copilot/manifest.yml.go-template
owner: github
name: gh-copilot
host: github.com
tag: v{{ .Version }}
ispinned: true
path: {{ .Target }}/share/gh/extensions/gh-copilot/gh-copilot
EOF