#syntax=docker/dockerfile:1.24.0@sha256:87999aa3d42bdc6bea60565083ee17e86d1f3339802f543c0d03998580f9cb89

FROM ghcr.io/uniget-org/tools/gh:latest AS gh

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:99a2bccd1ad68bfc5b1d1eb356cf54b7dd94e45c5216b89c87b9e21c70e12b9f AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=gh / /usr/local/
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
check-github-release-asset "github/gh-copilot" "v${version}" "linux-${alt_arch}"
mkdir -p "${prefix}/share/gh/extensions/gh-copilot"
curl --silent --show-error --location --fail --output "${prefix}/share/gh/extensions/gh-copilot/gh-copilot" \
    "https://github.com/github/gh-copilot/releases/download/v${version}/linux-${alt_arch}"
chmod +x "${prefix}/share/gh/extensions/gh-copilot/gh-copilot"
EOF
COPY <<EOF uniget_bootstrap/share/gh/extensions/gh-copilot/manifest.yml.go-template
owner: github
name: gh-copilot
host: github.com
tag: v{{ .Version }}
ispinned: true
path: {{ .Target }}/share/gh/extensions/gh-copilot/gh-copilot
EOF