#syntax=docker/dockerfile:1.15.1@sha256:05e0ad437efefcf144bfbf9d7f728c17818408e6d01432d9e264ef958bbd52f3

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/CycloneDX/sbom-utility/releases/download/v${version}/sbom-utility-v${version}-linux-${alt_arch}.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "CycloneDX/sbom-utility" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin/" --no-same-owner \
    sbom-utility \
    config.json \
    custom.json \
    license.json

"${prefix}/bin/sbom-utility" completion bash >"${prefix}/share/bash-completion/completions/sbom-utility"
"${prefix}/bin/sbom-utility" completion fish >"${prefix}/share/fish/vendor_completions.d/sbom-utility.fish"
"${prefix}/bin/sbom-utility" completion zsh >"${prefix}/share/zsh/vendor-completions/_sbom-utility"
EOF