#syntax=docker/dockerfile:1.10.0@sha256:865e5dd094beca432e8c0a1d5e1c465db5f998dca4e439981029b3b81fb39ed5

FROM ghcr.io/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
RUN <<EOF
apt-get update
apt-get -y install --no-install-recommends \
    zsh
EOF
ARG name
ARG version
RUN <<EOF
check-github-release-asset "earthly/earthly" "v${version}" "earthly-linux-${alt_arch}"
curl --silent --show-error --location --fail --output "${prefix}/bin/earthly" \
    "https://github.com/earthly/earthly/releases/download/v${version}/earthly-linux-${alt_arch}"
chmod +x "${prefix}/bin/earthly"
"${prefix}/bin/earthly" bootstrap --with-autocomplete --no-buildkit
cp /usr/share/bash-completion/completions/earthly "${prefix}/share/bash-completion/completions/earthly"
sed -i "s|${prefix}||" "${prefix}/share/bash-completion/completions/earthly"
cp /usr/local/share/zsh/site-functions/_earthly "${prefix}/share/zsh/vendor-completions/_earthly"
sed -i "s|${prefix}||" "${prefix}/share/zsh/vendor-completions/_earthly"
EOF