#syntax=docker/dockerfile:1.25.0@sha256:0adf442eae370b6087e08edc7c50b552d80ddf261576f4ebd6421006b2461f12

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:059b11407572b2fd733e7bcd1c528852394d7fe1abef7119a1a97356983cab76 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
RUN --mount=type=cache,target=/var/cache/apt <<EOF
apt-get update
apt-get -y install --no-install-recommends \
    zsh
EOF
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/earthly/earthly/releases/download/v${version}/earthly-linux-${alt_arch}"
filename="$( basename "${url}" )"

check-github-release-asset "earthly/earthly" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/earthly"

"${prefix}/bin/earthly" bootstrap --with-autocomplete --no-buildkit
cp /usr/share/bash-completion/completions/earthly "${prefix}/share/bash-completion/completions/earthly"
sed -i "s|${prefix}||" "${prefix}/share/bash-completion/completions/earthly"
cp /usr/local/share/zsh/site-functions/_earthly "${prefix}/share/zsh/vendor-completions/_earthly"
sed -i "s|${prefix}||" "${prefix}/share/zsh/vendor-completions/_earthly"
EOF