#syntax=docker/dockerfile:1.7.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:98429d8ee1c7cf7d06f65b692870d983f0965f1c1cdffa1dd04ef878b56293b6 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
RUN <<EOF
apt-get update
apt-get -y install --no-install-recommends \
    zsh
EOF
ARG name
ARG version
RUN <<EOF
check-github-release-asset "earthly/earthly" "v${version}" "earthly-linux-${alt_arch}"
curl --silent --location --fail --output "${prefix}/bin/earthly" \
    "https://github.com/earthly/earthly/releases/download/v${version}/earthly-linux-${alt_arch}"
chmod +x "${prefix}/bin/earthly"
"${prefix}/bin/earthly" bootstrap --with-autocomplete --no-buildkit
cp /usr/share/bash-completion/completions/earthly "${prefix}/share/bash-completion/completions/earthly"
sed -i "s|${prefix}||" "${prefix}/share/bash-completion/completions/earthly"
cp /usr/local/share/zsh/site-functions/_earthly "${prefix}/share/zsh/vendor-completions/_earthly"
sed -i "s|${prefix}||" "${prefix}/share/zsh/vendor-completions/_earthly"
EOF