#syntax=docker/dockerfile:1.6.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:da13a27933fac882122e16292dad3e4869a53dbbc52a73b4a5ddfbcde6902a99 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "reproducible-containers/diffoci" "v${version}" "diffoci-v${version}.linux-${alt_arch}"
curl --silent --location --fail --output "${prefix}/bin/diffoci" \
    "https://github.com/reproducible-containers/diffoci/releases/download/v${version}/diffoci-v${version}.linux-${alt_arch}"
chmod +x "${prefix}/bin/diffoci"

"${prefix}/bin/diffoci" completion bash >"${prefix}/share/bash-completion/completions/diffoci"
"${prefix}/bin/diffoci" completion fish >"${prefix}/share/fish/vendor_completions.d/diffoci.fish"
"${prefix}/bin/diffoci" completion zsh >"${prefix}/share/zsh/vendor-completions/_diffoci"
EOF