#syntax=docker/dockerfile:1.6.0

FROM ghcr.io/uniget-org/tools/rust:latest AS rust

FROM nicholasdille/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --from=rust / /usr/local/
ARG DEBIAN_FRONTEND=noninteractive
RUN <<EOF
apt-get update
apt-get -y install --no-install-recommends \
    build-essential
EOF
WORKDIR /tmp/github.com/stepchowfun/docuum
ARG name
ARG version
RUN <<EOF
source "/etc/profile.d/cargo.sh"
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/stepchowfun/docuum .
export RUSTFLAGS='-C target-feature=+crt-static'
cargo build --release --target x86_64-unknown-linux-gnu
cp target/x86_64-unknown-linux-gnu/release/docuum "${prefix}/bin/"
EOF