#syntax=docker/dockerfile:1.11.0@sha256:1f2be5a2aa052cbd9aedf893d17c63277c3d1c51b3fb0f3b029c6b34f658d057

FROM ghcr.io/uniget-org/tools/rust:latest AS rust

FROM registry.gitlab.com/uniget-org/images/build-essential:24.04@sha256:763459acb3fdb5c0dc947b211fe8815cde4d06ec1535125db0d7c0e22a357abd AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=rust / /usr/local/
WORKDIR /tmp/github.com/stepchowfun/docuum
ARG name
ARG version
RUN --mount=type=cache,target=/target \
    --mount=type=cache,target=/usr/local/cargo/registry <<EOF
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/stepchowfun/docuum .
export CARGO_HOME=/usr/local/cargo
export CARGO_TARGET_DIR=/target
export RUSTUP_HOME=/usr/local/rustup
export RUSTFLAGS='-C target-feature=+crt-static'
cargo build --release --target "${arch}-unknown-linux-gnu"
cp "/target/${arch}-unknown-linux-gnu/release/docuum" "${prefix}/bin/"
EOF