#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM ghcr.io/uniget-org/tools/go:latest AS go
FROM ghcr.io/uniget-org/tools/make:latest AS make

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:059b11407572b2fd733e7bcd1c528852394d7fe1abef7119a1a97356983cab76 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=go / /usr/local/
COPY --link --from=make / /usr/local/
WORKDIR $GOPATH/src/github.com/cpuguy83/go-md2man
ARG name
ARG version
RUN git clone --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/cpuguy83/go-md2man.git .
ENV CGO_ENABLED=0
RUN make -j$(nproc) bin/go-md2man \
 && mv bin/go-md2man "${prefix}/bin/"
RUN "${prefix}/bin/go-md2man" -in ./go-md2man.1.md -out ./go-md2man.1 \
 && mv go-md2man.1 "${prefix}/share/man/man1/"
