#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:059b11407572b2fd733e7bcd1c528852394d7fe1abef7119a1a97356983cab76 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/scala/scala3/releases/download/${version}/scala3-${version}-${arch}-pc-linux.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "scala/scala3" "${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
mkdir -p "${prefix}/opt/scala3"
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/opt/scala3" --strip-components=1 --no-same-owner

ln --symbolic --relative --force \
    "${prefix}/opt/scala3/bin/scala" \
    "${prefix}/bin/scala"
ln --symbolic --relative --force \
    "${prefix}/opt/scala3/bin/scalac" \
    "${prefix}/bin/scalac"
EOF