#syntax=docker/dockerfile:1.6.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:da13a27933fac882122e16292dad3e4869a53dbbc52a73b4a5ddfbcde6902a99 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "helm/chart-testing" "v${version}" "chart-testing_${version}_linux_${alt_arch}.tar.gz"
curl --silent --location --fail "https://github.com/helm/chart-testing/releases/download/v${version}/chart-testing_${version}_linux_${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/bin/" --no-same-owner \
    ct \
    etc
mkdir -p "${prefix}/etc/ct"
mv "${prefix}/bin/etc/chart_schema.yaml" "${prefix}/etc/ct/"
mv "${prefix}/bin/etc/lintconf.yaml" "${prefix}/etc/ct/"
rmdir "${prefix}/bin/etc"

"${prefix}/bin/ct" completion bash >"${prefix}/share/bash-completion/completions/ct"
"${prefix}/bin/ct" completion fish >"${prefix}/share/fish/vendor_completions.d/ct.fish"
"${prefix}/bin/ct" completion zsh >"${prefix}/share/zsh/vendor-completions/_ct"
EOF
