#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:b0b654de801604e256237f2c27a907a4b61b59ebd83423ad0e0e465c0a3ba9cd AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version

RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/uutils/coreutils/releases/download/${version}/coreutils-${version}-${arch}-unknown-linux-musl.tar.gz"
filename="$( basename "${url}" )"

check-download "${url}"
check-github-release-asset "uutils/coreutils" "${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin/" --strip-components=1 --no-same-owner \
    "coreutils-${version}-${arch}-unknown-linux-musl/coreutils"
EOF
RUN <<EOF
curl --silent --show-error --location --fail "https://github.com/uutils/coreutils/releases/download/${version}/docs.tar.zst" \
| tar --extract --zstd --directory="${prefix}"
find "${prefix}/share/zsh/site-functions/" -type f -exec mv {} "${prefix}/share/zsh/vendor-completions/" \;
rmdir "${prefix}/share/zsh/site-functions/"
rm -rf "${prefix}/share/elvish/"
EOF
RUN <<EOF
"${prefix}/bin/coreutils" --list | xargs -I{} ln --symbolic --relative --force "${prefix}/bin/coreutils" "${prefix}/bin/{}"
EOF
