#syntax=docker/dockerfile:1.8.1

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:178a01206383923b589ecfe3bace55431c4b8528086909ffcdc1ef88de4da10f AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "deislabs/containerd-wasm-shims" "v${version}" "containerd-wasm-shims-v1-slight-linux-${arch}.tar.gz"
curl --silent --show-error --location --fail "https://github.com/deislabs/containerd-wasm-shims/releases/download/v${version}/containerd-wasm-shims-v1-slight-linux-${arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/bin/" --no-same-owner
EOF