#syntax=docker/dockerfile:1.7.0

FROM ghcr.io/uniget-org/images/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "chrismellard/docker-credential-acr-env" "${version}" "docker-credential-acr-env_${version}_linux_${alt_arch}.tar.gz"
curl --silent --location --fail "https://github.com/chrismellard/docker-credential-acr-env/releases/download/${version}/docker-credential-acr-env_${version}_linux_${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/bin" --no-same-owner \
    docker-credential-acr-env
EOF