#syntax=docker/dockerfile:1.21.0@sha256:27f9262d43452075f3c410287a2c43f5ef1bf7ec2bb06e8c9eeb1b8d453087bc

FROM ghcr.io/uniget-org/tools/go:latest AS go

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/grafana/mimir/releases/download/mimir-${version}/mimirtool-linux-${alt_arch}"
filename="$( basename "${url}" )"

check-github-release-asset "grafana/mimir" "mimir-${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/mimirtool"
EOF
COPY --link --from=go / /usr/local/
WORKDIR /go/src/github.com/foo/bar
RUN <<EOF
check-clone "https://github.com/grafana/mimir" "mimir-${version}"
git clone -q --config advice.detachedHead=false --depth 1 --branch "mimir-${version}" https://github.com/grafana/mimir .
EOF
RUN --mount=type=cache,target=/root/go/pkg/mod <<EOF
go build -o "${prefix}/bin/copyblocks" ./tools/copyblocks
go build -o "${prefix}/bin/copyprefix" ./tools/copyprefix
go build -o "${prefix}/bin/listblocks" ./tools/listblocks
go build -o "${prefix}/bin/mark-blocks" ./tools/mark-blocks
go build -o "${prefix}/bin/splitblocks" ./tools/splitblocks
EOF