#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM registry.gitlab.com/uniget-org/images/build-base:3.24@sha256:6c6c414a06d0c48a6a05e1b3fe6940529179f7ed617dccbbcf4f2424383b1014 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
RUN --mount=type=cache,target=/var/cache/apk <<EOF
apk add --update-cache \
    meson \
    clang \
    xz \
    libselinux-dev \
    libcap-dev \
    libcap-static \
    libxslt \
    docbook-xsl
EOF
WORKDIR /tmp/bwrap
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/containers/bubblewrap/releases/download/v${version}/bubblewrap-${version}.tar.xz"
filename="$( basename "${url}" )"

check-github-release-asset "containers/bubblewrap" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --xz --strip-components=1
EOF
COPY meson.build.patch /tmp/
RUN <<EOF
export CC="clang"
export CFLAGS="-O2 -Werror=unused-variable"
patch -p0 <../meson.build.patch
meson setup build \
    --prefix="${prefix}" \
    -Dselinux=disabled \
    -Dbash_completion=enabled \
    -Dbash_completion_dir="${prefix}/share/bash-completion/completions" \
    -Dzsh_completion=enabled \
    -Dzsh_completion_dir="${prefix}/share/zsh/vendor-completions" \
    -Dman=enabled
meson compile -C build
meson install -C build
EOF
