#syntax=docker/dockerfile:1.24.0@sha256:87999aa3d42bdc6bea60565083ee17e86d1f3339802f543c0d03998580f9cb89

FROM registry.gitlab.com/uniget-org/images/build-base:3.23@sha256:b3f7e2f78a9eda4260453779505b7054d137bf5c136dead92fc8e9240eb00835 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
RUN --mount=type=cache,target=/var/cache/apk <<EOF
apk add --update-cache \
    meson \
    clang \
    xz \
    libselinux-dev \
    libcap-dev \
    libcap-static \
    libxslt \
    docbook-xsl
EOF
WORKDIR /tmp/bwrap
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/containers/bubblewrap/releases/download/v${version}/bubblewrap-${version}.tar.xz"
filename="$( basename "${url}" )"

check-github-release-asset "containers/bubblewrap" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --xz --strip-components=1
EOF
COPY meson.build.patch /tmp/
RUN <<EOF
export CC="clang"
export CFLAGS="-O2 -Werror=unused-variable"
patch -p0 <../meson.build.patch
meson setup build \
    --prefix="${prefix}" \
    -Dselinux=disabled \
    -Dbash_completion=enabled \
    -Dbash_completion_dir="${prefix}/share/bash-completion/completions" \
    -Dzsh_completion=enabled \
    -Dzsh_completion_dir="${prefix}/share/zsh/vendor-completions" \
    -Dman=enabled
meson compile -C build
meson install -C build
EOF
