#syntax=docker/dockerfile:1.27.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/alpine:3.24@sha256:3a9a59f6df17a6d831f3ccd5f27663d3e0c9821cf14f69da207f17421903a2c2 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://get.helm.sh/helm-v${version}-linux-${alt_arch}.tar.gz"
filename="$(basename "${url}")"

curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin" --strip-components=1 --no-same-owner \
    "linux-${alt_arch}/helm"

"${prefix}/bin/helm" completion bash >"${prefix}/share/bash-completion/completions/helm"
"${prefix}/bin/helm" completion fish >"${prefix}/share/fish/vendor_completions.d/helm.fish"
"${prefix}/bin/helm" completion zsh >"${prefix}/share/zsh/vendor-completions/_helm"
EOF
