#syntax=docker/dockerfile:1.7.1

FROM ghcr.io/uniget-org/images/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
curl --silent --show-error --location --fail "https://get.helm.sh/helm-v${version}-linux-${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/bin" --strip-components=1 --no-same-owner \
    linux-${alt_arch}/helm
"${prefix}/bin/helm" completion bash >"${prefix}/share/bash-completion/completions/helm"
"${prefix}/bin/helm" completion fish >"${prefix}/share/fish/vendor_completions.d/helm.fish"
"${prefix}/bin/helm" completion zsh >"${prefix}/share/zsh/vendor-completions/_helm"
EOF
