#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/uniget-org/tools/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
url="https://github.com/opentofu/opentofu/releases/download/v${version}/tofu_${version}_linux_${alt_arch}.zip"
check-github-release-asset "opentofu/opentofu" "v${version}" "tofu_${version}_linux_${alt_arch}.zip"
filename="$(basename "${url}")"
curl --silent --location --fail --remote-name "${url}"
unzip -q -o -d "${prefix}${target}/bin" "${filename}" \
    tofu
EOF