#syntax=docker/dockerfile:1.6.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:da13a27933fac882122e16292dad3e4869a53dbbc52a73b4a5ddfbcde6902a99 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "whalebrew/whalebrew" "${version}" "whalebrew-Linux-x86_64"
curl --silent --location --fail --output "${prefix}/bin/whalebrew" \
    "https://github.com/whalebrew/whalebrew/releases/download/${version}/whalebrew-Linux-x86_64"
chmod +x "${prefix}/bin/whalebrew"

"${prefix}/bin/whalebrew" completion bash >"${prefix}/share/bash-completion/completions/whalebrew"
"${prefix}/bin/whalebrew" completion fish >"${prefix}/share/fish/vendor_completions.d/whalebrew.fish"
"${prefix}/bin/whalebrew" completion zsh >"${prefix}/share/zsh/vendor-completions/_whalebrew"
EOF