#syntax=docker/dockerfile:1.21.0@sha256:26147acbda4f14c5add9946e2fd2ed543fc402884fd75146bd342a7f6271dc1d

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/whalebrew/whalebrew/releases/download/${version}/whalebrew-Linux-x86_64"
filename="$( basename "${url}" )"

check-github-release-asset "whalebrew/whalebrew" "${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/whalebrew"


"${prefix}/bin/whalebrew" completion bash >"${prefix}/share/bash-completion/completions/whalebrew"
"${prefix}/bin/whalebrew" completion fish >"${prefix}/share/fish/vendor_completions.d/whalebrew.fish"
"${prefix}/bin/whalebrew" completion zsh >"${prefix}/share/zsh/vendor-completions/_whalebrew"
EOF