#syntax=docker/dockerfile:1.8.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:178a01206383923b589ecfe3bace55431c4b8528086909ffcdc1ef88de4da10f AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-download "https://github.com/projectdiscovery/nuclei-templates/archive/refs/tags/v${version}.tar.gz"

mkdir -p "${prefix}/share/nuclei-templates/"
curl --silent --show-error --location --fail "https://github.com/projectdiscovery/nuclei-templates/archive/refs/tags/v${version}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/share/nuclei-templates/" --strip-components=1 --no-same-owner
EOF