#syntax=docker/dockerfile:1.25.0@sha256:0adf442eae370b6087e08edc7c50b552d80ddf261576f4ebd6421006b2461f12

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:059b11407572b2fd733e7bcd1c528852394d7fe1abef7119a1a97356983cab76 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
WORKDIR /uniget_bootstrap/share/nuclei-templates
ARG name
ARG version
RUN <<EOF
url="https://github.com/projectdiscovery/nuclei-templates/archive/refs/tags/v${version}.tar.gz"
filename="$( basename "${url}" )"

check-download "${url}"
curl --silent --show-error --location --fail --output "/tmp/${filename}" \
    "${url}"

tar --file="/tmp/${filename}" --list
tar --file="/tmp/${filename}" --extract --gzip --strip-components=1 --no-same-owner
EOF