#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM ghcr.io/uniget-org/tools/go:latest AS go
FROM ghcr.io/uniget-org/tools/make:latest AS make

FROM registry.gitlab.com/uniget-org/images/build-base:3.24@sha256:bfcf3e99a47ac1b07f9dd40db914d12a3a15f5b886a9e7f35a60be58c9d294bc AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=go / /usr/local/
COPY --link --from=make / /usr/local/
WORKDIR /go/src/github.com/Azure/acr-cli
ARG name
ARG version
RUN <<EOF
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/Azure/acr-cli .
make -j$(nproc) binaries GO_LDFLAGS="-ldflags '-s -w -linkmode external -extldflags -static'"
cp bin/acr "${prefix}/bin/"

"${prefix}/bin/acr" completion bash >"${prefix}/share/bash-completion/completions/acr"
"${prefix}/bin/acr" completion fish >"${prefix}/share/fish/vendor_completions.d/acr.fish"
"${prefix}/bin/acr" completion zsh >"${prefix}/share/zsh/vendor-completions/_acr"
EOF
