#syntax=docker/dockerfile:1.6.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:da13a27933fac882122e16292dad3e4869a53dbbc52a73b4a5ddfbcde6902a99 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
export NVM_DIR="${prefix}/opt/nvm"
mkdir -p "${NVM_DIR}"
curl --silent --location --fail https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
EOF