#syntax=docker/dockerfile:1.25.0@sha256:0adf442eae370b6087e08edc7c50b552d80ddf261576f4ebd6421006b2461f12

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:059b11407572b2fd733e7bcd1c528852394d7fe1abef7119a1a97356983cab76 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/zricethezav/gitleaks/releases/download/v${version}/gitleaks_${version}_linux_x64.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "zricethezav/gitleaks" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin/" --no-same-owner \
    gitleaks
"${prefix}/bin/gitleaks" completion bash >"${prefix}/share/bash-completion/completions/gitleaks"
"${prefix}/bin/gitleaks" completion fish >"${prefix}/share/fish/vendor_completions.d/gitleaks.fish"
"${prefix}/bin/gitleaks" completion zsh >"${prefix}/share/zsh/vendor-completions/_gitleaks"
EOF