variables:
  METADATA_CHANGES_FROM_SHA:
    description: Force pipeline to collect changes relative to supplied commit SHA
  METADATA_ONLY:
    description: Build metadata only
    value: "false"
    options:
    - "false"
    - "true"
  BUILD_TOOL_NAME:
    description: Name of tool to build

.docker:
  variables:
    DOCKER_CERT_DIR: ""
  services:
  - name: docker:29.5.0-dind@sha256:8e3fae900cbfbdc14e8abca89a9e44363065cb535f34a09283c59cc0dde2de20
  image: docker:29.5.0@sha256:8e3fae900cbfbdc14e8abca89a9e44363065cb535f34a09283c59cc0dde2de20
  before_script: |
    echo "${CI_REGISTRY_PASSWORD}" \
    | docker login "${CI_REGISTRY}" \
        --username="${CI_REGISTRY_USER}" \
        --password-stdin
  after_script: |
    docker logout "${CI_REGISTRY}"

build_single:
  rules:
  - if: $CI_PIPELINE_SOURCE == "web" && $BUILD_TOOL_NAME
  trigger:
    include:
    - local: pipeline/build.yaml
      inputs:
        name: $BUILD_TOOL_NAME
    strategy: mirror

dev_download:
  rules:
  - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - if: $CI_PIPELINE_SOURCE == "web" && $BUILD_TOOL_NAME == ""
  - if: $METADATA_ONLY == "true"
  image: registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:99a2bccd1ad68bfc5b1d1eb356cf54b7dd94e45c5216b89c87b9e21c70e12b9f
  script: |
    curl --silent --show-error --location --fail https://gitlab.com/uniget-org/dev/-/releases/permalink/latest/downloads/dev_Linux_$(uname -m).tar.gz \
    | tar --extract --gzip dev
    ./dev --version
  artifacts:
    paths:
    - dev

collect:
  rules:
  - if: $METADATA_ONLY == "true"
    when: never
  - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    needs:
    - dev_download
  - if: $CI_PIPELINE_SOURCE == "web" && $BUILD_TOOL_NAME == ""
    needs:
    - dev_download
  image: alpine:3.23.4@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11
  script: |
    ./dev metadata changes --from="$METADATA_CHANGES_FROM_SHA" | tee changes.txt
    TOOLS="$( cat changes.txt | xargs echo | tr ' ' , )"
    if test "${TOOLS}" == ""; then
        cat >build.yaml <<EOF
    build:
      script: echo "No tools to build"
    EOF

    else
        cat >build.yaml <<EOF
    build:
      parallel:
        matrix:
        - TOOL: [$TOOLS]
      trigger:
        include:
        - local: pipeline/build.yaml
          inputs:
            name: \${TOOL}
            arch: [amd64, arm64]
        strategy: mirror
    EOF
    fi
  artifacts:
    paths:
    - changes.txt
    - build.yaml
    expire_in: 4 days

build_trigger:
  rules:
  - if: $METADATA_ONLY == "true"
    when: never
  - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    needs:
    - collect
  - if: $CI_PIPELINE_SOURCE == "web" && $BUILD_TOOL_NAME == ""
    needs:
    - collect
  trigger:
    include:
    - artifact: build.yaml
      job: collect
    strategy: mirror

metadata:
  rules:
  - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    needs:
    - dev_download
    - build_trigger
  - if: $METADATA_ONLY == "true"
    needs:
    - dev_download
  extends:
  - .docker
  script:
  - docker buildx create --name=uniget --bootstrap --use
  - ./dev metadata build
