variables:
  METADATA_CHANGES_FROM_SHA:
    description: Force pipeline to collect changes relative to supplied commit SHA
  METADATA_ONLY:
    description: Build metadata only
    value: "false"
    options:
    - "false"
    - "true"
  BUILD_TOOL_NAME:
    description: Name of tool to build
  SKIP_BUILD:
    description: Skip build stage
    value: "true"
    options:
    - "true"
    - "false"

.docker:
  variables:
    DOCKER_CERT_DIR: ""
  services:
  - name: docker:29.6.1-dind@sha256:66d292e5c26bd33a6f6f61cacb880de2186339a524ecba1ce098dbbaceed6515
  image: docker:29.6.1@sha256:66d292e5c26bd33a6f6f61cacb880de2186339a524ecba1ce098dbbaceed6515
  before_script: |
    echo "${CI_REGISTRY_PASSWORD}" \
    | docker login "${CI_REGISTRY}" \
        --username="${CI_REGISTRY_USER}" \
        --password-stdin
  after_script: |
    docker logout "${CI_REGISTRY}"

build_single:
  rules:
  - if: $CI_PIPELINE_SOURCE == "web" && $BUILD_TOOL_NAME
  trigger:
    include:
    - local: pipeline/build.yaml
      inputs:
        name: $BUILD_TOOL_NAME
    strategy: mirror

dev_download:
  rules:
  - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - if: $CI_PIPELINE_SOURCE == "web" && $BUILD_TOOL_NAME == ""
  - if: $METADATA_ONLY == "true"
  image: registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:059b11407572b2fd733e7bcd1c528852394d7fe1abef7119a1a97356983cab76
  script: |
    curl --silent --show-error --location --fail https://gitlab.com/uniget-org/dev/-/releases/permalink/latest/downloads/dev_Linux_$(uname -m).tar.gz \
    | tar --extract --gzip dev
    ./dev --version
  artifacts:
    paths:
    - dev

uniget_download:
  rules:
  - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - if: $CI_PIPELINE_SOURCE == "web" && $BUILD_TOOL_NAME == ""
  - if: $METADATA_ONLY == "true"
  image: registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:059b11407572b2fd733e7bcd1c528852394d7fe1abef7119a1a97356983cab76
  script: |
    curl --silent --show-error --location --fail https://gitlab.com/uniget-org/cli/-/releases/permalink/latest/downloads/uniget_Linux_$(uname -m).tar.gz \
    | tar --extract --gzip uniget
    ./uniget --version
  artifacts:
    paths:
    - uniget

collect:
  rules:
  - if: $METADATA_ONLY == "true"
    when: never
  - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    needs:
    - dev_download
  - if: $CI_PIPELINE_SOURCE == "web" && $BUILD_TOOL_NAME == ""
    needs:
    - dev_download
  image: alpine:3.24.1@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
  script: |
    ./dev metadata changes --from="$METADATA_CHANGES_FROM_SHA" | tee changes.txt
    TOOLS="$( cat changes.txt | xargs echo | tr ' ' , )"
    if test "${TOOLS}" == ""; then
        cat >build.yaml <<EOF
    build:
      script: echo "No tools to build"
    EOF

    else
        cat >build.yaml <<EOF
    build:
      parallel:
        matrix:
        - TOOL: [$TOOLS]
      trigger:
        include:
        - local: pipeline/build.yaml
          inputs:
            name: \${TOOL}
            arch: [amd64, arm64]
        strategy: mirror
    EOF
    fi
  artifacts:
    paths:
    - changes.txt
    - build.yaml
    expire_in: 4 days

build_trigger:
  rules:
  - if: $METADATA_ONLY == "true"
    when: never
  - if: $SKIP_BUILD == "true"
    when: never
  - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    needs:
    - collect
  - if: $CI_PIPELINE_SOURCE == "web" && $BUILD_TOOL_NAME == ""
    needs:
    - collect
  trigger:
    include:
    - artifact: build.yaml
      job: collect
    strategy: mirror

metadata:
  rules:
  - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    needs:
    - dev_download
    - uniget_download
    - build_trigger
  - if: $METADATA_ONLY == "true"
    needs:
    - dev_download
    - uniget_download
  - if: $SKIP_BUILD == "true"
    needs:
    - dev_download
    - uniget_download
  extends:
  - .docker
  id_tokens:
    SIGSTORE_ID_TOKEN:
      aud: sigstore
  script:
  - ./uniget install cosign
  - cosign version
  - docker buildx create --name=uniget --bootstrap --use
  - ./dev metadata create
  - ./dev metadata sign
  - ./dev metadata build
