.docker:
  variables:
    DOCKER_CERT_DIR: ""
  services:
  - name: docker:29.4.1-dind@sha256:c77e5d7912f9b137cc67051fdc2991d8f5ae22c55ddf532bb836dcb693a04940
  image: docker:29.4.1@sha256:c77e5d7912f9b137cc67051fdc2991d8f5ae22c55ddf532bb836dcb693a04940
  before_script: |
    echo "${CI_REGISTRY_PASSWORD}" \
    | docker login "${CI_REGISTRY}" \
        --username="${CI_REGISTRY_USER}" \
        --password-stdin
  after_script: |
    docker logout "${CI_REGISTRY}"

.uniget:
  before_script: |
    apk add --update-cache \
        curl
  script: |
    curl -sLf https://gitlab.com/uniget-org/cli/-/releases/permalink/latest/downloads/uniget_Linux_$(uname -m).tar.gz \
    | tar -xzC /usr/local/bin uniget

dev_download:
  rules:
  - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - if: $CI_PIPELINE_SOURCE == "web"
  image: registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0aa2d228f23334e74ff9b4b56fa4b35a720e29280b934b6b925ad9a221e804d3
  script: |
    curl --silent --show-error --location --fail https://gitlab.com/uniget-org/dev/-/releases/permalink/latest/downloads/dev_Linux_$(uname -m).tar.gz \
    | tar --extract --gzip dev
    ./dev --version
  artifacts:
    paths:
    - dev

collect:
  rules:
  - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - if: $CI_PIPELINE_SOURCE == "web"
  needs:
  - dev_download
  image: alpine:3.23.4@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11
  script: |
    ./dev metadata changes | tee changes.txt
    cat >>build.yaml <<EOF
    build:
      parallel:
        matrix:
        - TOOL: [a, b, c]
      script: echo "TOOL=${TOOL}"
    EOF
  artifacts:
    paths:
    - changes.txt
    - build.yaml

build_trigger:
  rules:
  - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - if: $CI_PIPELINE_SOURCE == "web"
  needs:
  - collect
  trigger:
    include:
    - artifact: build.yaml
      job: collect

metadata:
  rules:
  - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  needs:
  - dev_download
  - collect
  extends:
  - .docker
  script:
  - docker buildx create --name=uniget --bootstrap --use
  - ./dev metadata build
