#syntax=docker/dockerfile:1.7.0

FROM ghcr.io/uniget-org/images/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "grafana/loki" "v${version}" "loki-linux-${alt_arch}.zip"
url="https://github.com/grafana/loki/releases/download/v${version}/loki-linux-${alt_arch}.zip"
filename="$(basename "${url}")"
curl --silent --location --fail --remote-name "${url}"
unzip -q -o -d "${prefix}/bin" "${filename}"
mv "${prefix}/bin/loki-linux-${alt_arch}" "${prefix}/bin/loki"
EOF