#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
echo "### Setting architecture string for ${TARGETPLATFORM}"
case "${arch}" in
    x86_64)
        export arch_suffix="${arch}"
        ;;
    aarch64)
        export arch_suffix="${alt_arch}"
        ;;
    *)
        echo "ERROR: Unsupported architecture ${arch}."
        exit 1
        ;;
esac
echo "    Using ${arch_suffix}"

url="https://github.com/MacroPower/kat/releases/download/v${version}/kat_Linux_${arch_suffix}.tar.gz"
filename="$(basename "${url}")"

check-github-release-asset "MacroPower/kat" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

# Extract to temp directory first
mkdir -p /tmp/kat_extract
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin/" --no-same-owner \
    kat \
    man/kat.1

mv "${prefix}/bin/man/kat.1" "${prefix}/share/man/man1/kat.1"
rmdir "${prefix}/bin/man"
EOF
RUN <<EOF
"${prefix}/bin/kat" completion bash >"${prefix}/share/bash-completion/completions/kat"
"${prefix}/bin/kat" completion fish >"${prefix}/share/fish/vendor_completions.d/kat.fish"
"${prefix}/bin/kat" completion zsh >"${prefix}/share/zsh/vendor-completions/_kat"
EOF
