#syntax=docker/dockerfile:1.9.0@sha256:fe40cf4e92cd0c467be2cfc30657a680ae2398318afd50b0c80585784c604f28

FROM ghcr.io/uniget-org/tools/make:latest AS make

FROM ghcr.io/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --from=make / /usr/local/
ARG name
ARG version
RUN <<EOF
check-github-release-asset "libbpf/bpftool" "v${version}" "bpftool-v${version}-${alt_arch}.tar.gz"
curl --silent --show-error --location --fail "https://github.com/libbpf/bpftool/releases/download/v${version}/bpftool-v${version}-${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/bin/" --no-same-owner
chmod +x "${prefix}/bin/bpftool"
EOF
WORKDIR /tmp/bpftool
RUN <<EOF
apt-get update
apt-get -y install --no-install-recommends \
    python3-docutils
EOF
RUN <<EOF
curl --silent --show-error --location --fail "https://github.com/libbpf/bpftool/releases/download/v${version}/bpftool-libbpf-v${version}-sources.tar.gz" \
| tar --extract --gzip --strip-components=1 --no-same-owner
make -C docs man
find docs -name "*.8" -exec cp {} "${prefix}/share/man/man8/" \;
EOF
RUN <<EOF
cp bash-completion/bpftool "${prefix}/share/bash-completion/completions/bpftool"
EOF