#syntax=docker/dockerfile

FROM ghcr.io/uniget-org/tools/go:latest AS go

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=go / /usr/local/
WORKDIR /go/src/github.com/sgreben/stdin-spinner
ARG name
ARG version
ENV GOPATH=/go \
    GO111MODULE=auto
RUN --mount=type=cache,target=/root/go/pkg/mod <<EOF
git clone -q --config advice.detachedHead=false --depth 1 --branch "${version}" https://github.com/sgreben/stdin-spinner .
go build -ldflags "-X main.version=${version}" -o "${prefix}/bin/stdin-spinner" .
EOF