#syntax=docker/dockerfile:1.23.0@sha256:2780b5c3bab67f1f76c781860de469442999ed1a0d7992a5efdf2cffc0e3d769

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:99a2bccd1ad68bfc5b1d1eb356cf54b7dd94e45c5216b89c87b9e21c70e12b9f AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://awscli.amazonaws.com/awscli-exe-linux-x86_64-${version}.zip"
filename="$( basename "${url}" )"

check-download "${url}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

unzip -t "${uniget_cache_download}/${filename}"
unzip -q "${uniget_cache_download}/${filename}"

mkdir -p "${prefix}/aws-cli/v2/${version}/bin"
mv aws/dist "${prefix}/aws-cli/v2/${version}"

ln --symbolic --relative --force "${prefix}/aws-cli/v2/${version}" "${prefix}/aws-cli/v2/current"
ln --symbolic --relative --force "${prefix}/aws-cli/v2/current/dist/aws" "${prefix}/aws-cli/v2/current/bin/aws"
ln --symbolic --relative --force "${prefix}/aws-cli/v2/current/dist/aws_completer" "${prefix}/aws-cli/v2/current/bin/aws_completer"
ln --symbolic --relative --force "${prefix}/aws-cli/v2/current/bin/aws" "${prefix}/bin/aws"
ln --symbolic --relative --force "${prefix}/aws-cli/v2/current/bin/aws_completer" "${prefix}/bin/aws_completer"
EOF
COPY <<EOF /uniget_bootstrap/share/bash-completion/completions/aws.go-template
complete -C {{ .Target }}/bin/aws_completer aws
EOF