#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM ghcr.io/uniget-org/tools/python-3.12:latest AS python
FROM ghcr.io/uniget-org/tools/node-lts:latest AS node
FROM ghcr.io/uniget-org/tools/make:latest AS make

FROM registry.gitlab.com/uniget-org/images/build-essential:26.04@sha256:1ed0eccad96ae7a150a8ecb82a0034969949572532adaf9bd41505d23037df72 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=python / /usr/local/
COPY --link --from=node / /usr/local/
COPY --link --from=make / /usr/local/
WORKDIR /uniget_bootstrap/libexec/devcontainer
ARG name
ARG version
RUN <<EOF
npm install \
    --omit=dev \
    "@devcontainers/cli@${version}"
ln --symbolic --relative --force "${prefix}/libexec/devcontainer/node_modules/.bin/devcontainer" "${prefix}/bin/"
EOF