#syntax=docker/dockerfile:1.6.0

FROM ghcr.io/uniget-org/tools/python:latest AS python
FROM ghcr.io/uniget-org/tools/nodejs:latest AS nodejs
FROM ghcr.io/uniget-org/tools/npm:latest AS npm
FROM ghcr.io/uniget-org/tools/make:latest AS make

FROM nicholasdille/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
COPY --link --from=python / /
COPY --link --from=nodejs / /
COPY --link --from=npm / /
COPY --link --from=make / /
RUN <<EOF
apt-get update
apt-get -y install --no-install-recommends \
    build-essential
EOF
WORKDIR ${prefix}${target}/libexec/devcontainer
ARG name
ARG version
RUN <<EOF
npm install \
    --omit=dev \
    "@devcontainers/cli@${version}"
ln --symbolic --relative --force "${prefix}${target}/libexec/devcontainer/node_modules/.bin/devcontainer" "${prefix}${target}/bin/"
EOF