#syntax=docker/dockerfile:1.6.0

#FROM ghcr.io/uniget-org/tools/python:latest AS python
#FROM ghcr.io/uniget-org/tools/shiv:latest AS shiv

FROM nicholasdille/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
#COPY --link --from=python / /usr/local/
#COPY --link --from=shiv / /usr/local/
RUN <<EOF
apt-get update
apt-get -y install --no-install-recommends \
    python3-pip \
    python3-venv \
    python-is-python3
EOF
WORKDIR /uniget_bootstrap/libexec/semgrep
RUN <<EOF
#shiv --output-file "${prefix}/bin/semgrep" --console-script semgrep "semgrep==${version}"
python -m venv "${prefix}/libexec/semgrep"
source "${prefix}/libexec/semgrep/bin/activate"
pip install "semgrep==${version}"
deactivate
ln --symbolic --relative --force "${prefix}/libexec/semgrep/bin/semgrep" "${prefix}/bin/"
ln --symbolic --relative --force "${prefix}/libexec/semgrep/bin/pysemgrep" "${prefix}/bin/"
EOF