#syntax=docker/dockerfile:1.16.0@sha256:9857836c9ee4268391bb5b09f9f157f3c91bb15821bb77969642813b0d00518d

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/vmware-tanzu/velero/releases/download/v${version}/velero-v${version}-linux-${alt_arch}.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "vmware-tanzu/velero" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin" --strip-components=1 --no-same-owner \
    "velero-v${version}-linux-${alt_arch}/velero"
EOF
RUN <<EOF
"${prefix}/bin/velero" completion bash >"${prefix}/share/bash-completion/completions/velero"
"${prefix}/bin/velero" completion fish >"${prefix}/share/fish/vendor_completions.d/velero.fish"
"${prefix}/bin/velero" completion zsh >"${prefix}/share/zsh/vendor-completions/_velero"
EOF