#syntax=docker/dockerfile:1.15.1@sha256:05e0ad437efefcf144bfbf9d7f728c17818408e6d01432d9e264ef958bbd52f3

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/darxkies/k8s-tew/releases/download/${version}/k8s-tew"
filename="$( basename "${url}" )"

check-github-release-asset "darxkies/k8s-tew" "${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/k8s-tew"


"${prefix}/bin/k8s-tew" completion bash >"${prefix}/share/bash-completion/completions/k8s-tew"
"${prefix}/bin/k8s-tew" completion zsh >"${prefix}/share/zsh/vendor-completions/_k8s-tew"
EOF