#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM ghcr.io/uniget-org/tools/make:latest AS make
FROM ghcr.io/uniget-org/tools/zig:latest AS zig

FROM registry.gitlab.com/uniget-org/images/build-base:3.24@sha256:6c6c414a06d0c48a6a05e1b3fe6940529179f7ed617dccbbcf4f2424383b1014 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
RUN --mount=type=cache,target=/var/cache/apk <<EOF
apk add --update-cache \
    ncurses-dev \
    zstd-dev \
    minisign
EOF
COPY --from=make / /usr/local/
#COPY --from=zig / /usr/local/
WORKDIR /tmp/ncdu
ARG name
ARG version
RUN <<EOF
curl --silent --show-error --location --fail "https://dev.yorhel.nl/download/ncdu-${version}.tar.gz" \
| tar --extract --gzip --strip-components=1
EOF
WORKDIR /tmp
RUN <<EOF
ZIG_VERSION="0.15.2"
curl --silent --show-error --location --fail --remote-name "https://ziglang.org/download/${ZIG_VERSION}/zig-${arch}-linux-${ZIG_VERSION}.tar.xz"
curl --silent --show-error --location --fail --remote-name "https://ziglang.org/download/${ZIG_VERSION}/zig-${arch}-linux-${ZIG_VERSION}.tar.xz.minisig"
minisign -Vm "zig-${arch}-linux-${ZIG_VERSION}.tar.xz" -P "RWSGOq2NVecA2UPNdBUZykf1CCb147pkmdtYxgb3Ti+JO/wCYvhbAb/U"
tar --extract --xz --directory=/opt --file="zig-${arch}-linux-${ZIG_VERSION}.tar.xz"
ln --symbolic --relative --force "/opt/zig-${arch}-linux-${ZIG_VERSION}/zig" /usr/local/bin/zig
zig version
EOF
WORKDIR /tmp/ncdu
ARG name
ARG version
RUN <<EOF
make -j$(nproc)
make install PREFIX="${prefix}"
EOF