#syntax=docker/dockerfile:1.23.0@sha256:4a43a54dd1fedceb30ba47e76cfcf2b47304f4161c0caeac2db1c61804ea3c91

FROM ghcr.io/uniget-org/tools/cosign:latest AS cosign

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=cosign / /usr/local/
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/ckotzbauer/sbom-operator/releases/download/${version}/sbom-operator_${version}_linux_${alt_arch}.tar.gz"
filename="$(basename "${url}")"

echo "### Downloading sbom-operator ${version} for ${alt_arch}"
check-github-release-asset "ckotzbauer/sbom-operator" "${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"
echo "    SHA256 checksum: $(sha256sum ${uniget_cache_download}/${filename} | cut -d' ' -f1)"

echo "### Downloading signature and certificate"
check-github-release-asset "ckotzbauer/sbom-operator" "${version}" "${filename}.sigstore.json"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}.sigstore.json" \
    "${url}.sigstore.json"

echo "### Verifying signature"
COSIGN_EXPERIMENTAL=1 cosign verify-blob "${uniget_cache_download}/${filename}" \
    --bundle "${uniget_cache_download}/${filename}.sigstore.json" \
    --certificate-oidc-issuer https://token.actions.githubusercontent.com \
    --certificate-identity-regexp 'https://github.com/ckotzbauer/actions-toolkit/.github/workflows/toolkit-release-goreleaser.yml@.+' \
    --certificate-github-workflow-repository ckotzbauer/sbom-operator \
    --certificate-github-workflow-name create-release \
    --certificate-github-workflow-ref refs/heads/main \
    --certificate-github-workflow-trigger workflow_dispatch

echo "### Installing sbom-operator ${version}"
tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin/" --no-same-owner \
    sbom-operator
EOF