#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM ghcr.io/uniget-org/tools/go:latest AS go
FROM ghcr.io/uniget-org/tools/make:latest AS make

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=go / /usr/local/
COPY --link --from=make / /usr/local/
WORKDIR /go/src/github.com/chainguard-dev/apko
ARG name
ARG version
RUN <<EOF
check-clone "https://github.com/chainguard-dev/apko" "v${version}"

git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/chainguard-dev/apko .
make -j$(nproc) apko
cp apko "${prefix}/bin/"

"${prefix}/bin/apko" completion bash >"${prefix}/share/bash-completion/completions/apko"
"${prefix}/bin/apko" completion fish >"${prefix}/share/fish/vendor_completions.d/apko.fish"
"${prefix}/bin/apko" completion zsh >"${prefix}/share/zsh/vendor-completions/_apko"
EOF