#syntax=docker/dockerfile:1.14.0@sha256:4c68376a702446fc3c79af22de146a148bc3367e73c25a5803d453b6b3f722fb

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
COPY --chmod=0755 install-docker-debug.sh "/uniget_bootstrap/bin/"
RUN <<EOF
BODY="$(
    curl --silent --show-error --location --fail \
        "https://api.github.com/repos/uniget-org/renovate-custom/releases/tags/docker-debug%2F${version}" \
    | jq --raw-output '.body'
)"
if test -z "${BODY}"; then
    echo "No release found for docker-debug/${version}" >&2
    exit 1
fi
DD_VERSION="$(
    echo "${BODY}" \
    | cut -d@ -f2
)"
sed -i "s/docker_desktop_version:=DD_VERSION/docker_desktop_version:=${DD_VERSION}/" "/uniget_bootstrap/bin/install-docker-debug.sh"
EOF