#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
for binary in lore loreserver; do
    url="https://github.com/EpicGames/lore/releases/download/v${version}/${binary}-v${version}-${arch}-unknown-linux-gnu.tar.gz"
    filename="$(basename "${url}")"

    check-github-release-asset "EpicGames/lore" "v${version}" "${filename}"
    curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
        "${url}"

    tar --extract --gzip --directory="${prefix}/bin" --strip-components=1 \
        --file="${uniget_cache_download}/${filename}" \
        "./${binary}"
    chmod +x "${prefix}/bin/${binary}"
done
EOF
RUN <<EOF
"${prefix}/bin/lore" completions bash >"${prefix}/share/bash-completion/completions/lore"
"${prefix}/bin/lore" completions fish >"${prefix}/share/fish/vendor_completions.d/lore.fish"
"${prefix}/bin/lore" completions zsh >"${prefix}/share/zsh/vendor-completions/_lore"
EOF