#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM ghcr.io/uniget-org/tools/make:latest AS make

FROM registry.gitlab.com/uniget-org/images/build-essential:26.04@sha256:5ee01cd64296e795943405f10d803592dbd27cad7d35cd6ee1271bf177a71146 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
RUN --mount=type=cache,target=/var/cache/apt <<EOF
apt-get update
apt-get -y install --no-install-recommends \
    zlib1g-dev
EOF
COPY --link --from=make / /usr/local/
WORKDIR /tmp/figlet
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/cmatsuoka/figlet/archive/refs/tags/${version}.tar.gz"
filename="$( basename "${url}" )"

check-download "${url}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --strip-components=1

make -j$(nproc) figlet LDFLAGS=-static DEFAULTFONTDIR=/share/figlet
make install prefix="${prefix}" MANDIR="${prefix}/share/man"
EOF