#syntax=docker/dockerfile:1.17.0@sha256:e63addfe27b10e394a5f9f1e866961adc70d08573f1cb80f8d1a0999347b3553

FROM ghcr.io/uniget-org/tools/go:latest AS go
FROM ghcr.io/uniget-org/tools/make:latest AS make

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=go / /usr/local/
COPY --link --from=make / /usr/local/
WORKDIR /go/src/github.com/portainer/k2d
ARG name
ARG version
RUN --mount=type=cache,target=/root/go/pkg/mod <<EOF
git clone -q --config advice.detachedHead=false --depth 1 --branch "${version}" https://github.com/portainer/k2d .
make -j$(nproc) release
cp dist/k2d "${prefix}/bin/"
EOF