#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM ghcr.io/uniget-org/tools/make:latest AS make
FROM ghcr.io/uniget-org/tools/go:latest AS go
FROM ghcr.io/uniget-org/tools/golangci-lint:latest AS golangci-lint

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:059b11407572b2fd733e7bcd1c528852394d7fe1abef7119a1a97356983cab76 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=go / /usr/local/
COPY --link --from=make / /usr/local/
COPY --link --from=golangci-lint / /usr/local/
WORKDIR /go/src/github.com/jbovet/mcp-cli
ARG name
ARG version
RUN --mount=type=cache,target=/root/go/pkg/mod <<EOF
git clone https://github.com/jbovet/mcp-cli .
git checkout "${version}"
make deps
make vet
make lint
make test
make build
mv bin/mcp-cli "${prefix}/bin/"
EOF
RUN <<EOF
"${prefix}/bin/mcp-cli" completion bash >"${prefix}/share/bash-completion/completions/mcp-cli"
"${prefix}/bin/mcp-cli" completion fish >"${prefix}/share/fish/vendor_completions.d/mcp-cli.fish"
"${prefix}/bin/mcp-cli" completion zsh >"${prefix}/share/zsh/vendor-completions/_mcp-cli"
EOF