#syntax=docker/dockerfile:1.10.0@sha256:865e5dd094beca432e8c0a1d5e1c465db5f998dca4e439981029b3b81fb39ed5

FROM ghcr.io/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "mvdan/xurls" "v${version}" "xurls_v${version}_linux_${alt_arch}"
curl --silent --show-error --location --fail --output "${prefix}/bin/xurls" \
    "https://github.com/mvdan/xurls/releases/download/v${version}/xurls_v${version}_linux_${alt_arch}"
chmod +x "${prefix}/bin/xurls"
EOF