#syntax=docker/dockerfile

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
for binary in taritd vmm vmm-agent; do
    url="https://github.com/instavm/tarit/releases/download/v${version}/${binary}"
    filename="${binary}"

    check-github-release-asset "instavm/tarit" "v${version}" "${filename}"
    curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
        "${url}"

    install --mode=0755 \
        "${uniget_cache_download}/${filename}" \
        "${prefix}/bin/${binary}"
done
EOF
