#syntax=docker/dockerfile:1.25.0@sha256:0adf442eae370b6087e08edc7c50b552d80ddf261576f4ebd6421006b2461f12

ARG version=latest
FROM allinurl/goaccess:${version} AS goaccess

FROM registry.gitlab.com/uniget-org/images/alpine:3.23@sha256:36c378075502da03a50858d763e9c579aee8eede8ca513c4fc03e00953c9ccff AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
WORKDIR /uniget_bootstrap
COPY --from=goaccess /usr/bin/goaccess bin/
COPY --from=goaccess /usr/share/man/man1/goaccess.1 share/man/man1/
COPY --from=goaccess /usr/share/locale/ share/locale/