#syntax=docker/dockerfile:1.25.0@sha256:0adf442eae370b6087e08edc7c50b552d80ddf261576f4ebd6421006b2461f12

ARG version=latest
FROM allinurl/goaccess:${version} AS goaccess

FROM registry.gitlab.com/uniget-org/images/alpine:3.23@sha256:23951cd7fdf0bbc6e0f5c629c9fc3b003dc0ee36683e7773644cfd9b111ecae6 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
WORKDIR /uniget_bootstrap
COPY --from=goaccess /usr/bin/goaccess bin/
COPY --from=goaccess /usr/share/man/man1/goaccess.1 share/man/man1/
COPY --from=goaccess /usr/share/locale/ share/locale/