#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:b0b654de801604e256237f2c27a907a4b61b59ebd83423ad0e0e465c0a3ba9cd AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
echo "### Setting architecture string for ${TARGETPLATFORM}"
case "${arch}" in
    x86_64)
        export arch_suffix=x64
        ;;
    aarch64)
        export arch_suffix=arm64
        ;;
    *)
        echo "ERROR: Unsupported architecture ${arch}."
        exit 1
        ;;
esac
echo "    Using ${arch_suffix}"

url="https://github.com/pulumi/pulumi/releases/download/v${version}/pulumi-v${version}-linux-${arch_suffix}.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "pulumi/pulumi" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin/" --strip-components=1 --no-same-owner

"${prefix}/bin/pulumi" completion bash >"${prefix}/share/bash-completion/completions/pulumi"
"${prefix}/bin/pulumi" completion fish >"${prefix}/share/fish/vendor_completions.d/pulumi.fish"
"${prefix}/bin/pulumi" completion zsh >"${prefix}/share/zsh/vendor-completions/_pulumi"
EOF