#syntax=docker/dockerfile

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]

ARG name
ARG version

RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/MykytaStel/repopilot/releases/download/v${version}/repopilot-v${version}-${arch}-unknown-linux-gnu.tar.gz"
filename="$( basename "${url}" )"

check-download "${url}"
check-github-release-asset "MykytaStel/repopilot" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin" --no-same-owner \
    repopilot
EOF