#syntax=docker/dockerfile:1.17.0@sha256:e63addfe27b10e394a5f9f1e866961adc70d08573f1cb80f8d1a0999347b3553

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
COPY docker.cow /uniget_bootstrap/share/cows/
COPY --chmod=0755 <<EOF /uniget_bootstrap/bin/whalesay
#!/bin/bash
exec cowsay -f docker "\$@"
EOF