#syntax=docker/dockerfile:1.16.0@sha256:9857836c9ee4268391bb5b09f9f157f3c91bb15821bb77969642813b0d00518d

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
COPY docker.cow /uniget_bootstrap/share/cows/
COPY --chmod=0755 <<EOF /uniget_bootstrap/bin/whalesay
#!/bin/bash
exec cowsay -f docker "\$@"
EOF