#syntax=docker/dockerfile:1.8.1

FROM ghcr.io/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
COPY docker.cow /uniget_bootstrap/share/cows/
COPY --chmod=0755 <<EOF /uniget_bootstrap/bin/whalesay
#!/bin/bash
exec cowsay -f docker "\$@"
EOF