#syntax=docker/dockerfile:1.6.0

FROM ghcr.io/uniget-org/images/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]

ARG name
ARG version

RUN <<EOF
check-github-release-asset "docker/machine" "v${version}" "docker-machine-Linux-${arch}"
curl --silent --location --fail --output "${prefix}/bin/docker-machine" \
    "https://github.com/docker/machine/releases/download/v${version}/docker-machine-Linux-${arch}"
chmod +x "${prefix}/bin/docker-machine"
EOF