#syntax=docker/dockerfile:1.7.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:98429d8ee1c7cf7d06f65b692870d983f0965f1c1cdffa1dd04ef878b56293b6 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
url="https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${version}-linux.zip"
filename="$(basename "${url}")"
curl --silent --location --fail --remote-name "${url}"
unzip -q -o -d "${prefix}/opt" "${filename}"
mv "${prefix}/opt/sonar-scanner-${version}-linux" "${prefix}/opt/sonar-scanner"
sed -i 's/use_embedded_jre=true/use_embedded_jre=false/' "${prefix}/opt/sonar-scanner/bin/sonar-scanner"
rm -rf "${prefix}/opt/sonar-scanner/jre"
ln --symbolic --relative --force "${prefix}/opt/sonar-scanner/bin/sonar-scanner" "${prefix}/bin/sonar-scanner"
EOF