#syntax=docker/dockerfile:1.7.1

FROM ghcr.io/uniget-org/images/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
curl --silent --show-error --location --fail --output "${prefix}/bin/tea" \
    "https://gitea.com/gitea/tea/releases/download/v${version}/tea-${version}-linux-${alt_arch}"
chmod +x "${prefix}/bin/tea"

curl --silent --show-error --location --fail --output "${prefix}/share/bash-completion/completions/tea" \
    "https://gitea.com/gitea/tea/raw/tag/v${version}/contrib/autocomplete.sh"
curl --silent --show-error --location --fail --output "${prefix}/share/zsh/vendor-completions/_tea" \
    "https://gitea.com/gitea/tea/raw/tag/v${version}/contrib/autocomplete.zsh"
EOF