#syntax=docker/dockerfile:1.10.0@sha256:865e5dd094beca432e8c0a1d5e1c465db5f998dca4e439981029b3b81fb39ed5

FROM ghcr.io/uniget-org/tools/make:latest AS make

FROM ghcr.io/uniget-org/images/build-base:3.20 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=make / /usr/local/
WORKDIR /tmp/lz4
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/lz4/lz4/releases/download/v${version}/lz4-${version}.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "lz4/lz4" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --strip-components=1

make -C lib -j$(nproc)
make -C programs -j$(nproc) LDFLAGS=-static
make install DESTDIR="${prefix}" prefix=""
EOF