#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:b0b654de801604e256237f2c27a907a4b61b59ebd83423ad0e0e465c0a3ba9cd AS ubuntu2604

FROM ubuntu2604 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
echo "### Setting architecture string for ${TARGETPLATFORM}"
case "${arch}" in
    x86_64)
        export arch_suffix="x64"
        ;;
    aarch64)
        export arch_suffix="${alt_arch}"
        ;;
    *)
        echo "ERROR: Unsupported architecture ${arch}."
        exit 1
        ;;
esac
echo "    Using ${arch_suffix}"

gitlab_host="gitlab.com"
gitlab_api_base_url="https://${gitlab_host}/api/v4"
project_path="gitlab-org/editor-extensions/gitlab-lsp"
project_id="46519181"
package_name="duo-cli"
package_id_for_version="$(
    curl --silent --show-error --fail "${gitlab_api_base_url}/projects/${project_id}/packages?package_name=${package_name}&package_type=generic&package_version=${version}" \
    | jq -r '.[].id'
)"
download_id="$(
    curl --silent --show-error --fail "${gitlab_api_base_url}/projects/${project_id}/packages/${package_id_for_version}/package_files" \
    | jq -r ".[] | select(.file_name == \"duo-linux-${arch_suffix}\") | .id"
)"

url="https://${gitlab_host}/${project_path}/-/package_files/${download_id}/download"
filename="duo"

check-download "${url}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/duo"
EOF