#syntax=docker/dockerfile

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/gefyrahq/gefyra/releases/download/${version}/gefyra-${version}-linux-${alt_arch}.zip"
filename="$(basename "${url}")"

check-github-release-asset "gefyrahq/gefyra" "${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

unzip -q -o -d "${prefix}/bin" "${uniget_cache_download}/${filename}" \
    gefyra
EOF