#syntax=docker/dockerfile:1.25.0@sha256:0adf442eae370b6087e08edc7c50b552d80ddf261576f4ebd6421006b2461f12

FROM ghcr.io/uniget-org/tools/make:latest AS make
FROM ghcr.io/uniget-org/tools/libmnl:latest AS libmnl
FROM ghcr.io/uniget-org/tools/libnftnl:latest AS libnftnl
FROM ghcr.io/uniget-org/tools/libnfnetlink:latest AS libnfnetlink

FROM registry.gitlab.com/uniget-org/images/build-essential:26.04@sha256:e01323d1547d9efab438820253dd234aa6b45d03b2e067dcc710cb5caa7a37a9 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=make / /usr/local/
COPY --link --from=libmnl / /usr/local/
COPY --link --from=libnftnl / /usr/local/
COPY --link --from=libnfnetlink / /usr/local/
WORKDIR /tmp/iptables
ARG name
ARG version
RUN <<EOF
check-clone "https://git.netfilter.org/iptables/" "v${version}"
git clone --config advice.detachedHead=false --depth 1 --branch "v${version}" git://git.netfilter.org/iptables .
./autogen.sh
./configure \
    --prefix="${prefix}" \
    --enable-shared \
    --enable-static
make -j$(nproc)
make install
ln --symbolic --relative --force "${prefix}/sbin/iptables-legacy-multi" "${prefix}/bin/iptables-xml"
EOF