#syntax=docker/dockerfile:1.19.0@sha256:b6afd42430b15f2d2a4c5a02b919e98a525b785b1aaff16747d2f623364e39b6

FROM ghcr.io/uniget-org/tools/make:latest AS make
FROM ghcr.io/uniget-org/tools/libmnl:latest AS libmnl
FROM ghcr.io/uniget-org/tools/libnftnl:latest AS libnftnl
FROM ghcr.io/uniget-org/tools/libnfnetlink:latest AS libnfnetlink

FROM registry.gitlab.com/uniget-org/images/build-essential:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=make / /usr/local/
COPY --link --from=libmnl / /usr/local/
COPY --link --from=libnftnl / /usr/local/
COPY --link --from=libnfnetlink / /usr/local/
WORKDIR /tmp/iptables
ARG name
ARG version
RUN <<EOF
check-clone "https://git.netfilter.org/iptables/" "v${version}"
git clone --config advice.detachedHead=false --depth 1 --branch "v${version}" git://git.netfilter.org/iptables .
./autogen.sh
./configure \
    --prefix="${prefix}" \
    --enable-shared \
    --enable-static
make -j$(nproc)
make install
ln --symbolic --relative --force "${prefix}/sbin/iptables-legacy-multi" "${prefix}/bin/iptables-xml"
EOF