#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:059b11407572b2fd733e7bcd1c528852394d7fe1abef7119a1a97356983cab76 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/download/v${version}/clusterawsadm-linux-${alt_arch}"
filename="$( basename "${url}" )"

check-github-release-asset "kubernetes-sigs/cluster-api-provider-aws" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/clusterawsadm"


check-github-release-asset "kubernetes-sigs/cluster-api-provider-aws" "v${version}" "clusterctl-aws-linux-${alt_arch}"
curl --silent --show-error --location --fail --output "${prefix}/bin/clusterctl-aws" \
    "https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/download/v${version}/clusterctl-aws-linux-${alt_arch}"
chmod +x "${prefix}/bin/clusterctl-aws"

"${prefix}/bin/clusterawsadm" completion bash >"${prefix}/share/bash-completion/completions/clusterawsadm"
"${prefix}/bin/clusterawsadm" completion fish >"${prefix}/share/fish/vendor_completions.d/clusterawsadm.fish"
"${prefix}/bin/clusterawsadm" completion zsh >"${prefix}/share/zsh/vendor-completions/_clusterawsadm"

"${prefix}/bin/clusterctl-aws" completion bash >"${prefix}/share/bash-completion/completions/clusterctl-aws"
"${prefix}/bin/clusterctl-aws" completion fish >"${prefix}/share/fish/vendor_completions.d/clusterctl-aws.fish"
"${prefix}/bin/clusterctl-aws" completion zsh >"${prefix}/share/zsh/vendor-completions/_clusterctl-aws"
EOF