#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
ARG commit_sha=0cbc58b
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/openshift/origin/releases/download/v${version}/openshift-origin-client-tools-v${version}-${commit_sha}-linux-64bit.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "openshift/origin" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin" --strip-components=1 --wildcards \
    */oc

"${prefix}/bin/oc" completion bash >"${prefix}/share/bash-completion/completions/oc"
"${prefix}/bin/oc" completion zsh >"${prefix}/share/zsh/vendor-completions/_oc"
EOF