#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:059b11407572b2fd733e7bcd1c528852394d7fe1abef7119a1a97356983cab76 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/BurntSushi/ripgrep/releases/download/${version}/ripgrep-${version}-${arch}-unknown-linux-musl.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "BurntSushi/ripgrep" "${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin/" --strip-components=1 --no-same-owner \
    "ripgrep-${version}-x86_64-unknown-linux-musl/rg" \
    "ripgrep-${version}-x86_64-unknown-linux-musl/doc/rg.1" \
    "ripgrep-${version}-x86_64-unknown-linux-musl/complete"
mv "${prefix}/bin/doc/rg.1" "${prefix}/share/man/man1/"
mv "${prefix}/bin/complete/rg.bash" "${prefix}/share/bash-completion/completions/ripgrep"
mv "${prefix}/bin/complete/rg.fish" "${prefix}/share/fish/vendor_completions.d/ripgrep.fish"
mv "${prefix}/bin/complete/_rg" "${prefix}/share/zsh/vendor-completions/_ripgrep"
rm -rf \
    "${prefix}/bin/doc" \
    "${prefix}/bin/complete"
EOF