#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/linkerd/linkerd2/releases/download/edge-${version}/linkerd2-cli-edge-${version}-linux-${alt_arch}"
filename="$( basename "${url}" )"

check-github-release-asset "linkerd/linkerd2" "edge-${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/linkerd"
EOF
RUN <<EOF
"${prefix}/bin/linkerd" completion bash >"${prefix}/share/bash-completion/completions/linkerd"
"${prefix}/bin/linkerd" completion fish >"${prefix}/share/fish/vendor_completions.d/linkerd.fish"
"${prefix}/bin/linkerd" completion zsh >"${prefix}/share/zsh/vendor-completions/_linkerd"
EOF