#syntax=docker/dockerfile:1.6.0

FROM ghcr.io/uniget-org/images/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]

ARG name
ARG version

RUN <<EOF
check-github-release-asset "open-policy-agent/conftest" "v${version}" "conftest_${version}_Linux_${arch}.tar.gz"
curl --silent --location --fail "https://github.com/open-policy-agent/conftest/releases/download/v${version}/conftest_${version}_Linux_${arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/bin" --no-same-owner \
    conftest
"${prefix}/bin/conftest" completion bash >"${prefix}/share/bash-completion/completions/conftest"
"${prefix}/bin/conftest" completion fish >"${prefix}/share/fish/vendor_completions.d/conftest.fish"
"${prefix}/bin/conftest" completion zsh >"${prefix}/share/zsh/vendor-completions/_conftest"
EOF