spec:
  inputs:
    name:
      description: Name of the tools to build
      type: string
    os:
      description: Operating systems to build
      type: array
      default:
      - linux
    arch:
      description: Architectures to build
      type: array
      default:
      - amd64

---

.docker_login:
  before_script: |
    echo "${CI_REGISTRY_PASSWORD}" \
    | docker login "${CI_REGISTRY}" \
        --username="${CI_REGISTRY_USER}" \
        --password-stdin

.docker_logout:
  after_script: |
    docker logout "${CI_REGISTRY}"

.dind:
  variables:
    DOCKER_CERT_DIR: ""
  services:
  - name: docker:29.4.3-dind@sha256:685b91dca8eab7de1dce1c303dbb7a763e4082d6a60db10968adf3295fbd2495

build_single:
  parallel:
    matrix:
    - os: $[[ inputs.os ]]
      arch: $[[ inputs.arch ]]
  extends:
  - .docker_login
  - .dind
  - .docker_logout
  image: docker:29.4.3@sha256:685b91dca8eab7de1dce1c303dbb7a763e4082d6a60db10968adf3295fbd2495
  script:
  - |
    apk update
    apk add \
        bash \
        make \
        curl
  - |
    curl -sLf https://gitlab.com/uniget-org/cli/-/releases/permalink/latest/downloads/uniget_Linux_$(uname -m).tar.gz \
    | tar -xzC "/usr/local/bin" uniget
  - |
    uniget install \
        jq \
        yq
  - |
    make $[[ inputs.name ]]--build-${arch} \
        REGISTRY=${CI_REGISTRY} \
        REPOSITORY_PREFIX=${CI_PROJECT_PATH}/
  artifacts:
    paths:
    - tools/*/build-*.log
    - tools/*/image-*.json
    expire_in: 4 days
  tags:
  - saas-${os}-medium-${arch}

create_index_regctl:
  extends:
  - .docker_login
  - .docker_logout
  needs:
  - job: build_single
    parallel:
      matrix:
      - os: $[[ inputs.os ]]
        arch: $[[ inputs.arch ]]
  image: docker:29.4.3@sha256:685b91dca8eab7de1dce1c303dbb7a763e4082d6a60db10968adf3295fbd2495
  script:
  - |
    apk add --update-cache \
        bash \
        make \
        curl
  - |
    curl -sLf https://gitlab.com/uniget-org/cli/-/releases/permalink/latest/downloads/uniget_Linux_$(uname -m).tar.gz \
    | tar -xzC "/usr/local/bin" uniget
  - |
    uniget install \
        jq \
        yq \
        regclient
  - |
    echo "### Creating index ${CI_REGISTRY_IMAGE}/$[[ inputs.name ]]"
    make $[[ inputs.name ]]--index \
        REGISTRY=${CI_REGISTRY} \
        REPOSITORY_PREFIX=${CI_PROJECT_PATH}/
    INDEX_DIGEST="$( cat tools/$[[ inputs.name ]]/index.json | sha256sum | cut -d' ' -f1 )"
    echo "Got index digest: ${INDEX_DIGEST}"
    echo "INDEX_DIGEST=${INDEX_DIGEST}" >index.env
  artifacts:
    paths:
    - tools/*/index.json
    expire_in: 4 days
    reports:
      dotenv: index.env
  
.sign:
  extends:
  - .docker_login
  - .docker_logout
  needs:
  - create_index_regctl
  image: docker:29.4.3@sha256:685b91dca8eab7de1dce1c303dbb7a763e4082d6a60db10968adf3295fbd2495
  id_tokens:
    SIGSTORE_ID_TOKEN:
      aud: sigstore
  variables:
    COSIGN_EXPERIMENTAL: 1
  script:
  - |
    apk add --update-cache \
        bash \
        curl \
        make
  - |
    curl -sLf https://gitlab.com/uniget-org/cli/-/releases/permalink/latest/downloads/uniget_Linux_$(uname -m).tar.gz \
    | tar -xzC "/usr/local/bin" uniget
  - |
    uniget install \
        jq \
        yq \
        regclient \
        cosign
  - |
    echo "Got index digest: ${INDEX_DIGEST}"
  - |
    echo "### Sign ${IMAGE}"
    make $[[ inputs.name ]]--sign \
        REGISTRY=${CI_REGISTRY} \
        REPOSITORY_PREFIX=${CI_PROJECT_PATH}/
  artifacts:
    paths:
    - tools/*/cosign*
    expire_in: 4 days
  tags:
  - saas-linux-medium-amd64
