#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM ghcr.io/uniget-org/tools/node-lts:latest AS node

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=node / /usr/local/
WORKDIR /uniget_bootstrap/libexec/keyoxide
ARG name
ARG version
RUN <<EOF
npm install \
    --omit=dev \
    "keyoxide@${version}"
ln --symbolic --relative --force "${prefix}/libexec/keyoxide/node_modules/.bin/keyoxide" "${prefix}/bin/"
EOF