#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
case "${alt_arch}" in
    amd64)
        export arch_suffix="${alt_arch}"
        ;;
    arm64)
        export arch_suffix="${arch}"
        ;;
    *)
        echo "ERROR: Unknown architecture (${alt_arch})."
        exit 1
        ;;
esac

url="https://github.com/deislabs/wagi/releases/download/v${version}/wagi-v${version}-linux-${arch_suffix}.tar.gz"
filename="$(basename "${url}")"

check-github-release-asset "deislabs/wagi" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin/" --no-same-owner \
    wagi
EOF