#syntax=docker/dockerfile:1.7.0

FROM ghcr.io/uniget-org/images/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "crra/mp3binder" "v${version}" "linux_${alt_arch}.zip"
curl --silent --location --fail --remote-name "https://github.com/crra/mp3binder/releases/download/v${version}/linux_${alt_arch}.zip"
unzip -q -o -d "/tmp" "linux_${alt_arch}.zip"
rm "linux_${alt_arch}.zip"
mv "/tmp/mp3binder" "${prefix}/bin"
EOF