#syntax=docker/dockerfile:1.6.0

FROM ghcr.io/uniget-org/images/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
RUN <<EOF
apt-get update
apt-get -y install --no-install-recommends \
    make
EOF
WORKDIR /tmp/pass-otp
ARG name
ARG version
RUN <<EOF
check-github-release-asset "tadfisher/pass-otp" "v${version}" "pass-otp-${version}.tar.gz"
curl --silent --location --fail "https://github.com/tadfisher/pass-otp/releases/download/v${version}/pass-otp-${version}.tar.gz" \
| tar --extract --gzip --strip-components=1 --no-same-owner
make install \
    DESTDIR="${prefix}" \
    PREFIX="" \
    BASHCOMPDIR="/share/bash-completion/completions"
EOF