#syntax=docker/dockerfile:1.25.0@sha256:0adf442eae370b6087e08edc7c50b552d80ddf261576f4ebd6421006b2461f12

FROM ghcr.io/uniget-org/tools/make:latest AS make
FROM ghcr.io/uniget-org/tools/go:latest AS go

FROM registry.gitlab.com/uniget-org/images/build-essential:26.04@sha256:e01323d1547d9efab438820253dd234aa6b45d03b2e067dcc710cb5caa7a37a9 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=go / /usr/local/
COPY --link --from=make / /usr/local/
WORKDIR /go/src/github.com/runfinch/finch-daemon
ARG name
ARG version
RUN --mount=type=cache,target=/root/go/pkg/mod <<EOF
check-clone "https://github.com/runfinch/finch-daemon" "v${version}"
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/runfinch/finch-daemon .
make build STATIC=1
cp bin/finch-daemon "${prefix}/bin/"
EOF
COPY nerdctl.toml.go-template /uniget_bootstrap/var/lib/finch/nerdctl/
COPY buildkitd.toml /uniget_bootstrap/etc/finch/buildkit/
COPY finch-buildkitd.service.go-template /uniget_bootstrap/etc/systemd/system/
COPY finch-buildkitd.socket /uniget_bootstrap/etc/systemd/system/
COPY finch.yaml /uniget_bootstrap/etc/finch/
COPY finch.service.go-template /uniget_bootstrap/etc/systemd/system/
COPY finch.socket /uniget_bootstrap/etc/systemd/system/