#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM ghcr.io/uniget-org/tools/make:latest AS make
FROM ghcr.io/uniget-org/tools/go:latest AS go

FROM registry.gitlab.com/uniget-org/images/build-essential:26.04@sha256:5ee01cd64296e795943405f10d803592dbd27cad7d35cd6ee1271bf177a71146 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=go / /usr/local/
COPY --link --from=make / /usr/local/
WORKDIR /go/src/github.com/runfinch/finch-daemon
ARG name
ARG version
RUN --mount=type=cache,target=/root/go/pkg/mod <<EOF
check-clone "https://github.com/runfinch/finch-daemon" "v${version}"
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/runfinch/finch-daemon .
make build STATIC=1
cp bin/finch-daemon "${prefix}/bin/"
EOF
COPY nerdctl.toml.go-template /uniget_bootstrap/var/lib/finch/nerdctl/
COPY buildkitd.toml /uniget_bootstrap/etc/finch/buildkit/
COPY finch-buildkitd.service.go-template /uniget_bootstrap/etc/systemd/system/
COPY finch-buildkitd.socket /uniget_bootstrap/etc/systemd/system/
COPY finch.yaml /uniget_bootstrap/etc/finch/
COPY finch.service.go-template /uniget_bootstrap/etc/systemd/system/
COPY finch.socket /uniget_bootstrap/etc/systemd/system/