#syntax=docker/dockerfile:1.25.0@sha256:0adf442eae370b6087e08edc7c50b552d80ddf261576f4ebd6421006b2461f12

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:059b11407572b2fd733e7bcd1c528852394d7fe1abef7119a1a97356983cab76 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
WORKDIR /tmp/sysbox
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://downloads.nestybox.com/sysbox/releases/v${version}/sysbox-ce_${version}-0.linux_${alt_arch}.deb"
filename="$(basename "${url}")"

check-download "${url}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"
ar x "${uniget_cache_download}/${filename}"
tar --file=data.tar.xz --extract --xz

for type in fs runc mgr; do
    mv "usr/bin/sysbox-${type}" "${prefix}/bin/"
    test -f "lib/systemd/system/sysbox-${type}.service" \
    && mv "lib/systemd/system/sysbox-${type}.service" "${prefix}/etc/systemd/system/"
done
mv "lib/systemd/system/sysbox.service" "${prefix}/etc/systemd/system/"

mkdir -p "${prefix}/etc/sysctl.d"
mv "lib/sysctl.d/99-sysbox-sysctl.conf" "${prefix}/etc/sysctl.d/"
EOF