#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM registry.gitlab.com/uniget-org/images/ubuntu:rolling AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
curl --silent --show-error --location --fail --remote-name "https://dot.net/v1/dotnet-install.sh"
bash dotnet-install.sh \
    --channel STS \
    --runtime dotnet \
    --version "${version}" \
    --install-dir "${prefix}/share/dotnet"
ln --symbolic --relative --force "${prefix}/share/dotnet/dotnet" "${prefix}/bin/dotnet"
EOF
COPY <<EOF /uniget_bootstrap/etc/dotnet/install_location.go-template
{{ .Target }}/share/dotnet
EOF