#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/int128/kubelogin/releases/download/v${version}/kubelogin_linux_${alt_arch}.zip"
filename="$(basename "${url}")"

check-github-release-asset "int128/kubelogin" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

unzip -t "${uniget_cache_download}/${filename}"
unzip -q -o -d "${prefix}/bin" "${uniget_cache_download}/${filename}" \
    kubelogin
mv "${prefix}/bin/kubelogin" "${prefix}/bin/kubectl-oidc_login"

export PATH="${prefix}/bin:${PATH}"
"${prefix}/bin/kubectl-oidc_login" completion bash >"${prefix}/share/bash-completion/completions/kubectl-oidc-login"
"${prefix}/bin/kubectl-oidc_login" completion fish >"${prefix}/share/fish/vendor_completions.d/kubectl-oidc-login.fish"
"${prefix}/bin/kubectl-oidc_login" completion zsh >"${prefix}/share/zsh/vendor-completions/_kubectl-oidc-login"
EOF