#syntax=docker/dockerfile:1.14.0@sha256:4c68376a702446fc3c79af22de146a148bc3367e73c25a5803d453b6b3f722fb

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/iximiuz/cdebug/releases/download/v${version}/cdebug_linux_${alt_arch}.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "iximiuz/cdebug" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin/" --no-same-owner \
    cdebug

"${prefix}/bin/cdebug" completion bash >"${prefix}/share/bash-completion/completions/cdebug"
"${prefix}/bin/cdebug" completion fish >"${prefix}/share/fish/vendor_completions.d/cdebug.fish"
"${prefix}/bin/cdebug" completion zsh >"${prefix}/share/zsh/vendor-completions/_cdebug"
EOF
