#syntax=docker/dockerfile:1.8.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:178a01206383923b589ecfe3bace55431c4b8528086909ffcdc1ef88de4da10f AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
COPY --chmod=0755 install-docker-desktop.sh "/uniget_bootstrap/bin/"
RUN <<EOF
sed -i "s/version:=VERSION/version:=${version}/" "/uniget_bootstrap/bin/install-docker-desktop.sh"
EOF