#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM registry.gitlab.com/uniget-org/images/build-base:3.24@sha256:6c6c414a06d0c48a6a05e1b3fe6940529179f7ed617dccbbcf4f2424383b1014 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
WORKDIR /tmp/libsodium
RUN --mount=type=cache,target=/var/cache/apt <<EOF
curl --silent --show-error --location --fail https://download.libsodium.org/libsodium/releases/LATEST.tar.gz \
| tar --extract --gzip --strip-components=1
env CPPFLAGS="-DED25519_NONDETERMINISTIC=1" \
    ./configure \
        --disable-dependency-tracking
make -j"$(nproc)" check
make install
EOF
RUN <<EOF
apk add --no-cache \
    cmake \
    pkgconfig \
    catatonit
EOF
WORKDIR /tmp/minisign
RUN <<EOF
check-clone "https://github.com/jedisct1/minisign" "${version}"
git clone -q --config advice.detachedHead=false --depth 1 --branch "master" https://github.com/jedisct1/minisign .
mkdir build
cd build
cmake \
    -DCMAKE_BUILD_TYPE=MinSizeRel \
    -DCMAKE_C_FLAGS="-fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIE" \
    -DCMAKE_EXE_LINKER_FLAGS="-pie -Wl,-z,relro,-z,now" \
    -DBUILD_STATIC_EXECUTABLES=1 \
    ..
make -j$(nproc)
cp minisign "${prefix}/bin/"
EOF
RUN <<EOF
curl --silent --show-error --location --fail --output "${prefix}/share/man/man1/minisign.1" \
    "https://github.com/jedisct1/minisign/raw/refs/heads/master/share/man/man1/minisign.1"
EOF