#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM ghcr.io/uniget-org/tools/make:latest AS make
FROM ghcr.io/uniget-org/tools/rust:latest AS rust

FROM registry.gitlab.com/uniget-org/images/build-essential:26.04@sha256:1ed0eccad96ae7a150a8ecb82a0034969949572532adaf9bd41505d23037df72 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
RUN --mount=type=cache,target=/var/cache/apt <<EOF
apt-get -y update
apt-get -y install --no-install-recommends \
    pkg-config \
    libsystemd-dev \
    libdbus-glib-1-dev \
    libelf-dev \
    libseccomp-dev \
    libclang-dev \
    libzstd-dev \
    protobuf-compiler \
    sudo
EOF
COPY --link --from=rust / /usr/local/
COPY --link --from=make / /usr/local/
WORKDIR /tmp/github.com/containerd/runwasi
ARG name
ARG version
RUN --mount=type=cache,target=/target \
    --mount=type=cache,target=/usr/local/cargo/registry <<EOF
git clone -q --config advice.detachedHead=false --depth 1 --branch "containerd-shim-wasmtime/v${version}" https://github.com/containerd/runwasi .
export CARGO_HOME=/usr/local/cargo
export CARGO_TARGET_DIR=/target/
export RUSTUP_HOME=/usr/local/rustup
export RUSTFLAGS='-C target-feature=+crt-static'
make -j$(nproc) build-wasmtime TARGET_DIR="${CARGO_TARGET_DIR}"
make install-wasmtime PREFIX="${prefix}" TARGET_DIR="${CARGO_TARGET_DIR}"
EOF