#syntax=docker/dockerfile:1.17.0@sha256:e2dd261f92e4b763d789984f6eab84be66ab4f5f08052316d8eb8f173593acf7

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/GitoxideLabs/gitoxide/releases/download/v${version}/gitoxide-max-pure-v${version}-${arch}-unknown-linux-musl.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "GitoxideLabs/gitoxide" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin/" --strip-components=1 --no-same-owner \
    "gitoxide-max-pure-v${version}-${arch}-unknown-linux-musl/gix" \
    "gitoxide-max-pure-v${version}-${arch}-unknown-linux-musl/ein"
    
"${prefix}/bin/gix" completions --shell bash >"${prefix}/share/bash-completion/completions/gix"
"${prefix}/bin/gix" completions --shell fish >"${prefix}/share/fish/vendor_completions.d/gix.fish"
"${prefix}/bin/gix" completions --shell zsh >"${prefix}/share/zsh/vendor-completions/_gix"
    
"${prefix}/bin/ein" completions --shell bash >"${prefix}/share/bash-completion/completions/ein"
"${prefix}/bin/ein" completions --shell fish >"${prefix}/share/fish/vendor_completions.d/ein.fish"
"${prefix}/bin/ein" completions --shell zsh >"${prefix}/share/zsh/vendor-completions/_ein"
EOF