#syntax=docker/dockerfile:1.8.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:dc6c0030ff36d8c83922c5c24088c89faf3cb4f0b21540e231f35408453b76c3 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
WORKDIR /uniget_bootstrap/opt/gcloud
RUN <<EOF
check-download "https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-${version}-linux-${arch}.tar.gz"
curl --silent --show-error --location --fail "https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-${version}-linux-${arch}.tar.gz" \
| tar --extract --gzip --strip-components=1 --no-same-owner
ln --symbolic --relative --force "${prefix}/opt/gcloud/bin/gcloud" "${prefix}/bin/gcloud"
ln --symbolic --relative --force "${prefix}/opt/gcloud/bin/bq" "${prefix}/bin/bq"

cp "${prefix}/opt/gcloud/path.bash.inc" "${prefix}/share/bash-completion/completions/foo"
cp "${prefix}/opt/gcloud/path.fish.inc" "${prefix}/share/fish/vendor_completions.d/foo.fish"
cp "${prefix}/opt/gcloud/path.zsh.inc"  "${prefix}/share/zsh/vendor-completions/_foo"
EOF