#syntax=docker/dockerfile:1.11.1@sha256:1f2be5a2aa052cbd9aedf893d17c63277c3d1c51b3fb0f3b029c6b34f658d057

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
WORKDIR /uniget_bootstrap/opt/gcloud
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-${version}-linux-${arch}.tar.gz"
filename="$( basename "${url}" )"

check-download "${url}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --strip-components=1 --no-same-owner

ln --symbolic --relative --force "${prefix}/opt/gcloud/bin/gcloud" "${prefix}/bin/gcloud"
ln --symbolic --relative --force "${prefix}/opt/gcloud/bin/bq" "${prefix}/bin/bq"

cp "${prefix}/opt/gcloud/path.bash.inc" "${prefix}/share/bash-completion/completions/gcloud"
cp "${prefix}/opt/gcloud/path.fish.inc" "${prefix}/share/fish/vendor_completions.d/gcloud.fish"
cp "${prefix}/opt/gcloud/path.zsh.inc"  "${prefix}/share/zsh/vendor-completions/_gcloud"
EOF