#syntax=docker/dockerfile:1.6.0

FROM ghcr.io/uniget-org/tools/cosign:latest AS cosign

FROM nicholasdille/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
COPY --from=cosign / /usr/local/
COPY kubectl.sh ${prefix}/etc/profile.d/
RUN <<EOF
curl --silent --location --fail --output "${prefix}/bin/kubectl" \
    "https://dl.k8s.io/release/v${version}/bin/linux/${alt_arch}/kubectl"
chmod +x "${prefix}/bin/kubectl"

if test "$(echo -e "1.26.0-beta.0\n${version}" | sort -V | head -n 1)" == "1.26.0-beta.0"; then
    echo "Verifying keyless signature for kubectl"
    curl --silent --location --fail --output "/tmp/kubectl.sig" \
        "https://dl.k8s.io/release/v${version}/bin/linux/${alt_arch}/kubectl.sig"
    curl --silent --location --fail --output "/tmp/kubectl.cert" \
        "https://dl.k8s.io/release/v${version}/bin/linux/${alt_arch}/kubectl.cert"
    COSIGN_EXPERIMENTAL=1 cosign verify-blob "${prefix}/bin/kubectl" \
        --signature "/tmp/kubectl.sig" \
        --certificate "/tmp/kubectl.cert" \
        --certificate-oidc-issuer https://accounts.google.com \
        --certificate-identity krel-staging@k8s-releng-prod.iam.gserviceaccount.com
    rm -f \
        "/tmp/kubectl.sig" \
        "/tmp/kubectl.cert"
fi

curl --silent --location --fail --output "${prefix}/bin/kubectl-convert" \
    "https://dl.k8s.io/release/v${version}/bin/linux/${alt_arch}/kubectl-convert"
chmod +x "${prefix}/bin/kubectl-convert"

if test "$(echo -e "1.26.0-beta.0\n${version}" | sort -V | head -n 1)" == "1.26.0-beta.0"; then
    echo "Verifying keyless signature for kubectl-convert"
    curl --silent --location --fail --output "/tmp/kubectl-convert.sig" \
        "https://dl.k8s.io/release/v${version}/bin/linux/${alt_arch}/kubectl-convert.sig"
    curl --silent --location --fail --output "/tmp/kubectl-convert.cert" \
        "https://dl.k8s.io/release/v${version}/bin/linux/${alt_arch}/kubectl-convert.cert"
    COSIGN_EXPERIMENTAL=1 cosign verify-blob "${prefix}/bin/kubectl-convert" \
        --signature "/tmp/kubectl-convert.sig" \
        --certificate "/tmp/kubectl-convert.cert" \
        --certificate-oidc-issuer https://accounts.google.com \
        --certificate-identity krel-staging@k8s-releng-prod.iam.gserviceaccount.com
    rm -f \
        "/tmp/kubectl-convert.sig" \
        "/tmp/kubectl-convert.cert"
fi

"${prefix}/bin/kubectl" completion bash >"${prefix}/share/bash-completion/completions/kubectl"
"${prefix}/bin/kubectl" completion zsh >"${prefix}/share/zsh/vendor-completions/_kubectl"
EOF