#syntax=docker/dockerfile:1.27.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM ghcr.io/uniget-org/tools/node-lts:latest AS node

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
#FROM registry.gitlab.com/uniget-org/images/build-essential:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=node / /usr/local/
WORKDIR /uniget_bootstrap/libexec/bru
ARG name
ARG version
RUN <<EOF
npm install \
    --omit=dev \
    "@usebruno/cli@${version}"
ln --symbolic --relative --force "${prefix}/libexec/bru/node_modules/.bin/bru" "${prefix}/bin/"
EOF
#RUN <<EOF
#"${prefix}/bin/bru" completion bash >"${prefix}/share/bash-completion/completions/bru"
#"${prefix}/bin/bru" completion fish >"${prefix}/share/fish/vendor_completions.d/bru.fish"
#"${prefix}/bin/bru" completion zsh >"${prefix}/share/zsh/vendor-completions/_bru"
#EOF