#syntax=docker/dockerfile

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/abhishekamralkar/argus/releases/download/v${version}/argus_${version}_linux_${alt_arch}.tar.gz"
filename="$(basename "${url}")"

check-github-release-asset "abhishekamralkar/argus" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin" --no-same-owner \
    argus
EOF
RUN <<EOF
"${prefix}/bin/argus" completion bash >"${prefix}/share/bash-completion/completions/argus"
"${prefix}/bin/argus" completion fish >"${prefix}/share/fish/vendor_completions.d/argus.fish"
"${prefix}/bin/argus" completion zsh  >"${prefix}/share/zsh/vendor-completions/_argus"
EOF
