#syntax=docker/dockerfile:1.8.1

FROM ghcr.io/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "antonmedv/fx" "${version}" "fx_linux_${alt_arch}"
curl --silent --show-error --location --fail --output "${prefix}/bin/fx" \
    "https://github.com/antonmedv/fx/releases/download/${version}/fx_linux_${alt_arch}"
chmod +x "${prefix}/bin/fx"
EOF