#syntax=docker/dockerfile:1.21.0@sha256:27f9262d43452075f3c410287a2c43f5ef1bf7ec2bb06e8c9eeb1b8d453087bc

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/kluctl/kluctl/releases/download/v${version}/kluctl_v${version}_linux_${alt_arch}.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "kluctl/kluctl" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin/" --no-same-owner
"${prefix}/bin/kluctl" completion bash >"${prefix}/share/bash-completion/completions/kluctl"
"${prefix}/bin/kluctl" completion fish >"${prefix}/share/fish/vendor_completions.d/kluctl.fish"
"${prefix}/bin/kluctl" completion zsh >"${prefix}/share/zsh/vendor-completions/_kluctl"
EOF