#syntax=docker/dockerfile:1.20.0@sha256:26147acbda4f14c5add9946e2fd2ed543fc402884fd75146bd342a7f6271dc1d

# krew internals:
# - KREW_ROOT defaults to ~/.krew
# - Add KREW_ROOT/bin to PATH
# - KREW_ROOT/receipts/<name>.yaml describes plugin (required for `krew list`)
# - KREW_ROOT/store/<name>/<version>/<binary>
# - KREW_ROOT/bin/<binary> links to binary in store

FROM ghcr.io/uniget-org/tools/krew:latest AS krew

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=krew / /usr/local/
ARG name
ARG version
COPY --chmod=755 <<EOF /uniget_bootstrap/bin/krew-uniget
#!/bin/bash
set -o errexit

export KREW_ROOT="/libexec/krew"
krew "\$@"
EOF
COPY <<EOF /uniget_bootstrap/etc/profile.d/krew.sh
export PATH="/libexec/krew/bin:${PATH}"
EOF
RUN <<EOF
export KREW_ROOT="${prefix}/libexec/krew"
mkdir -p "${KREW_ROOT}"
krew update
krew install krew
plugins=(
    access-matrix
    advise-policy
    advise-psp
    assert
    blame
    bulk-action
    capture
    cert-manager
    cilium
    cyclonus
    debug-shell
    deprecations
    df-pv
    doctor
    edit-status
    emit-event
    evict-pod
    exec-as
    exec-cronjob
    explore
    fields
    flame
    fleet
    foreach
    fuzzy
    gadget
    get-all
    graph
    grep
    hns
    ice
    ingress-nginx
    images
    janitor
    klock
    kluster-capacity
    konfig
    kubesec-scan
    kurt
    lineage
    modify-secret
    mtail
    neat
    node-shell
    np-viewer
    outdated
    pexec
    pod-dive
    pod-inspect
    pod-lens
    preflight
    rbac-lookup
    rbac-tool
    rbac-view
    resource-capacity
    resource-snapshot
    rolesum
    score
    slice
    sniff
    socks5-proxy
    spy
    sshd
    starboard
    status
    stern
    strace
    sudo
    support-bundle
    tap
    trace
    tree
    tunnel
    view-allocations
    view-utilization
    viewnode
    whisper-secret
    who-can
    whoami
)
for plugin in "${plugins[@]}"; do
    echo "Processing ${plugin}"
    krew install "${plugin}"
done
find "${KREW_ROOT}/bin" -type l -exec ln --symbolic --relative --force {} "${prefix}/bin/" \;
EOF
