#syntax=docker/dockerfile:1.20.0@sha256:26147acbda4f14c5add9946e2fd2ed543fc402884fd75146bd342a7f6271dc1d

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
COPY --chmod=0755 <<EOF /uniget_bootstrap/bin/dummy
#!/bin/sh
exec true
EOF
RUN <<EOF
ln --symbolic --relative --force \
    "${prefix}/bin/dummy" \
    "${prefix}/bin/dummy-symlink-fine"
ln --symbolic --relative --force \
    "${prefix}/bin/dummy-gone" \
    "${prefix}/bin/dummy-symlink-broken"
EOF
