#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM ghcr.io/uniget-org/tools/go:latest AS go
FROM ghcr.io/uniget-org/tools/make:latest AS make

FROM registry.gitlab.com/uniget-org/images/build-base:3.24@sha256:bfcf3e99a47ac1b07f9dd40db914d12a3a15f5b886a9e7f35a60be58c9d294bc AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=go / /usr/local/
COPY --link --from=make / /usr/local/
WORKDIR /go/src/github.com/adnanh/webhook
ARG name
ARG version
RUN --mount=type=cache,target=/root/go/pkg/mod <<EOF
check-clone "https://github.com/adnanh/webhook" "${version}"
git clone -q --config advice.detachedHead=false --depth 1 --branch "${version}" https://github.com/adnanh/webhook .
export CGO_ENABLED=0
go build -ldflags "-s -w" -o "${prefix}/bin/webhook"
EOF