#syntax=docker/dockerfile:1.8.1

FROM ghcr.io/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]

ARG name
ARG version

RUN <<EOF
mkdir -p "${prefix}/libexec/${name}/bin"
EOF

COPY daemon.json /uniget_bootstrap/etc/docker-preview/
COPY --chmod=0755 <<EOF /uniget_bootstrap/bin/docker-preview
#!/bin/bash
set -o errexit
export DOCKER_HOST=unix:///var/run/docker-preview.sock
exec /libexec/${name}/bin/docker "\$@"
EOF

RUN <<EOF
check-download "https://download.docker.com/linux/static/test/${arch}/docker-${version}.tgz"
curl --silent --show-error --location --fail "https://download.docker.com/linux/static/test/${arch}/docker-${version}.tgz" \
| tar --extract --gzip --directory="${prefix}/libexec/${name}/bin" --no-same-owner --strip-components=1

check-download "https://download.docker.com/linux/static/test/${arch}/docker-rootless-extras-${version}.tgz"
curl --silent --show-error --location --fail "https://download.docker.com/linux/static/stable/${arch}/docker-rootless-extras-${version}.tgz" \
| tar --extract --gzip --directory="${prefix}/libexec/${name}/bin" --no-same-owner --strip-components=1
EOF

RUN <<EOF
check-download "https://github.com/moby/moby/raw/v${version}/contrib/init/systemd/docker.service"
curl --silent --show-error --location --fail --output "${prefix}/etc/systemd/system/${name}.service.go-template" \
    "https://github.com/moby/moby/raw/v${version}/contrib/init/systemd/docker.service"
sed -i "/^\[Service\]/a Environment=PATH=/usr/local/libexec/${name}/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin" "${prefix}/etc/systemd/system/${name}.service.go-template"
sed -i -E "s|^ExecStart=/usr/bin/dockerd|ExecStart={{ .Target }}/bin/dockerd|" "${prefix}/etc/systemd/system/${name}.service.go-template"
sed -i -n '/Type=notify/!p' "${prefix}/etc/systemd/system/${name}.service.go-template"
sed -i -n '/Requires=docker.socket/!p' "${prefix}/etc/systemd/system/${name}.service.go-template"
EOF

COPY <<EOF /uniget_bootstrap/etc/docker/daemon.json
{
    "default-runtime": "runc",
    "features":{
        "buildkit": true,
        "containerd-snapshotter": true
    }
}
EOF
