#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:059b11407572b2fd733e7bcd1c528852394d7fe1abef7119a1a97356983cab76 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://cdn.teleport.dev/teleport-v${version}-linux-${alt_arch}-bin.tar.gz"
filename="$(basename "${url}")"

check-download "${url}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin/" --strip-components=1 --no-same-owner \
    teleport/tctl \
    teleport/teleport \
    teleport/tbot \
    teleport/tsh

curl --silent --show-error --location --fail --output "${prefix}/etc/systemd/system/teleport.service.go-template" \
    "https://github.com/gravitational/teleport/blob/v${version}/examples/systemd/teleport.service"
sed -i "s|ExecStart=/usr/local/bin/teleport|ExecStart={{ .Target }}/bin/teleport|" "${prefix}/etc/systemd/system/teleport.service.go-template"
EOF