#syntax=docker/dockerfile:1.8.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:6ff62e5ed6b1c33f0ae1644692a354281534a37ec4d752cf480850e19a94d16d AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
curl --silent --show-error --location --fail "https://cdn.teleport.dev/teleport-v${version}-linux-${alt_arch}-bin.tar.gz" \
| tar --extract --gzip --directory="${prefix}/bin/" --strip-components=1 --no-same-owner \
    teleport/tctl \
    teleport/teleport \
    teleport/tbot \
    teleport/tsh
curl --silent --show-error --location --fail --output "${prefix}/etc/systemd/system/teleport.service" \
    "https://github.com/gravitational/teleport/blob/v${version}/examples/systemd/teleport.service"
sed -i "s|ExecStart=/usr/local/bin/teleport|ExecStart=/bin/teleport|" "${prefix}/etc/systemd/system/teleport.service"
EOF