#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:b0b654de801604e256237f2c27a907a4b61b59ebd83423ad0e0e465c0a3ba9cd AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/watchexec/watchexec/releases/download/v${version}/watchexec-${version}-${arch}-unknown-linux-musl.tar.xz"
filename="$( basename "${url}" )"

check-github-release-asset "watchexec/watchexec" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --xz --directory="${prefix}/bin/" --strip-components=1 --no-same-owner \
    "watchexec-${version}-${arch}-unknown-linux-musl/watchexec" \
    "watchexec-${version}-${arch}-unknown-linux-musl/watchexec.1"

mv "${prefix}/bin/watchexec.1" "${prefix}/share/man/man1/"

"${prefix}/bin/watchexec" --completions bash >"${prefix}/share/bash-completion/completions/watchexec"
"${prefix}/bin/watchexec" --completions fish >"${prefix}/share/fish/vendor_completions.d/watchexec.fish"
"${prefix}/bin/watchexec" --completions zsh  >"${prefix}/share/zsh/vendor-completions/_watchexec"
EOF