# yaml-language-server: $schema=https://tools.uniget.dev/schema.yaml
name: flux
description: Lightweight scripting language for querying databases (like InfluxDB)
license:
  name: MIT License
  link: https://github.com/influxdata/flux/blob/master/LICENSE
homepage: https://influxdata.com
repository: https://github.com/influxdata/flux
version: "0.200.0"
tags:
- org/influxdata
- observability/metrics
- o11y
- category/monitoring
- lang/go
- type/cli
check: "" # No version parameter
platforms:
- linux/amd64
renovate:
  datasource: github-releases
  package: influxdata/flux
  extractVersion: ^v(?<version>.+)$
conflicts_with:
- flux2
