#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:b0b654de801604e256237f2c27a907a4b61b59ebd83423ad0e0e465c0a3ba9cd AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
echo "### Setting architecture string for ${TARGETPLATFORM}"
case "${arch}" in
    x86_64)
        export arch_suffix="x86_64-unknown-linux-gnu"
        ;;
    aarch64)
        export arch_suffix="aarch64-unknown-linux-gnu"
        ;;
    *)
        echo "ERROR: Unsupported architecture ${alt_arch}."
        exit 1
        ;;
esac
echo "    Using ${arch_suffix}"

url="https://github.com/orhun/git-cliff/releases/download/v${version}/git-cliff-${version}-${arch_suffix}.tar.gz"
filename="$(basename "${url}")"

check-github-release-asset "orhun/git-cliff" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin/" --strip-components=1 --no-same-owner \
    "git-cliff-${version}/git-cliff" \
    "git-cliff-${version}/completions" \
    "git-cliff-${version}/man/git-cliff.1"

cp "${prefix}/bin/completions/git-cliff.bash" "${prefix}/share/bash-completion/completions/git-cliff"
cp "${prefix}/bin/completions/git-cliff.fish" "${prefix}/share/fish/vendor_completions.d/git-cliff.fish"
cp "${prefix}/bin/completions/_git-cliff" "${prefix}/share/zsh/vendor-completions/_git-cliff"
rm -rf "${prefix}/bin/completions"

cp "${prefix}/bin/man/git-cliff.1" "${prefix}/share/man/man1/"
rm -rf "${prefix}/bin/man"
EOF
