#syntax=docker/dockerfile:1.27.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM ghcr.io/uniget-org/tools/rust:latest AS rust

FROM registry.gitlab.com/uniget-org/images/build-essential:26.04@sha256:5ee01cd64296e795943405f10d803592dbd27cad7d35cd6ee1271bf177a71146 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
COPY --link --from=rust / /usr/local/
WORKDIR /tmp/github.com/uutils/util-linux
RUN --mount=type=cache,target=/usr/local/cargo/registry <<EOF
check-clone "https://github.com/uutils/util-linux" "${version}"
git clone -q --config advice.detachedHead=false --depth 1 --branch "${version}" https://github.com/uutils/util-linux .
export CARGO_HOME=/usr/local/cargo
export RUSTUP_HOME=/usr/local/rustup
cargo build --release --target "${arch}-unknown-linux-gnu"
cp "target/${arch}-unknown-linux-gnu/release/util-linux" "${prefix}/bin/"
EOF
RUN <<EOF
"${prefix}/bin/util-linux" --help 2>/dev/null \
    | grep -oP '(?<=    ).+' \
    | tr ',' '\n' \
    | sed 's/^ //;s/ //' \
    | while read -r util; do
        ln --symbolic --relative --force "${prefix}/bin/util-linux" "${prefix}/bin/${util}"
    done
EOF
