#syntax=docker/dockerfile:1.8.0

FROM ghcr.io/uniget-org/tools/go:latest AS go

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:6ff62e5ed6b1c33f0ae1644692a354281534a37ec4d752cf480850e19a94d16d AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=go / /usr/local/
WORKDIR /go/src/github.com/containers/podman-tui
ARG name
ARG version
RUN <<EOF
export CGO_ENABLED=0
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/containers/podman-tui .
go build -mod=vendor -o ./bin/linux/podman-tui -tags "containers_image_openpgp remote"
cp ./bin/linux/podman-tui "${prefix}/bin/"
EOF
