#syntax=docker/dockerfile:1.7.1

FROM ghcr.io/uniget-org/images/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "argoproj/argo-cd" "v${version}" "argocd-linux-${alt_arch}"
curl --silent --show-error --location --fail --output "${prefix}/bin/argocd" \
    "https://github.com/argoproj/argo-cd/releases/download/v${version}/argocd-linux-${alt_arch}"
chmod +x "${prefix}/bin/argocd"
"${prefix}/bin/argocd" completion bash >"${prefix}/share/bash-completion/completions/argocd"
"${prefix}/bin/argocd" completion zsh >"${prefix}/share/zsh/vendor-completions/_argocd"
EOF