#syntax=docker/dockerfile:1.6.0

FROM ghcr.io/uniget-org/images/build-essential:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG DEBIAN_FRONTEND=noninteractive
RUN <<EOF
apt-get update
apt-get -y install --no-install-recommends \
    python3 \
    libltdl-dev \
    m4 \
    bison \
    flex
EOF
WORKDIR /tmp/graphviz
ARG name
ARG version
RUN <<EOF
check-download "https://gitlab.com/graphviz/graphviz/-/archive/${version}/graphviz-${version}.tar.gz"
curl --silent --location --fail "https://gitlab.com/graphviz/graphviz/-/archive/${version}/graphviz-${version}.tar.gz" \
| tar --extract --gzip --strip-components=1
./autogen.sh
./configure \
    --prefix="${prefix}" \
    --enable-static=yes \
    --enable-shared=no \
    --enable-ltdl=no \
    --enable-swig=no \
    --enable-tcl=no \
    --enable-x=no \
    --with-expat=no \
    --with-visio=no \
    --with-cgraph=no \
    --with-fontconfig=no \
    --disable-sharp \
    --disable-guile \
    --disable-io \
    --disable-java \
    --disable-lua \
    --disable-ocaml \
    --disable-perl \
    --disable-php \
    --disable-python \
    --disable-ruby \
    --disable-tcl \
    --with-gtk=no \
    --with-poppler=no \
    --with-gdk-pixbuf=no \
    --with-gtkgl=no \
    --with-gtkglext=no \
    --with-ann=no \
    --with-glade=no \
    --with-qt=no \
    --with-x=nomake
make -j$(nproc)
make install
mv "${prefix}/bin/dot_static" "${prefix}/bin/dot"
EOF