#syntax=docker/dockerfile:1.13.0@sha256:426b85b823c113372f766a963f68cfd9cd4878e1bcc0fda58779127ee98a28eb

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
check-github-release-asset "containernetworking/plugins" "v${version}" "cni-plugins-linux-${alt_arch}-v${version}.tgz"
mkdir -p "${prefix}/libexec/cni"
curl --silent --show-error --location --fail "https://github.com/containernetworking/plugins/releases/download/v${version}/cni-plugins-linux-${alt_arch}-v${version}.tgz" \
| tar --extract --gzip --directory="${prefix}/libexec/cni" --no-same-owner

curl --silent --show-error --location --fail --output "${prefix}/etc/systemd/system/cni-dhcp.service" \
    "https://github.com/containernetworking/plugins/raw/v${version}/plugins/ipam/dhcp/systemd/cni-dhcp.service"
sed -i -E 's|^ExecStart=/opt/cni/bin/dhcp|ExecStart={{ .Target }}/libexec/cni/dhcp|' "${prefix}/etc/systemd/system/cni-dhcp.service"

curl --silent --show-error --location --fail --output "${prefix}/etc/systemd/system/cni-dhcp.socket" \
    "https://github.com/containernetworking/plugins/raw/v${version}/plugins/ipam/dhcp/systemd/cni-dhcp.socket"
EOF