#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/Orange-OpenSource/hurl/releases/download/${version}/hurl-${version}-${arch}-unknown-linux-gnu.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "Orange-OpenSource/hurl" "${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}" --strip-components=1 --no-same-owner
mv \
    "${prefix}/man/man1/hurl.1.gz" \
    "${prefix}/man/man1/hurlfmt.1.gz" \
    "${prefix}/share/man/man1/"
rm -rf "${prefix}/man/"

mv "${prefix}/completions/hurl.bash"    "${prefix}/share/bash-completion/completions/hurl"
mv "${prefix}/completions/hurl.fish"    "${prefix}/share/fish/vendor_completions.d/hurl.fish"
mv "${prefix}/completions/_hurl"        "${prefix}/share/zsh/vendor-completions/_hurl"
mv "${prefix}/completions/hurlfmt.bash" "${prefix}/share/bash-completion/completions/hurlfmt"
mv "${prefix}/completions/hurlfmt.fish" "${prefix}/share/fish/vendor_completions.d/hurlfmt.fish"
mv "${prefix}/completions/_hurlfmt"     "${prefix}/share/zsh/vendor-completions/_hurlfmt"
rmdir "${prefix}/completions"
EOF