#syntax=docker/dockerfile:1.24.0@sha256:87999aa3d42bdc6bea60565083ee17e86d1f3339802f543c0d03998580f9cb89

FROM ghcr.io/uniget-org/tools/go:latest AS go
FROM ghcr.io/uniget-org/tools/goreleaser:latest AS goreleaser

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:99a2bccd1ad68bfc5b1d1eb356cf54b7dd94e45c5216b89c87b9e21c70e12b9f AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=go / /usr/local/
COPY --link --from=goreleaser / /usr/local/
WORKDIR /go/src/github.com/GoogleCloudPlatform/docker-credential-gcr
ARG name
ARG version
RUN --mount=type=cache,target=/root/go/pkg/mod <<EOF
check-clone "https://github.com/GoogleCloudPlatform/docker-credential-gcr" "v${version}"
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/GoogleCloudPlatform/docker-credential-gcr .
export CGO_ENABLED=0
go build \
    -ldflags "-s -w -X github.com/GoogleCloudPlatform/docker-credential-gcr/v2/config.Version=${version}" \
    -o "${prefix}/bin/docker-credential-gcr" \
    .
EOF