#syntax=docker/dockerfile:1.15.1@sha256:05e0ad437efefcf144bfbf9d7f728c17818408e6d01432d9e264ef958bbd52f3

FROM ghcr.io/uniget-org/tools/go:latest AS go
FROM ghcr.io/uniget-org/tools/goreleaser:latest AS goreleaser

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=go / /usr/local/
COPY --link --from=goreleaser / /usr/local/
WORKDIR /go/src/github.com/GoogleCloudPlatform/docker-credential-gcr
ARG name
ARG version
RUN --mount=type=cache,target=/root/go/pkg/mod <<EOF
check-clone "https://github.com/GoogleCloudPlatform/docker-credential-gcr" "v${version}"
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/GoogleCloudPlatform/docker-credential-gcr .
export CGO_ENABLED=0
go build \
    -ldflags "-s -w -X github.com/GoogleCloudPlatform/docker-credential-gcr/v2/config.Version=${version}" \
    -o "${prefix}/bin/docker-credential-gcr" \
    .
EOF