#syntax=docker/dockerfile

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/neilotoole/sq/releases/download/v${version}/sq-${version}-linux-${alt_arch}.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "neilotoole/sq" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin" --no-same-owner \
    sq

"${prefix}/bin/sq" completion bash >"${prefix}/share/bash-completion/completions/sq"
"${prefix}/bin/sq" completion fish >"${prefix}/share/fish/vendor_completions.d/sq.fish"
"${prefix}/bin/sq" completion zsh >"${prefix}/share/zsh/vendor-completions/_sq"
EOF
