#syntax=docker/dockerfile:1.8.1

FROM ghcr.io/uniget-org/tools/make:latest AS make

FROM ghcr.io/uniget-org/images/build-essential:24.04@sha256:2b201a13c865ad8ca885fb04659c3996fa547f5ce147f0996e2d7fd878d331e1 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ENV DEBIAN_FRONTEND=non-interactive
RUN <<EOF
apt-get update
apt-get -y install --no-install-recommends \
    ninja-build \
    libglib2.0-dev \
    libfdt-dev \
    libpixman-1-dev \
    zlib1g-dev \
    python3-pip \
    python-is-python3
EOF
COPY --link --from=make / /usr/local/
WORKDIR /tmp/qemu
ARG name
ARG version
ARG TARGETS="aarch64-softmmu x86_64-softmmu"
RUN <<EOF
check-clone https://github.com/qemu/qemu "v${version}"
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/qemu/qemu .
EOF
WORKDIR /tmp/qemu/build
RUN <<EOF
../configure --prefix="${prefix}" --static --enable-tools --disable-user --disable-gio --target-list="${TARGETS}"
make -j$(nproc)
EOF
RUN make install