#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM registry.gitlab.com/uniget-org/images/ubuntu:rolling AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/mikefarah/yq/releases/download/v${version}/yq_linux_${alt_arch}"
filename="$( basename "${url}" )"

check-github-release-asset "mikefarah/yq" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/yq"

"${prefix}/bin/yq" shell-completion bash >"${prefix}/share/bash-completion/completions/yq"
"${prefix}/bin/yq" shell-completion fish >"${prefix}/share/fish/vendor_completions.d/yq.fish"
"${prefix}/bin/yq" shell-completion zsh >"${prefix}/share/zsh/vendor-completions/_yq"
EOF