#syntax=docker/dockerfile:1.27.1@sha256:4edf897a3ffa55b89f906fc8cc78afdb3f1834cc9c7083565e611a8a7d5fe99e

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04 AS ubuntu2604
FROM registry.gitlab.com/uniget-org/images/build-essential:26.04 AS build-essential2604
FROM registry.gitlab.com/uniget-org/images/alpine:3.24 AS alpine324
FROM registry.gitlab.com/uniget-org/images/build-base:3.24 AS build-base324

FROM ubuntu2604 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version

RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
echo "### Setting architecture string for ${TARGETPLATFORM}"
case "${arch}" in
    x86_64)
        export arch_suffix="amd64"
        ;;
    aarch64)
        export arch_suffix="arm64"
        ;;
    *)
        echo "ERROR: Unsupported architecture ${arch}."
        exit 1
        ;;
esac
echo "    Using ${arch_suffix}"

url="https://github.com/mozillazg/ptcpdump/releases/download/v${version}/ptcpdump_${version}_linux_${arch_suffix}.tar.gz"
filename="$( basename "${url}" )"

check-download "${url}"
check-github-release-asset "mozillazg/ptcpdump" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin" --no-same-owner \
    ptcpdump
EOF
