#syntax=docker/dockerfile

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/foks-proj/go-foks/releases/download/v${version}/foks-${version}.musl.linux.${alt_arch}.gz"
filename="$( basename "${url}" )"

check-github-release-asset "foks-proj/go-foks" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

gzip --test "${uniget_cache_download}/${filename}"
gzip --stdout --decompress "${uniget_cache_download}/${filename}" >"${prefix}/bin/foks"
chmod 0755 "${prefix}/bin/foks"
EOF
