#syntax=docker/dockerfile:1.7.1

FROM ghcr.io/uniget-org/images/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "antoniomika/sish" "v${version}" "sish-${version}.linux-amd64.tar.gz"
curl --silent --location --fail "https://github.com/antoniomika/sish/releases/download/v${version}/sish-${version}.linux-${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/bin/" --strip-components=1 --no-same-owner \
    sish-${version}.linux-${alt_arch}/sish
EOF