#syntax=docker/dockerfile:1.10.0@sha256:865e5dd094beca432e8c0a1d5e1c465db5f998dca4e439981029b3b81fb39ed5

FROM ghcr.io/uniget-org/tools/make:latest AS make
FROM ghcr.io/uniget-org/tools/libmnl:latest AS libmnl
FROM ghcr.io/uniget-org/tools/libnftnl:latest AS libnftnl
FROM ghcr.io/uniget-org/tools/iptables:latest AS iptables
FROM ghcr.io/uniget-org/tools/libjansson:latest AS libjansson
FROM ghcr.io/uniget-org/tools/musl:latest AS musl

FROM ghcr.io/uniget-org/images/build-essential:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
RUN --mount=type=cache,target=/var/cache/apt <<EOF
apt-get update
apt-get -y install --no-install-recommends \
    bison \
    flex \
    asciidoc \
    libgmp-dev \
    libreadline-dev
EOF
COPY --link --from=make / /usr/local/
COPY --link --from=libmnl / /usr/local/
COPY --link --from=libnftnl / /usr/local/
COPY --link --from=iptables / /usr/local/
COPY --link --from=libjansson / /usr/local/
COPY --link --from=musl / /usr/local/
WORKDIR /tmp/nftables
ARG name
ARG version
RUN <<EOF
check-clone "https://git.netfilter.org/nftables/" "v${version}"
git clone --config advice.detachedHead=false --depth 1 --branch "v${version}" git://git.netfilter.org/nftables .
EOF
RUN <<EOF
#export PKG_CONFIG_PATH="/lib/pkgconfig:${PKG_CONFIG_PATH}"
./autogen.sh
./configure \
    --prefix="${prefix}" \
    --enable-static=yes \
    --with-xtables \
    --with-json \
    --with-cli=readline
make -j$(nproc)
make install
EOF