#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/denoland/deno/releases/download/v${version}/deno-${arch}-unknown-linux-gnu.zip"
filename="$(basename "${url}")"
check-github-release-asset "denoland/deno" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"
unzip -q -o -d "${prefix}/bin" "${uniget_cache_download}/${filename}"

url="https://github.com/denoland/deno/releases/download/v${version}/denort-${arch}-unknown-linux-gnu.zip"
filename="$(basename "${url}")"
check-github-release-asset "denoland/deno" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"
unzip -q -o -d "${prefix}/bin" "${uniget_cache_download}/${filename}"

"${prefix}/bin/deno" completions bash >"${prefix}/share/bash-completion/completions/deno"
"${prefix}/bin/deno" completions fish >"${prefix}/share/fish/vendor_completions.d/deno.fish"
"${prefix}/bin/deno" completions zsh >"${prefix}/share/zsh/vendor-completions/_deno"
EOF
