#syntax=docker/dockerfile:1.6.0

FROM ghcr.io/uniget-org/images/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]

ARG name
ARG version

COPY docker ${prefix}/libexec/podman/
RUN <<EOF
ln --symbolic --relative --force "${prefix}/libexec/podman/docker" "/bin/docker"
EOF