#syntax=docker/dockerfile:1.22.0@sha256:4a43a54dd1fedceb30ba47e76cfcf2b47304f4161c0caeac2db1c61804ea3c91

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
COPY --chmod=0755 install-docker-dev.sh "/uniget_bootstrap/bin/"
RUN <<EOF
DOCKER_DESKTOP_VERSION="$(
    echo "${version}" \
    | cut -d- -f2
)"
sed -i "s/docker_desktop_version:=DD_VERSION/docker_desktop_version:=${DOCKER_DESKTOP_VERSION}/" "/uniget_bootstrap/bin/install-docker-dev.sh"
EOF