#syntax=docker/dockerfile:1.10.0@sha256:865e5dd094beca432e8c0a1d5e1c465db5f998dca4e439981029b3b81fb39ed5

FROM ghcr.io/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
case "${alt_arch}" in
    amd64)
        export arch_suffix=""
        ;;
    arm64)
        export arch_suffix="_${alt_arch}"
        ;;
    *)
        echo "ERROR: Unsupported architecture (${alt_arch})."
        exit 1
        ;;
esac
curl --silent --show-error --location --fail "https://github.com/mintoolkit/mint/releases/download/${version}/dist_linux${arch_suffix}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/bin/" --strip-components=1 --no-same-owner \
    "dist_linux${arch_suffix}/mint" \
    "dist_linux${arch_suffix}/mint-sensor"
EOF