#syntax=docker/dockerfile:1.8.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:dc6c0030ff36d8c83922c5c24088c89faf3cb4f0b21540e231f35408453b76c3 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "osquery/osquery" "${version}" "osquery-${version}_1.linux_${arch}.tar.gz"
curl --silent --show-error --location --fail "https://github.com/osquery/osquery/releases/download/${version}/osquery-${version}_1.linux_${arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/" --strip-components=2 --no-same-owner \
    opt/osquery
ln --symbolic --relative --force "${prefix}/bin/osqueryd" "${prefix}/bin/osqueryi"
EOF