#syntax=docker/dockerfile:1.16.0@sha256:e2dd261f92e4b763d789984f6eab84be66ab4f5f08052316d8eb8f173593acf7

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/containers/fuse-overlayfs/releases/download/v${version}/fuse-overlayfs-${arch}"
filename="$( basename "${url}" )"

check-github-release-asset "containers/fuse-overlayfs" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/${name}"
EOF
RUN <<EOF
curl --silent --show-error --location --fail --output "${prefix}/share/man/man1/fuse-overlayfs.1" \
    "https://github.com/containers/fuse-overlayfs/raw/refs/tags/v${version}/fuse-overlayfs.1"
EOF