#syntax=docker/dockerfile:1.7.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:98429d8ee1c7cf7d06f65b692870d983f0965f1c1cdffa1dd04ef878b56293b6 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "vmware-archive/buildkit-cli-for-kubectl" "v${version}" "linux-v${version}.tgz"
curl --silent --location --fail "https://github.com/vmware-archive/buildkit-cli-for-kubectl/releases/download/v${version}/linux-v${version}.tgz" \
| tar --extract --gzip --directory="${prefix}/bin" --no-same-owner 
EOF