#syntax=docker/dockerfile:1.15.1@sha256:05e0ad437efefcf144bfbf9d7f728c17818408e6d01432d9e264ef958bbd52f3

FROM ghcr.io/uniget-org/tools/make:latest AS make

FROM registry.gitlab.com/uniget-org/images/build-base:3.21 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=make / /usr/local/
WORKDIR /tmp/uidmap
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/shadow-maint/shadow/releases/download/v${version}/shadow-${version}.tar.xz"
filename="$(basename "${url}")"

check-github-release-asset "shadow-maint/shadow" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --xz --strip-components 1

./configure --prefix="${prefix}" --enable-static --disable-shared
make -j$(nproc) LDFLAGS=--static
cp src/newuidmap "${prefix}/bin"
cp src/newgidmap "${prefix}/bin"
cp man/man1/newuidmap.1 "${prefix}/share/man/man1"
cp man/man1/newgidmap.1 "${prefix}/share/man/man1"
chmod u+s "${prefix}/bin/newuidmap"
chmod u+s "${prefix}/bin/newgidmap"
EOF