#syntax=docker/dockerfile:1.27.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM ghcr.io/uniget-org/tools/make:latest AS make

FROM registry.gitlab.com/uniget-org/images/build-base:3.24@sha256:6c6c414a06d0c48a6a05e1b3fe6940529179f7ed617dccbbcf4f2424383b1014 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=make / /usr/local/
WORKDIR /tmp/uidmap
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/shadow-maint/shadow/releases/download/v${version}/shadow-${version}.tar.xz"
filename="$(basename "${url}")"

check-github-release-asset "shadow-maint/shadow" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --xz --strip-components 1

./configure --prefix="${prefix}" --enable-static --disable-shared
make -j$(nproc) LDFLAGS=--static
cp src/newuidmap "${prefix}/bin"
cp src/newgidmap "${prefix}/bin"
cp man/man1/newuidmap.1 "${prefix}/share/man/man1"
cp man/man1/newgidmap.1 "${prefix}/share/man/man1"
chmod u+s "${prefix}/bin/newuidmap"
chmod u+s "${prefix}/bin/newgidmap"
EOF