#syntax=docker/dockerfile:1.14.0@sha256:426b85b823c113372f766a963f68cfd9cd4878e1bcc0fda58779127ee98a28eb

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
COPY docker.service.go-template /uniget_bootstrap/etc/systemd/user/
COPY delegate.conf /uniget_bootstrap/var/lib/uniget/contrib/docker-rootless/
COPY --chmod=0755 enable-docker-rootless.sh /uniget_bootstrap/bin/