#syntax=docker/dockerfile:1.11.1@sha256:10c699f1b6c8bdc8f6b4ce8974855dd8542f1768c26eb240237b8f1c9c6c9976

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
COPY docker.service.go-template /uniget_bootstrap/etc/systemd/user/
COPY delegate.conf /uniget_bootstrap/var/lib/uniget/contrib/docker-rootless/
COPY --chmod=0755 enable-docker-rootless.sh /uniget_bootstrap/bin/