#syntax=docker/dockerfile:1.8.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:178a01206383923b589ecfe3bace55431c4b8528086909ffcdc1ef88de4da10f AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
COPY docker.service /uniget_bootstrap/var/lib/uniget/contrib/docker-rootless/
COPY delegate.conf /uniget_bootstrap/var/lib/uniget/contrib/docker-rootless/
COPY --chmod=0755 enable-docker-rootless.sh /uniget_bootstrap/bin/