#syntax=docker/dockerfile:1.15.1@sha256:05e0ad437efefcf144bfbf9d7f728c17818408e6d01432d9e264ef958bbd52f3

FROM ghcr.io/uniget-org/tools/rust:latest AS rust

FROM registry.gitlab.com/uniget-org/images/build-essential:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=rust / /usr/local/
WORKDIR /tmp/github.com/bensadeh/tailspin
ARG name
ARG version
RUN --mount=type=cache,target=/target \
    --mount=type=cache,target=/usr/local/cargo/registry <<EOF
git clone -q --config advice.detachedHead=false --depth 1 --branch "${version}" https://github.com/bensadeh/tailspin .
export CARGO_HOME=/usr/local/cargo
export CARGO_TARGET_DIR=/target
export RUSTUP_HOME=/usr/local/rustup
export RUSTFLAGS='-C target-feature=+crt-static'
cargo build --release --target "${arch}-unknown-linux-gnu"
cp "/target/${arch}-unknown-linux-gnu/release/tspin" "${prefix}/bin/"

curl --silent --show-error --location --fail --output "${prefix}/share/bash-completion/completions/tspin" \
    --url "https://github.com/bensadeh/tailspin/raw/${version}/completions/tspin.bash"
curl --silent --show-error --location --fail --output "${prefix}/share/fish/vendor_completions.d/tspin.fish" \
    --url "https://github.com/bensadeh/tailspin/raw/${version}/completions/tspin.fish"
curl --silent --show-error --location --fail --output "${prefix}/share/zsh/vendor-completions/_tspin" \
    --url "https://github.com/bensadeh/tailspin/raw/${version}/completions/tspin.zsh"
EOF