#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
RUN --mount=type=cache,target=/var/cache/apt <<EOF
apt-get update
apt-get -y install --no-install-recommends \
    curl \
    ca-certificates \
    gcc \
    ncurses-dev \
    make \
    pkg-config
EOF
WORKDIR /tmp/tig
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/jonas/tig/releases/download/tig-${version}/tig-${version}.tar.gz"
filename="$(basename "${url}")"

check-github-release-asset "jonas/tig" "tig-${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --strip-components=1
EOF
RUN <<EOF
./configure

make -j$(nproc) LDFLAGS=-static prefix="${prefix}"
make install install-doc-man prefix="${prefix}"

cp contrib/tig-completion.bash "${prefix}/share/bash-completion/completions/tig"
cp contrib/tig-completion.zsh "${prefix}/share/zsh/vendor-completions/_tig"
EOF