#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:b0b654de801604e256237f2c27a907a4b61b59ebd83423ad0e0e465c0a3ba9cd AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
RUN --mount=type=cache,target=/var/cache/apt <<EOF
apt-get update
apt-get -y install --no-install-recommends \
    curl \
    ca-certificates \
    gcc \
    ncurses-dev \
    make \
    pkg-config
EOF
WORKDIR /tmp/tig
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/jonas/tig/releases/download/tig-${version}/tig-${version}.tar.gz"
filename="$(basename "${url}")"

check-github-release-asset "jonas/tig" "tig-${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --strip-components=1
EOF
RUN <<EOF
./configure

make -j$(nproc) LDFLAGS=-static prefix="${prefix}"
make install install-doc-man prefix="${prefix}"

cp contrib/tig-completion.bash "${prefix}/share/bash-completion/completions/tig"
cp contrib/tig-completion.zsh "${prefix}/share/zsh/vendor-completions/_tig"
EOF