#syntax=docker/dockerfile:1.6.0

FROM ghcr.io/uniget-org/images/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
mkdir -p "${prefix}/opt/jenkins"
curl --silent --location --fail --output "${prefix}/opt/jenkins/remoting.jar" \
    "https://repo.jenkins-ci.org/public/org/jenkins-ci/main/remoting/${version}/remoting-${version}.jar"
EOF