#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM rust:alpine AS build
RUN <<EOF
apk update
apk add \
    build-base \
    git \
    bash \
    cmake \
    clang
EOF
WORKDIR /tmp/github.com/cloudflareresearch/pvcli
ARG version
RUN <<EOF
git clone https://github.com/cloudflareresearch/pvcli .
git checkout "${version}"
cargo build --release --target "$(uname -m)-unknown-linux-musl"
cp "target/$(uname -m)-unknown-linux-musl/release/pvcli" "/usr/local/bin/"
EOF

FROM registry.gitlab.com/uniget-org/images/build-base:3.24 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --from=build "/usr/local/bin/pvcli" "/uniget_bootstrap/bin/"