#syntax=docker/dockerfile:1.8.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:178a01206383923b589ecfe3bace55431c4b8528086909ffcdc1ef88de4da10f AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "hetznercloud/cli" "v${version}" "hcloud-linux-${alt_arch}.tar.gz"
curl --silent --show-error --location --fail "https://github.com/hetznercloud/cli/releases/download/v${version}/hcloud-linux-${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/bin" --no-same-owner \
    hcloud
"${prefix}/bin/hcloud" completion bash >"${prefix}/share/bash-completion/completions/hcloud"
"${prefix}/bin/hcloud" completion fish >"${prefix}/share/fish/vendor_completions.d/hcloud.fish"
"${prefix}/bin/hcloud" completion zsh >"${prefix}/share/zsh/vendor-completions/_hcloud"
EOF