#syntax=docker/dockerfile:1.21.0@sha256:27f9262d43452075f3c410287a2c43f5ef1bf7ec2bb06e8c9eeb1b8d453087bc

FROM ghcr.io/uniget-org/tools/make:latest AS make

# Cannot use musl because execinfo.h is required but not available
FROM registry.gitlab.com/uniget-org/images/build-essential:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
RUN --mount=type=cache,target=/var/cache/apt <<EOF
apt-get update
apt-get -y install --no-install-recommends \
    cmake \
    libcurl4-openssl-dev \
    libssl-dev \
    libaio-dev \
    libnl-3-dev \
    libnl-genl-3-dev \
    libgflags-dev \
    libzstd-dev \
    libext2fs-dev \
    zlib1g-dev \
    libgtest-dev \
    sudo
EOF
COPY --link --from=make / /usr/local/
WORKDIR /tmp/overlaybd
ARG name
ARG version
RUN --mount=type=cache,target=/root/go/pkg/mod <<EOF
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/containerd/overlaybd .
git submodule update --init
mkdir build
cd build
cmake ..
make -j$(nproc)
make install DESTDIR=${prefix}
EOF