#syntax=docker/dockerfile:1.6.0

FROM nicholasdille/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "sealerio/sealer" "v${version}" "sealer-v${version}-linux-${alt_arch}.tar.gz"
curl --silent --location --fail "https://github.com/sealerio/sealer/releases/download/v${version}/sealer-v${version}-linux-${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/bin/" --no-same-owner

check-github-release-asset "sealerio/sealer" "v${version}" "seautil-v${version}-linux-${alt_arch}.tar.gz"
curl --silent --location --fail "https://github.com/sealerio/sealer/releases/download/v${version}/seautil-v${version}-linux-${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/bin/" --no-same-owner

"${prefix}/bin/sealer" completion bash >"${prefix}/share/bash-completion/completions/sealer"
EOF