#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/golangci/golangci-lint/releases/download/v${version}/golangci-lint-${version}-linux-${alt_arch}.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "golangci/golangci-lint" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin/" --strip-components=1 --no-same-owner \
    "golangci-lint-${version}-linux-${alt_arch}/golangci-lint"

"${prefix}/bin/golangci-lint" completion bash >"${prefix}/share/bash-completion/completions/golangci-lint"
"${prefix}/bin/golangci-lint" completion fish >"${prefix}/share/fish/vendor_completions.d/golangci-lint.fish"
"${prefix}/bin/golangci-lint" completion zsh >"${prefix}/share/zsh/vendor-completions/_golangci-lint"
EOF