#syntax=docker/dockerfile:1.21.0@sha256:26147acbda4f14c5add9946e2fd2ed543fc402884fd75146bd342a7f6271dc1d

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/go-task/task/releases/download/v${version}/task_linux_${alt_arch}.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "go-task/task" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin" --no-same-owner \
    task
curl --silent --show-error --location --fail "https://github.com/go-task/task/releases/download/v${version}/task_linux_${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/share" --strip-components=2 --no-same-owner \
    completion/bash/task.bash \
    completion/fish/task.fish \
    completion/zsh/_task
mv "${prefix}/share/task.bash" "${prefix}/share/bash-completion/completions/task"
mv "${prefix}/share/task.fish" "${prefix}/share/fish/vendor_completions.d/task.fish"
mv "${prefix}/share/_task" "${prefix}/share/zsh/vendor-completions/_task"
EOF