#syntax=docker/dockerfile:1.21.0@sha256:27f9262d43452075f3c410287a2c43f5ef1bf7ec2bb06e8c9eeb1b8d453087bc

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/openfaas/faasd/releases/download/${version}/faasd"
filename="$( basename "${url}" )"

check-github-release-asset "openfaas/faasd" "${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/faasd"


curl --silent --show-error --location --fail --output "${prefix}/etc/systemd/system/faasd.service.go-template" \
    "https://github.com/openfaas/faasd/raw/${version}/hack/faasd.service"
sed -i -E 's|^ExecStart=/usr/local/bin/faasd|ExecStart={{ .Target }}/bin/faasd|' "${prefix}/etc/systemd/system/faasd.service.go-template"

curl --silent --show-error --location --fail --output "${prefix}/etc/systemd/system/faasd-provider.service.go-template" \
    "https://github.com/openfaas/faasd/raw/${version}/hack/faasd-provider.service"
sed -i -E 's|^ExecStart=/usr/local/bin/faasd|ExecStart={{ .Target }}/bin/faasd|' "${prefix}/etc/systemd/system/faasd-provider.service.go-template"
EOF