#syntax=docker/dockerfile:1.8.1

FROM ghcr.io/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]

ARG name
ARG version

RUN <<EOF
check-github-release-asset "openfaas/faasd" "${version}" "faasd"
curl --silent --show-error --location --fail --output "${prefix}/bin/faasd" \
    "https://github.com/openfaas/faasd/releases/download/${version}/faasd"
chmod +x "${prefix}/bin/faasd"

curl --silent --show-error --location --fail --output "${prefix}/etc/systemd/system/faasd.service.go-template" \
    "https://github.com/openfaas/faasd/raw/${version}/hack/faasd.service"
sed -i -E 's|^ExecStart=/usr/local/bin/faasd|ExecStart={{ .Target }}/bin/faasd|' "${prefix}/etc/systemd/system/faasd.service.go-template"

curl --silent --show-error --location --fail --output "${prefix}/etc/systemd/system/faasd-provider.service.go-template" \
    "https://github.com/openfaas/faasd/raw/${version}/hack/faasd-provider.service"
sed -i -E 's|^ExecStart=/usr/local/bin/faasd|ExecStart={{ .Target }}/bin/faasd|' "${prefix}/etc/systemd/system/faasd-provider.service.go-template"
EOF