#syntax=docker/dockerfile:1.16.0@sha256:9857836c9ee4268391bb5b09f9f157f3c91bb15821bb77969642813b0d00518d

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/alexellis/k3sup/releases/download/${version}/k3sup"
filename="$( basename "${url}" )"

check-github-release-asset "alexellis/k3sup" "${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/k3sup"

"${prefix}/bin/k3sup" completion bash >"${prefix}/share/bash-completion/completions/k3sup"
"${prefix}/bin/k3sup" completion fish >"${prefix}/share/fish/vendor_completions.d/k3sup.fish"
"${prefix}/bin/k3sup" completion zsh >"${prefix}/share/zsh/vendor-completions/_k3sup"
EOF