#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:b0b654de801604e256237f2c27a907a4b61b59ebd83423ad0e0e465c0a3ba9cd AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version

RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
echo "### Setting architecture string for ${TARGETPLATFORM}"
case "${arch}" in
    x86_64)
        export target="x86_64"
        ;;
    aarch64)
        export target="aarch64"
        ;;
    *)
        echo "ERROR: Unsupported architecture ${arch}."
        exit 1
        ;;
esac
echo "    Using ${target}"

url="https://github.com/superradcompany/microsandbox/releases/download/v${version}/microsandbox-linux-${target}.tar.gz"
filename="$( basename "${url}" )"

check-download "${url}"
check-github-release-asset "superradcompany/microsandbox" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
mkdir /tmp/microsandbox
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="/tmp/microsandbox/" --no-same-owner
install --mode=0755 /tmp/microsandbox/msb "${prefix}/bin/msb"
install --mode=0644 /tmp/microsandbox/libkrunfw.so.* "${prefix}/lib/"
rm -rf /tmp/microsandbox
EOF
