#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:b0b654de801604e256237f2c27a907a4b61b59ebd83423ad0e0e465c0a3ba9cd AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
WORKDIR /tmp/texlive
COPY texlive.profile .
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://texlive.info/historic/systems/texlive/${version}/install-tl-unx.tar.gz"
filename="$( basename "${url}" )"

check-download "${url}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --strip-components=1 --no-same-owner
EOF
RUN <<EOF
perl install-tl --profile=texlive.profile #--repository=https://texlive.info/historic/systems/texlive/${version}/tlnet-final/
EOF
RUN <<EOF
find "${prefix}${target}/opt/texlive/bin/${arch}-linux" -type f -executable \
| xargs -n 1 basename \
| while read -r BINARY; do
    ln --symbolic --relative --force \
        "${prefix}${target}/opt/texlive/bin/${arch}-linux/${BINARY}" \
        "${prefix}${target}/bin/${BINARY}"
done
EOF