#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM ghcr.io/uniget-org/tools/node-lts:latest AS node
FROM ghcr.io/uniget-org/tools/python-3.12:latest AS python

FROM registry.gitlab.com/uniget-org/images/build-essential:26.04@sha256:0761326451efd5adfeaa56278c455d16cf8d5e4303b3fd3d99031af25b3da6c8 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=node / /usr/local/
COPY --link --from=python / /usr/local/
WORKDIR /uniget_bootstrap/libexec/dexto
ARG name
ARG version
RUN <<EOF
npm install \
    --omit=dev \
    "dexto@${version}"
ln --symbolic --relative --force "${prefix}/libexec/dexto/node_modules/.bin/dexto" "${prefix}/bin/"
EOF