#syntax=docker/dockerfile:1.6.0

FROM ghcr.io/uniget-org/images/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "carvel-dev/ytt" "v${version}" "ytt-linux-${alt_arch}"
curl --silent --location --fail --output "${prefix}/bin/ytt" \
    "https://github.com/carvel-dev/ytt/releases/download/v${version}/ytt-linux-${alt_arch}"
chmod +x "${prefix}/bin/ytt"
"${prefix}/bin/ytt" completion bash >"${prefix}/share/bash-completion/completions/ytt"
"${prefix}/bin/ytt" completion fish >"${prefix}/share/fish/vendor_completions.d/ytt.fish"
"${prefix}/bin/ytt" completion zsh >"${prefix}/share/zsh/vendor-completions/_ytt"
EOF