#syntax=docker/dockerfile:1.21.0@sha256:27f9262d43452075f3c410287a2c43f5ef1bf7ec2bb06e8c9eeb1b8d453087bc

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/danielb42/kubeswitch/releases/download/v${version}/kubeswitch_linux_${alt_arch}.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "danielb42/kubeswitch" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin" --no-same-owner \
    kubeswitch
EOF
COPY <<"EOF" "/uniget_bootstrap/share/bash-completion/completions/kubeswitch"
_kubeswitch_autocomplete() {
    local cur namespaces
    cur="${COMP_WORDS[COMP_CWORD]}"
    namespaces=$(kubectl get namespaces -o jsonpath='{.items[*].metadata.name}')

    COMPREPLY=( $(compgen -W "${namespaces}" -- ${cur}) )
}

complete -F _kubeswitch_autocomplete kubeswitch
EOF
