#syntax=docker/dockerfile

FROM ghcr.io/uniget-org/tools/rust:latest AS rust

FROM registry.gitlab.com/uniget-org/images/build-essential:26.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
COPY --link --from=rust / /usr/local/
WORKDIR /tmp/github.com/uutils/diffutils
RUN --mount=type=cache,target=/usr/local/cargo/registry <<EOF
check-clone "https://github.com/uutils/diffutils" "v${version}"
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/uutils/diffutils .
export CARGO_HOME=/usr/local/cargo
export RUSTUP_HOME=/usr/local/rustup
cargo build --release --target "${arch}-unknown-linux-musl"
cp "target/${arch}-unknown-linux-musl/release/diffutils" "${prefix}/bin/"
EOF
RUN <<EOF
ln --symbolic --relative --force "${prefix}/bin/diffutils" "${prefix}/bin/diff"
ln --symbolic --relative --force "${prefix}/bin/diffutils" "${prefix}/bin/cmp"
EOF
