#syntax=docker/dockerfile

FROM rust:latest AS build
RUN <<EOF
apt-get update
apt-get install -y --no-install-recommends \
    build-essential \
    git \
    bash \
    pkg-config
EOF
ARG version
WORKDIR /tmp/chimera
RUN <<EOF
git clone https://github.com/penberg/chimera.git .
git checkout "${version}"
cargo build --release --package chimera-cli --target "$(uname -m)-unknown-linux-gnu"
cp "target/$(uname -m)-unknown-linux-gnu/release/chimera" "/usr/local/bin/"
EOF

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --from=build "/usr/local/bin/chimera" "/uniget_bootstrap/bin/chimera"