#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM registry.gitlab.com/uniget-org/images/build-base:3.24 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
RUN <<EOF
apk update
apk add \
    rust \
    cargo \
    musl-dev
EOF
ARG name
ARG version
WORKDIR /tmp/chimera
RUN <<EOF
git clone https://github.com/penberg/chimera.git .
git checkout "${version}"
cargo build --release --package chimera-cli --target "${arch}-unknown-linux-musl"
install --mode=0755 target/"${arch}-unknown-linux-musl"/release/chimera "${prefix}/bin/"
EOF