#syntax=docker/dockerfile:1.17.0@sha256:e63addfe27b10e394a5f9f1e866961adc70d08573f1cb80f8d1a0999347b3553

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
echo "### Setting architecture string for ${TARGETPLATFORM}"
case "${arch}" in
    x86_64)
        export arch_suffix="${arch}"
        ;;
    aarch64)
        export arch_suffix="${alt_arch}"
        ;;
    *)
        echo "ERROR: Unsupported architecture ${arch}."
        exit 1
        ;;
esac
echo "    Using ${arch_suffix}"

url="https://github.com/kubernetes-sigs/ingress2gateway/releases/download/v${version}/ingress2gateway_Linux_${arch_suffix}.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "kubernetes-sigs/ingress2gateway" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin/" --no-same-owner \
    ingress2gateway

"${prefix}/bin/ingress2gateway" completion bash >"${prefix}/share/bash-completion/completions/ingress2gateway"
"${prefix}/bin/ingress2gateway" completion fish >"${prefix}/share/fish/vendor_completions.d/ingress2gateway.fish"
"${prefix}/bin/ingress2gateway" completion zsh >"${prefix}/share/zsh/vendor-completions/_ingress2gateway"
EOF