#syntax=docker/dockerfile:1.8.1

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:178a01206383923b589ecfe3bace55431c4b8528086909ffcdc1ef88de4da10f AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "docker/compose" "v${version}" "docker-compose-linux-${arch}"
curl --silent --show-error --location --fail --output "${prefix}/libexec/docker/cli-plugins/docker-compose" \
    "https://github.com/docker/compose/releases/download/v${version}/docker-compose-linux-${arch}"
chmod +x "${prefix}/libexec/docker/cli-plugins/docker-compose"
EOF