#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM ghcr.io/uniget-org/tools/make:latest AS make
FROM ghcr.io/uniget-org/tools/libcap:latest AS libcap

FROM registry.gitlab.com/uniget-org/images/build-base:3.23@sha256:e66b0c6fe2a1aabcc6a1898fa94b2a1fa4eb3c83874b491e4b5496d1318ebcc5 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
RUN --mount=type=cache,target=/var/cache/apk <<EOF
apk add --update-cache \
    libcap-dev \
    libcap-static \
    libbsd-dev \
    libbsd-static \
    linux-headers
EOF
COPY --link --from=make / /usr/local/
COPY --link --from=libcap / /usr/local/
WORKDIR /tmp/nsutils
ARG name
ARG version
RUN <<EOF
check-clone https://github.com/rd235/nsutils "v${version}"
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/rd235/nsutils .
autoreconf -if
./configure --prefix="${prefix}"
if test "${version}" == "0.2"; then
    cat <<EOP | patch -p0
--- nssearch.c.orig
+++ nssearch.c
@@ -25,6 +25,7 @@
 #include <stdlib.h>
 #include <string.h>
 #include <ctype.h>
+#include <limits.h>
 #include <dirent.h>
 #include <regex.h>
EOP
    cat <<EOP | patch -p0
--- nslist.c.orig
+++ nslist.c
@@ -22,6 +22,7 @@
 #define _GNU_SOURCE
 #include <stdio.h>
 #include <stdlib.h>
+#include <libgen.h>
 #include <unistd.h>
 #include <stdint.h>
 #include <string.h>
EOP
fi
make -j$(nproc) LDFLAGS=-static
make install
EOF