#syntax=docker/dockerfile:1.6.0

FROM nicholasdille/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
RUN <<EOF
apt-get update
apt-get -y install --no-install-recommends \
    git \
    ca-certificates \
    autoconf \
    automake \
    build-essential \
    libcap-dev \
    libbsd-dev \
    libcap2-bin
EOF
WORKDIR /tmp/nsutils
ARG name
ARG version
RUN <<EOF
check-clone https://github.com/rd235/nsutils "v${version}"
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/rd235/nsutils .
autoreconf -if
./configure --prefix="${prefix}${target}"
make LDFLAGS=--static
make install
EOF