#syntax=docker/dockerfile:1.27.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
case "${alt_arch}" in
    amd64)
        export arch_suffix="x86_64"
        ;;
    arm64)
        export arch_suffix="aarch64"
        ;;
    *)
        echo "ERROR: Unsupported architecture (${alt_arch})."
        exit 1
        ;;
esac
echo "    Using ${arch_suffix}"

url="https://github.com/tealdeer-rs/tealdeer/releases/download/v${version}/tealdeer-linux-${arch_suffix}-musl"
filename="$( basename "${url}" )"

check-github-release-asset "tealdeer-rs/tealdeer" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/tldr"
ln --symbolic --relative --force "${prefix}/bin/tldr" "${prefix}/bin/tealdeer"

curl --silent --show-error --location --fail --output "${prefix}/share/bash-completion/completions/tealdeer.bash" \
    "https://github.com/tealdeer-rs/tealdeer/raw/refs/tags/v${version}/completion/bash_tealdeer"
curl --silent --show-error --location --fail --output "${prefix}/share/fish/vendor_completions.d/tealdeer.fish" \
    "https://github.com/tealdeer-rs/tealdeer/raw/refs/tags/v${version}/completion/fish_tealdeer"
curl --silent --show-error --location --fail --output "${prefix}/share/zsh/vendor-completions/_tealdeer" \
    "https://github.com/tealdeer-rs/tealdeer/raw/refs/tags/v${version}/completion/zsh_tealdeer"
EOF
