#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM ghcr.io/uniget-org/tools/make:latest AS make

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
RUN --mount=type=cache,target=/var/cache/apt <<EOF
apt-get update
apt-get -y install --no-install-recommends \
    python3-pip \
    python3-venv \
    python-is-python3
EOF
COPY --link --from=make / /usr/local/
WORKDIR /tmp/kpxhs
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/akazukin5151/kpxhs/releases/download/v${version}/kpxhs-linux"
filename="$( basename "${url}" )"

check-github-release-asset "akazukin5151/kpxhs" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/kpxhs"


check-github-release-asset "akazukin5151/kpxhs" "v${version}" "kpxhs.1"
curl --silent --show-error --location --fail --output "${prefix}/share/man/man1/kpxhs.1" \
    "https://github.com/akazukin5151/kpxhs/releases/download/v${version}/kpxhs.1"
EOF