#syntax=docker/dockerfile:1.6.0

FROM nicholasdille/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
RUN <<EOF
apt-get update
apt-get -y install --no-install-recommends \
    build-essential \
    autoconf \
    automake \
    libtool \
    m4 \
    bison \
    flex
EOF
RUN <<EOF
mkdir -p "${prefix}/etc/ld.so.conf.d"
EOF
COPY <<EOF ${prefix}/etc/ld.so.conf.d/libcgroup.conf
/lib
EOF
WORKDIR /tmp/libcgroup
ARG name
ARG version
# Unable to build statically linked tools
RUN <<EOF
curl --silent --location --fail "https://github.com/libcgroup/libcgroup/releases/download/v${version}/libcgroup-${version}.tar.gz" \
| tar --extract --gzip --strip-components 1
./configure --prefix="${prefix}" --disable-pam --disable-daemon
make
make install
EOF
