#syntax=docker/dockerfile:1.21.0@sha256:26147acbda4f14c5add9946e2fd2ed543fc402884fd75146bd342a7f6271dc1d

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/dalance/procs/releases/download/v${version}/procs-v${version}-${arch}-linux.zip"
filename="$( basename "${url}" )"

check-github-release-asset "dalance/procs" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

unzip -t "${uniget_cache_download}/${filename}"
unzip -q -o -d "${prefix}/bin" "${uniget_cache_download}/${filename}"

"${prefix}/bin/procs" --gen-completion-out bash >"${prefix}/share/bash-completion/completions/procs"
"${prefix}/bin/procs" --gen-completion-out fish >"${prefix}/share/fish/vendor_completions.d/procs.fish"
"${prefix}/bin/procs" --gen-completion-out zsh >"${prefix}/share/zsh/vendor-completions/_procs"
EOF
