#syntax=docker/dockerfile:1.7.1

FROM ghcr.io/uniget-org/images/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]

ARG name
ARG version

RUN <<EOF
check-github-release-asset "CycloneDX/cyclonedx-cli" "v${version}" "cyclonedx-linux-x64"
curl --silent --show-error --location --fail --output "${prefix}/bin/cyclonedx-cli" \
    "https://github.com/CycloneDX/cyclonedx-cli/releases/download/v${version}/cyclonedx-linux-x64"
chmod +x "${prefix}/bin/cyclonedx-cli"
EOF