#syntax=docker/dockerfile

FROM ghcr.io/uniget-org/tools/bun:latest AS bun

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=bun / /usr/local/
WORKDIR /uniget_bootstrap/libexec/redai
ARG name
ARG version
RUN <<EOF
bun install "@kpolley/redai@${version}"
ln --symbolic --relative --force "${prefix}/libexec/redai/node_modules/.bin/redai" "${prefix}/bin/"
EOF