#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM ghcr.io/uniget-org/tools/bun:latest AS bun

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:b0b654de801604e256237f2c27a907a4b61b59ebd83423ad0e0e465c0a3ba9cd AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=bun / /usr/local/
WORKDIR /uniget_bootstrap/libexec/redai
ARG name
ARG version
RUN <<EOF
bun install "@kpolley/redai@${version}"
ln --symbolic --relative --force "${prefix}/libexec/redai/node_modules/.bin/redai" "${prefix}/bin/"
EOF


FROM scratch
COPY --from=prepare /uniget_bootstrap /
