#syntax=docker/dockerfile:1.14.0@sha256:0232be24407cc42c983b9b269b1534a3b98eea312aad9464dd0f1a9e547e15a7

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
WORKDIR /tmp/geist-font
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/vercel/geist-font/releases/download/${version}/Geist-${version}.zip"
filename="$(basename "${url}")"
check-github-release-asset "vercel/geist-font" "${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"
unzip -t "${uniget_cache_download}/${filename}"
unzip -q -o "${uniget_cache_download}/${filename}"

url="https://github.com/vercel/geist-font/releases/download/${version}/GeistMono-${version}.zip"
filename="$(basename "${url}")"
check-github-release-asset "vercel/geist-font" "${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"
unzip -t "${uniget_cache_download}/${filename}"
unzip -q -o "${uniget_cache_download}/${filename}"

mkdir -p \
    "${prefix}/share/geist-font" \
    "${prefix}/share/fonts/geist-font"
find "Geist" "GeistMono" -type f \( -name \*.woff2 -or -name \*.otf -or -name \*.ttf \) -exec cp {} "${prefix}/share/geist-font/" \;
EOF
