#syntax=docker/dockerfile:1.23.0@sha256:2780b5c3bab67f1f76c781860de469442999ed1a0d7992a5efdf2cffc0e3d769

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:99a2bccd1ad68bfc5b1d1eb356cf54b7dd94e45c5216b89c87b9e21c70e12b9f AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
WORKDIR /tmp/geist-font
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/vercel/geist-font/releases/download/${version}/geist-font-${version}.zip"
filename="$(basename "${url}")"
check-github-release-asset "vercel/geist-font" "${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"
unzip -t "${uniget_cache_download}/${filename}"
unzip -q -o "${uniget_cache_download}/${filename}"

mkdir -p \
    "${prefix}/share/geist-font" \
    "${prefix}/share/fonts/geist-font"
find "geist-font-${version}" -type f \( -name \*.woff2 -or -name \*.otf -or -name \*.ttf \) -exec cp {} "${prefix}/share/geist-font/" \;
EOF
