#syntax=docker/dockerfile:1.15.1@sha256:9857836c9ee4268391bb5b09f9f157f3c91bb15821bb77969642813b0d00518d

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/terraform-docs/terraform-docs/releases/download/v${version}/terraform-docs-v${version}-linux-${alt_arch}.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "terraform-docs/terraform-docs" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin/" --no-same-owner \
    terraform-docs

"${prefix}/bin/terraform-docs" completion bash >"${prefix}/share/bash-completion/completions/terraform-docs"
"${prefix}/bin/terraform-docs" completion fish >"${prefix}/share/fish/vendor_completions.d/terraform-docs.fish"
"${prefix}/bin/terraform-docs" completion zsh >"${prefix}/share/zsh/vendor-completions/_terraform-docs"
EOF