#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:b0b654de801604e256237f2c27a907a4b61b59ebd83423ad0e0e465c0a3ba9cd AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version

RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/plumber-cd/terraform-backend-git/releases/download/v${version}/terraform-backend-git-linux-${alt_arch}"
filename="$( basename "${url}" )"

check-github-release-asset "plumber-cd/terraform-backend-git" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/terraform-backend-git"


"${prefix}/bin/terraform-backend-git" completion bash >"${prefix}/share/bash-completion/completions/terraform-backend-git"
"${prefix}/bin/terraform-backend-git" completion fish >"${prefix}/share/fish/vendor_completions.d/terraform-backend-git.fish"
"${prefix}/bin/terraform-backend-git" completion zsh >"${prefix}/share/zsh/vendor-completions/_terraform-backend-git"
EOF