#syntax=docker/dockerfile:1.13.0@sha256:93bfd3b68c109427185cd78b4779fc82b484b0b7618e36d0f104d4d801e66d25

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version

RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/plumber-cd/terraform-backend-git/releases/download/v${version}/terraform-backend-git-linux-${alt_arch}"
filename="$( basename "${url}" )"

check-github-release-asset "plumber-cd/terraform-backend-git" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/terraform-backend-git"


"${prefix}/bin/terraform-backend-git" completion bash >"${prefix}/share/bash-completion/completions/terraform-backend-git"
"${prefix}/bin/terraform-backend-git" completion fish >"${prefix}/share/fish/vendor_completions.d/terraform-backend-git.fish"
"${prefix}/bin/terraform-backend-git" completion zsh >"${prefix}/share/zsh/vendor-completions/_terraform-backend-git"
EOF