#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/derailed/k9s/releases/download/v${version}/k9s_Linux_${alt_arch}.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "derailed/k9s" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin" --no-same-owner \
    k9s
EOF
RUN <<EOF
mkdir -p "${prefix}/share/k9s/skins"
curl --silent --show-error --location --fail "https://github.com/derailed/k9s/archive/refs/tags/v${version}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/share/k9s/skins" --strip-components=2 --no-same-owner \
    "k9s-${version}/skins/"
EOF
RUN <<EOF
"${prefix}/bin/k9s" completion bash >"${prefix}/share/bash-completion/completions/k9s"
"${prefix}/bin/k9s" completion fish >"${prefix}/share/fish/vendor_completions.d/k9s.fish"
"${prefix}/bin/k9s" completion zsh >"${prefix}/share/zsh/vendor-completions/_k9s"
EOF