#syntax=docker/dockerfile:1.21.0@sha256:26147acbda4f14c5add9946e2fd2ed543fc402884fd75146bd342a7f6271dc1d

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/jetify-com/devbox/releases/download/${version}/devbox_${version}_linux_${alt_arch}.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "jetify-com/devbox" "${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin/" --no-same-owner

"${prefix}/bin/devbox" completion bash >"${prefix}/share/bash-completion/completions/devbox"
"${prefix}/bin/devbox" completion fish >"${prefix}/share/fish/vendor_completions.d/devbox.fish"
"${prefix}/bin/devbox" completion zsh >"${prefix}/share/zsh/vendor-completions/_devbox"
EOF