#syntax=docker/dockerfile:1.8.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:6ff62e5ed6b1c33f0ae1644692a354281534a37ec4d752cf480850e19a94d16d AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "jetify-com/devbox" "${version}" "devbox_${version}_linux_${alt_arch}.tar.gz"
curl --silent --show-error --location --fail "https://github.com/jetify-com/devbox/releases/download/${version}/devbox_${version}_linux_${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/bin/" --no-same-owner

"${prefix}/bin/devbox" completion bash >"${prefix}/share/bash-completion/completions/devbox"
"${prefix}/bin/devbox" completion fish >"${prefix}/share/fish/vendor_completions.d/devbox.fish"
"${prefix}/bin/devbox" completion zsh >"${prefix}/share/zsh/vendor-completions/_devbox"
EOF