#syntax=docker/dockerfile:1.10.0@sha256:865e5dd094beca432e8c0a1d5e1c465db5f998dca4e439981029b3b81fb39ed5

FROM ghcr.io/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "openSUSE/catatonit" "v${version}" "catatonit.${arch}"
curl --silent --show-error --location --fail --output "${prefix}/bin/catatonit" \
    "https://github.com/openSUSE/catatonit/releases/download/v${version}/catatonit.${arch}"
chmod +x "${prefix}/bin/catatonit"
EOF