#syntax=docker/dockerfile:1.24.0@sha256:2780b5c3bab67f1f76c781860de469442999ed1a0d7992a5efdf2cffc0e3d769

FROM ghcr.io/uniget-org/tools/go:latest AS go
FROM ghcr.io/uniget-org/tools/make:latest AS make
FROM ghcr.io/uniget-org/tools/go-md2man:latest AS go-md2man

FROM registry.gitlab.com/uniget-org/images/build-base:3.23@sha256:b3f7e2f78a9eda4260453779505b7054d137bf5c136dead92fc8e9240eb00835 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
RUN --mount=type=cache,target=/var/cache/apk <<EOF
apk update
apk add --update-cache \
    bats \
    libassuan-dev \
    libassuan-static \
    libapparmor-dev \
    glib-dev \
    glib-static \
    gpgme-dev \
    libgpg-error-dev \
    libgpg-error-static \
    libseccomp-dev \
    libseccomp-static \
    libselinux-dev \
    sqlite-dev \
    sqlite-static
EOF
COPY --link --from=go / /usr/local/
COPY --link --from=make / /usr/local/
COPY --from=go-md2man / /usr/local/
WORKDIR /tmp/buildah
ARG name
ARG version
RUN git clone --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/containers/buildah .
ENV CFLAGS='-static -pthread' \
    LDFLAGS='-s -w -static-libgcc -static' \
    EXTRA_LDFLAGS='-s -w -linkmode external -extldflags "-static -lm -lgpgme -lgpg-error -lassuan"' \
    BUILDTAGS='static netgo osusergo exclude_graphdriver_btrfs exclude_graphdriver_devicemapper seccomp apparmor selinux' \
    CGO_ENABLED=1
RUN <<EOF
make -j$(nproc) bin/buildah
make -C docs -j$(nproc) GOMD2MAN=go-md2man
mkdir -p /usr/local/share/bash-completion/completions
cp contrib/completions/bash/buildah /usr/local/share/bash-completion/completions/
make install DESTDIR="${prefix}" PREFIX=""
EOF