#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:b0b654de801604e256237f2c27a907a4b61b59ebd83423ad0e0e465c0a3ba9cd AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
case "${alt_arch}" in
    amd64)
        export arch_suffix="x86_64-unknown-linux-gnu"
        ;;
    arm64)
        export arch_suffix="aarch64-unknown-linux-gnu"
        ;;
    *)
        echo "ERROR: Unsupported architecture (${alt_arch})."
        exit 1
        ;;
esac
echo "    Using ${arch_suffix}"

url="https://github.com/medialab/xan/releases/download/${version}/xan-${arch_suffix}.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "medialab/xan" "${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tempdir="$( mktemp -d )"
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${tempdir}" --no-same-owner
install --mode=0755 \
    "$( find "${tempdir}" -type f -name xan | head -n1 )" \
    "${prefix}/bin/xan"
EOF
