#syntax=docker/dockerfile:1.8.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:dc6c0030ff36d8c83922c5c24088c89faf3cb4f0b21540e231f35408453b76c3 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]

ARG name
ARG version

RUN <<EOF
check-github-release-asset "firecracker-microvm/firecracker" "v${version}" "firecracker-v${version}-${arch}.tgz"
curl --silent --show-error --location --fail "https://github.com/firecracker-microvm/firecracker/releases/download/v${version}/firecracker-v${version}-${arch}.tgz" \
| tar --extract --gzip --directory="${prefix}/bin" --strip-components=1 --no-same-owner \
    release-v${version}-${arch}/firecracker-v${version}-${arch} \
    release-v${version}-${arch}/jailer-v${version}-${arch} \
    release-v${version}-${arch}/seccompiler-bin-v${version}-${arch}
mv "${prefix}/bin/firecracker-v${version}-${arch}"     "${prefix}/bin/firecracker"
mv "${prefix}/bin/jailer-v${version}-${arch}"          "${prefix}/bin/jailer"
mv "${prefix}/bin/seccompiler-bin-v${version}-${arch}" "${prefix}/bin/seccompiler-bin"
EOF