#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:b0b654de801604e256237f2c27a907a4b61b59ebd83423ad0e0e465c0a3ba9cd AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/rclone/rclone/releases/download/v${version}/rclone-v${version}-linux-${alt_arch}.zip"
filename="$(basename "${url}")"

check-github-release-asset "rclone/rclone" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

unzip -q -o -d "${prefix}/bin" "${uniget_cache_download}/${filename}"
mv "${prefix}/bin/rclone-v${version}-linux-${alt_arch}/rclone" "${prefix}/bin/"
mv "${prefix}/bin/rclone-v${version}-linux-${alt_arch}/rclone.1" "${prefix}/share/man/man1/"
rm -rf "${prefix}/bin/rclone-v${version}-linux-${alt_arch}"
EOF
RUN <<EOF
"${prefix}/bin/rclone" completion bash - >"${prefix}/share/bash-completion/completions/rclone"
"${prefix}/bin/rclone" completion fish - >"${prefix}/share/fish/vendor_completions.d/rclone.fish"
"${prefix}/bin/rclone" completion zsh - >"${prefix}/share/zsh/vendor-completions/_rclone"
EOF