#syntax=docker/dockerfile

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
echo "### Setting architecture string for ${TARGETPLATFORM}"
case "${arch}" in
    x86_64)
        export arch_suffix="x86_64"
        ;;
    aarch64)
        export arch_suffix="arm64"
        ;;
    *)
        echo "ERROR: Unsupported architecture ${arch}."
        exit 1
        ;;
esac
echo "    Using ${arch_suffix}"

url="https://github.com/smol-machines/smolvm/releases/download/v${version}/smolvm-${version}-linux-${arch_suffix}.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "smol-machines/smolvm" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
mkdir -p "${prefix}/opt/smolvm/"
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/opt/smolvm/" --strip-components=1 --no-same-owner
ln --symbolic --relative --force "${prefix}/opt/smolvm/smolvm" "${prefix}/bin/"
ln --symbolic --relative --force "${prefix}/opt/smolvm/containerd-shim-smolvm-v2" "${prefix}/bin/"
EOF