#syntax=docker/dockerfile:1.8.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:dc6c0030ff36d8c83922c5c24088c89faf3cb4f0b21540e231f35408453b76c3 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "datreeio/datree" "${version}" "datree-cli_${version}_Linux_${arch}.zip"
curl --silent --show-error --location --fail --remote-name "https://github.com/datreeio/datree/releases/download/${version}/datree-cli_${version}_Linux_${arch}.zip"
unzip -q -o -d "/tmp" "datree-cli_${version}_Linux_${arch}.zip"
rm "datree-cli_${version}_Linux_${arch}.zip"
mv "/tmp/datree" "${prefix}/bin"
"${prefix}/bin/datree" completion bash >"${prefix}/share/bash-completion/completions/datree"
"${prefix}/bin/datree" completion fish >"${prefix}/share/fish/vendor_completions.d/datree.fish"
"${prefix}/bin/datree" completion zsh >"${prefix}/share/zsh/vendor-completions/_datree"
EOF
RUN <<EOF
"${prefix}/bin/datree" config set offline local
EOF