#syntax=docker/dockerfile:1.8.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:dc6c0030ff36d8c83922c5c24088c89faf3cb4f0b21540e231f35408453b76c3 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "little-angry-clouds/kubectl-ssh-proxy" "${version}" "kubectl-ssh-proxy-linux-amd64.tar.gz"
curl --silent --show-error --location --fail "https://github.com/little-angry-clouds/kubectl-ssh-proxy/releases/download/${version}/kubectl-ssh-proxy-linux-amd64.tar.gz" \
| tar --extract --gzip --directory="${prefix}" --no-same-owner
mv "${prefix}/bin/kubectl-ssh_proxy-linux-amd64" "${prefix}/bin/kubectl-ssh_proxy"
mv "${prefix}/bin/kube-ssh-proxy-ssh-bin-linux-amd64" "${prefix}/bin/kube-ssh-proxy-ssh-bin"
EOF