#syntax=docker/dockerfile:1.7.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:98429d8ee1c7cf7d06f65b692870d983f0965f1c1cdffa1dd04ef878b56293b6 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "little-angry-clouds/kubectl-ssh-proxy" "${version}" "kubectl-ssh-proxy-linux-amd64.tar.gz"
curl --silent --location --fail "https://github.com/little-angry-clouds/kubectl-ssh-proxy/releases/download/${version}/kubectl-ssh-proxy-linux-amd64.tar.gz" \
| tar --extract --gzip --directory="${prefix}" --no-same-owner
mv "${prefix}/bin/kubectl-ssh_proxy-linux-amd64" "${prefix}/bin/kubectl-ssh_proxy"
mv "${prefix}/bin/kube-ssh-proxy-ssh-bin-linux-amd64" "${prefix}/bin/kube-ssh-proxy-ssh-bin"
EOF