#syntax=docker/dockerfile:1.24.0@sha256:87999aa3d42bdc6bea60565083ee17e86d1f3339802f543c0d03998580f9cb89

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:99a2bccd1ad68bfc5b1d1eb356cf54b7dd94e45c5216b89c87b9e21c70e12b9f AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/k0sproject/k0sctl/releases/download/v${version}/k0sctl-linux-${alt_arch}"
filename="$( basename "${url}" )"

check-github-release-asset "k0sproject/k0sctl" "v${version}" "${filename}"
check-github-release-asset "k0sproject/k0sctl" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/k0sctl"

"${prefix}/bin/k0sctl" completion bash >"${prefix}/share/bash-completion/completions/k0sctl"
"${prefix}/bin/k0sctl" completion fish >"${prefix}/share/fish/vendor_completions.d/k0sctl.fish"
"${prefix}/bin/k0sctl" completion zsh >"${prefix}/share/zsh/vendor-completions/_k0sctl"
EOF