#syntax=docker/dockerfile:1.7.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:98429d8ee1c7cf7d06f65b692870d983f0965f1c1cdffa1dd04ef878b56293b6 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "etcd-io/etcd" "v${version}" "etcd-v${version}-linux-${alt_arch}.tar.gz"
curl --silent --location --fail "https://github.com/etcd-io/etcd/releases/download/v${version}/etcd-v${version}-linux-${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/bin" --strip-components=1 --no-same-owner \
    etcd-v${version}-linux-${alt_arch}/etcd \
    etcd-v${version}-linux-${alt_arch}/etcdctl
EOF