#syntax=docker/dockerfile:1.17.0@sha256:e63addfe27b10e394a5f9f1e866961adc70d08573f1cb80f8d1a0999347b3553

FROM registry.gitlab.com/uniget-org/images/build-base:3.21 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
RUN --mount=type=cache,target=/var/cache/apk <<EOF
apk add --update-cache \
    jemalloc-dev \
    openssl-dev \
    openssl-libs-static
EOF
WORKDIR /tmp/redis
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/redis/redis/archive/refs/tags/${version}.tar.gz"
filename="$(basename "${url}")"

check-download "${url}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --strip-components=1

make -j$(nproc) \
    BUILD_TLS=yes \
    CFLAGS="-static" \
    LDFLAGS="-static"
make install \
    PREFIX="${prefix}" \
    prefix=""
EOF