#syntax=docker/dockerfile:1.14.0@sha256:426b85b823c113372f766a963f68cfd9cd4878e1bcc0fda58779127ee98a28eb

FROM registry.gitlab.com/uniget-org/images/build-base:3.20 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
RUN --mount=type=cache,target=/var/cache/apk <<EOF
apk add --update-cache \
    jemalloc-dev \
    openssl-dev \
    openssl-libs-static
EOF
WORKDIR /tmp/redis
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/redis/redis/archive/refs/tags/${version}.tar.gz"
filename="$(basename "${url}")"

check-download "${url}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --strip-components=1

make -j$(nproc) \
    BUILD_TLS=yes \
    CFLAGS="-static" \
    LDFLAGS="-static"
make install \
    PREFIX="${prefix}" \
    prefix=""
EOF