#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/ducaale/xh/releases/download/v${version}/xh-v${version}-${arch}-unknown-linux-musl.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "ducaale/xh" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin/" --strip-components=1 --no-same-owner \
    "xh-v${version}-${arch}-unknown-linux-musl/xh" \
    "xh-v${version}-${arch}-unknown-linux-musl/completions" \
    "xh-v${version}-${arch}-unknown-linux-musl/doc/xh.1"
mv "${prefix}/bin/completions/xh.bash" "${prefix}/share/bash-completion/completions/xh"
mv "${prefix}/bin/completions/xh.fish" "${prefix}/share/fish/vendor_completions.d/xh.fish"
mv "${prefix}/bin/completions/_xh"     "${prefix}/share/zsh/vendor-completions/_xh"
mv "${prefix}/bin/doc/xh.1" "${prefix}/share/man/man1/"
rm -rf \
    "${prefix}/bin/completions" \
    "${prefix}/bin/doc"
EOF