#syntax=docker/dockerfile:1.21.0@sha256:27f9262d43452075f3c410287a2c43f5ef1bf7ec2bb06e8c9eeb1b8d453087bc

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/tektoncd/cli/releases/download/v${version}/tkn_${version}_Linux_x86_64.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "tektoncd/cli" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin/" --no-same-owner \
    tkn
"${prefix}/bin/tkn" completion bash >"${prefix}/share/bash-completion/completions/tkn"
"${prefix}/bin/tkn" completion fish >"${prefix}/share/fish/vendor_completions.d/tkn.fish"
"${prefix}/bin/tkn" completion zsh >"${prefix}/share/zsh/vendor-completions/_tkn"
ln -s "${prefix}/bin/tkn" "${prefix}/bin/kubectl-tkn"
EOF

RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/tektoncd/cli/archive/refs/tags/v${version}.tar.gz"
filename="$( basename "${url}" )"

check-download "${url}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/share/man/man1/" --strip-components=4 --no-same-owner \
    "cli-${version}/docs/man/man1/"
EOF