#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:059b11407572b2fd733e7bcd1c528852394d7fe1abef7119a1a97356983cab76 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/moby/buildkit/releases/download/v${version}/buildkit-v${version}.linux-${alt_arch}.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "moby/buildkit" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin" --strip-components=1 --no-same-owner

curl --silent --show-error --location --fail --output "${prefix}/etc/systemd/system/buildkit.service.go-template" \
    "https://github.com/moby/buildkit/raw/v${version}/examples/systemd/system/buildkit.service"
sed -i -E 's|^ExecStart=/usr/local/bin/buildkitd|ExecStart={{ .Target }}/bin/buildkitd|' "${prefix}/etc/systemd/system/buildkit.service.go-template"

curl --silent --show-error --location --fail --output "${prefix}/etc/systemd/system/buildkit.socket" \
    "https://github.com/moby/buildkit/raw/v${version}/examples/systemd/system/buildkit.socket"
EOF