#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM ghcr.io/uniget-org/tools/make:latest AS make
FROM ghcr.io/uniget-org/tools/go:latest AS go

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:b0b654de801604e256237f2c27a907a4b61b59ebd83423ad0e0e465c0a3ba9cd AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=go / /usr/local/
COPY --link --from=make / /usr/local/
WORKDIR /go/src/github.com/wolfi-dev/wolfictl
ARG name
ARG version
RUN --mount=type=cache,target=/root/go/pkg/mod <<EOF
check-clone "https://github.com/wolfi-dev/wolfictl" "v${version}"
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/wolfi-dev/wolfictl .
go install golang.org/x/tools/cmd/goimports@latest
make wolfictl
make install DESTDIR="${prefix}" PREFIX=""

"${prefix}/bin/wolfictl" completion bash >"${prefix}/share/bash-completion/completions/wolfictl"
"${prefix}/bin/wolfictl" completion fish >"${prefix}/share/fish/vendor_completions.d/wolfictl.fish"
"${prefix}/bin/wolfictl" completion zsh >"${prefix}/share/zsh/vendor-completions/_wolfictl"
EOF