#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:059b11407572b2fd733e7bcd1c528852394d7fe1abef7119a1a97356983cab76 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
curl --silent --show-error --location --fail --output "${prefix}/etc/profile.d/forgit.sh" \
    "https://github.com/wfxr/forgit/raw/refs/tags/${version}/bin/git-forgit"

mkdir -p "${prefix}/share/forgit"
curl --silent --show-error --location --fail --output "${prefix}/share/forgit/forgit.plugin.fish" \
    "https://github.com/wfxr/forgit/raw/refs/tags/${version}/conf.d/forgit.plugin.fish"
curl --silent --show-error --location --fail --output "${prefix}/share/forgit/forgit.plugin.zsh" \
    "https://github.com/wfxr/forgit/raw/refs/tags/${version}/forgit.plugin.zsh"
ln --relative --symbolic --force "${prefix}/share/forgit/forgit.plugin.zsh" "${prefix}/share/forgit/forgit.plugin.sh"
EOF
RUN <<EOF
curl --silent --show-error --location --fail --output "${prefix}/share/bash-completion/completions/forgit" \
    "https://github.com/wfxr/forgit/raw/refs/tags/${version}/completions/git-forgit.bash"
curl --silent --show-error --location --fail --output "${prefix}/share/fish/vendor_completions.d/forgit.fish" \
    "https://github.com/wfxr/forgit/raw/refs/tags/${version}/completions/git-forgit.fish"
curl --silent --show-error --location --fail --output "${prefix}/share/zsh/vendor-completions/_forgit" \
    "https://github.com/wfxr/forgit/raw/refs/tags/${version}/completions/_git-forgit"
EOF