#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM ghcr.io/uniget-org/tools/go:latest AS go

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
COPY --link --from=go / /usr/local/
WORKDIR /go/src/github.com/docker/mcp-gateway
ARG name
ARG version
RUN --mount=type=cache,target=/root/go/pkg/mod <<EOF
check-clone "https://github.com/docker/mcp-gateway" "v${version}"
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/docker/mcp-gateway .
CGO_ENABLED=0 go build -trimpath -ldflags "-s -w -X github.com/docker/mcp-gateway/cmd/docker-mcp/version.Version=v${version}" -o "${prefix}/libexec/docker/cli-plugins//docker-mcp" ./cmd/docker-mcp
EOF