#syntax=docker/dockerfile:1.16.0@sha256:9857836c9ee4268391bb5b09f9f157f3c91bb15821bb77969642813b0d00518d

FROM ghcr.io/uniget-org/tools/python:latest AS python
FROM ghcr.io/uniget-org/tools/shiv:latest AS shiv

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=python / /usr/local/
COPY --link --from=shiv / /usr/local/
ARG name
ARG version
RUN --mount=type=cache,target=/root/.cache/pip <<EOF
shiv --output-file "${prefix}/bin/http" --console-script http "httpie==${version}"

curl --silent --show-error --location --fail --output "${prefix}/share/bash-completion/completions/http" \
    "https://github.com/httpie/cli/raw/${version}/extras/httpie-completion.bash"
curl --silent --show-error --location --fail --output "${prefix}/share/fish/vendor_completions.d/http.fish" \
    "https://github.com/httpie/cli/raw/${version}/extras/httpie-completion.fish"
EOF