#syntax=docker/dockerfile

FROM ghcr.io/uniget-org/tools/go:latest AS go

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=go / /usr/local/
WORKDIR /go/src/github.com/maaslalani/confetty
ARG name
ARG version
RUN --mount=type=cache,target=/root/go/pkg/mod <<EOF
git clone https://github.com/maaslalani/confetty .
git checkout "${version}"
go get -u ./...
go build -o "${prefix}/bin/confetty" .
EOF