#syntax=docker/dockerfile:1.23.0@sha256:2780b5c3bab67f1f76c781860de469442999ed1a0d7992a5efdf2cffc0e3d769

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:99a2bccd1ad68bfc5b1d1eb356cf54b7dd94e45c5216b89c87b9e21c70e12b9f AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/microsoft/cascadia-code/releases/download/v${version}/CascadiaCode-${version}.zip"
filename="$(basename "${url}")"

check-github-release-asset "microsoft/cascadia-code" "v${version}" "${filename}"

curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

mkdir -p \
    "${prefix}/share/cascadia-code" \
    "${prefix}/share/fonts/cascadia-code"
unzip -t "${uniget_cache_download}/${filename}"
unzip -q -o -d "${prefix}/share/cascadia-code/" "${uniget_cache_download}/${filename}"

find "${prefix}/share/cascadia-code/ttf" -maxdepth 1 -type f -exec cp {} "${prefix}/share/fonts/cascadia-code" \;
EOF