#syntax=docker/dockerfile:1.8.1

FROM ghcr.io/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "google/osv-scanner" "v${version}" "osv-scanner_linux_${alt_arch}"
curl --silent --show-error --location --fail --output "${prefix}/bin/osv-scanner" \
    "https://github.com/google/osv-scanner/releases/download/v${version}/osv-scanner_linux_${alt_arch}"
chmod +x "${prefix}/bin/osv-scanner"
EOF