#syntax=docker/dockerfile:1.14.0@sha256:4c68376a702446fc3c79af22de146a148bc3367e73c25a5803d453b6b3f722fb

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/microsoft/WSL2-Linux-Kernel/archive/refs/tags/linux-msft-wsl-${version}.tar.gz"
filename="$( basename "${url}" )"

check-download "${url}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
mkdir -p "${prefix}/src/linux-${version}-wsl2"
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/src/linux-${version}-wsl2" --strip-components=1 --no-same-owner
EOF
COPY --chmod=0755 \
    install-deps-ubuntu.sh \
    assert-config.sh \
    /uniget_bootstrap/src/linux-${version}-wsl2/