#syntax=docker/dockerfile:1.10.0@sha256:865e5dd094beca432e8c0a1d5e1c465db5f998dca4e439981029b3b81fb39ed5

FROM ghcr.io/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-download "https://github.com/microsoft/WSL2-Linux-Kernel/archive/refs/tags/linux-msft-wsl-${version}.tar.gz"
mkdir -p "${prefix}/src/linux-${version}-wsl2"
cd "${prefix}/src/linux-${version}-wsl2"
curl --silent --show-error --location --fail "https://github.com/microsoft/WSL2-Linux-Kernel/archive/refs/tags/linux-msft-wsl-${version}.tar.gz" \
| tar --extract --gzip --strip-components=1 --no-same-owner
EOF
COPY --chmod=0755 \
    install-deps-ubuntu.sh \
    assert-config.sh \
    /uniget_bootstrap/src/linux-${version}-wsl2/