#syntax=docker/dockerfile:1.25.0@sha256:0adf442eae370b6087e08edc7c50b552d80ddf261576f4ebd6421006b2461f12

FROM ghcr.io/uniget-org/tools/go-md2man:latest AS go-md2man

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:cc8b2a023c3777e8b654c98d4bebc58827f8fcb73c4ce309d9ffa01b432954a9 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=go-md2man / /usr/local/
ARG name
ARG version
RUN <<EOF
for file in \
    Containerfile.5 \
    containerignore.5 \
    containers-mounts.conf.5 \
    containers.conf.5; do

    echo "Processing manpage ${file}..."
    curl --silent --show-error --location --fail --remote-name "https://github.com/containers/common/raw/main/docs/${file}.md"
    go-md2man -in "${file}.md" -out "${prefix}/share/man/man5/${file}"
    rm "${file}.md"
done
EOF
COPY policy.json /uniget_bootstrap/etc/containers/
COPY shortnames.conf /uniget_bootstrap/etc/containers/registries.conf.d/
COPY containers.conf /uniget_bootstrap/share/containers/
COPY seccomp.json /uniget_bootstrap/share/containers/