#syntax=docker/dockerfile:1.17.0@sha256:e63addfe27b10e394a5f9f1e866961adc70d08573f1cb80f8d1a0999347b3553

FROM ghcr.io/uniget-org/tools/go:latest AS go
FROM ghcr.io/uniget-org/tools/make:latest AS make

FROM registry.gitlab.com/uniget-org/images/build-base:3.21 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
RUN --mount=type=cache,target=/var/cache/apk <<EOF
apk add --update-cache \
    libseccomp-dev \
    libseccomp-static
EOF
COPY --link --from=go / /usr/local/
COPY --link --from=make / /usr/local/
WORKDIR /go/src/github.com/rootless-containers/bypass4netns
ARG name
ARG version
RUN <<EOF
check-clone "https://github.com/rootless-containers/bypass4netns" "v${version}"

git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/rootless-containers/bypass4netns .
make -j$(nproc) static
cp bypass4netns "${prefix}/bin/"
cp bypass4netnsd "${prefix}/bin/"
EOF