#syntax=docker/dockerfile

FROM ghcr.io/uniget-org/tools/rust:latest AS rust

FROM registry.gitlab.com/uniget-org/images/build-essential:26.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=rust / /usr/local/
WORKDIR /tmp/github.com/YS-L/csvlens
ARG name
ARG version
RUN --mount=type=cache,target=/target \
    --mount=type=cache,target=/usr/local/cargo/registry <<EOF
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/YS-L/csvlens .
export CARGO_HOME=/usr/local/cargo
export CARGO_TARGET_DIR=/target
export RUSTUP_HOME=/usr/local/rustup
cargo build --release --target "${arch}-unknown-linux-musl"
cp "/target/${arch}-unknown-linux-musl/release/csvlens" "${prefix}/bin/"
EOF