#syntax=docker/dockerfile:1.8.1

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:178a01206383923b589ecfe3bace55431c4b8528086909ffcdc1ef88de4da10f AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
echo "### Setting architecture string for ${TARGETPLATFORM}"
case "${arch}" in
    x86_64)
        export arch_suffix="${alt_arch}"
        ;;
    aarch64)
        export arch_suffix="${arch}"
        ;;
    *)
        echo "ERROR: Unsupported architecture ${arch}."
        exit 1
        ;;
esac
echo "    Using ${arch_suffix}"

check-github-release-asset "fermyon/spin" "v${version}" "spin-v${version}-linux-${arch_suffix}.tar.gz"
curl --silent --show-error --location --fail "https://github.com/fermyon/spin/releases/download/v${version}/spin-v${version}-static-linux-${arch_suffix}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/bin/" --no-same-owner \
    spin
EOF