#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM ghcr.io/uniget-org/tools/rust:latest AS rust

FROM registry.gitlab.com/uniget-org/images/build-essential:26.04@sha256:5ee01cd64296e795943405f10d803592dbd27cad7d35cd6ee1271bf177a71146 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=rust / /usr/local/
RUN <<EOF
apt-get update
apt-get install -y --no-install-recommends \
    libjitterentropy-dev \
    libzstd-dev \
    libssl-dev
EOF
WORKDIR /tmp/codeberg.org/forgejo-contrib/forgejo-cli
ARG name
ARG version
RUN <<EOF
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://codeberg.org/forgejo-contrib/forgejo-cli .
export CARGO_HOME=/usr/local/cargo
export RUSTUP_HOME=/usr/local/rustup
export RUSTFLAGS='-C target-feature=+crt-static'
cargo build --release --target "${arch}-unknown-linux-gnu"
cp "target/${arch}-unknown-linux-gnu/release/fj" "${prefix}/bin/"
EOF
RUN <<EOF
"${prefix}/bin/fj" completion bash >"${prefix}/share/bash-completion/completions/fj"
"${prefix}/bin/fj" completion fish >"${prefix}/share/fish/vendor_completions.d/fj.fish"
"${prefix}/bin/fj" completion zsh >"${prefix}/share/zsh/vendor-completions/_fj"
EOF