#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM ghcr.io/uniget-org/tools/rust:latest AS rust

FROM registry.gitlab.com/uniget-org/images/build-essential:26.04@sha256:bf6f96f242e6a61f634a1c1a988bfcda070b843bbd613fbdec92238a5b5f93ce AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=rust / /usr/local/
RUN <<EOF
apt-get update
apt-get install -y --no-install-recommends \
    libssl-dev
EOF
WORKDIR /tmp/codeberg.org/forgejo-contrib/forgejo-cli
ARG name
ARG version
RUN <<EOF
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://codeberg.org/forgejo-contrib/forgejo-cli .
export CARGO_HOME=/usr/local/cargo
export RUSTUP_HOME=/usr/local/rustup
export RUSTFLAGS='-C target-feature=+crt-static'
cargo build --release --target "${arch}-unknown-linux-gnu"
cp "target/${arch}-unknown-linux-gnu/release/fj" "${prefix}/bin/"
EOF
RUN <<EOF
"${prefix}/bin/fj" completion bash >"${prefix}/share/bash-completion/completions/fj"
"${prefix}/bin/fj" completion fish >"${prefix}/share/fish/vendor_completions.d/fj.fish"
"${prefix}/bin/fj" completion zsh >"${prefix}/share/zsh/vendor-completions/_fj"
EOF