#syntax=docker/dockerfile

FROM rust:alpine AS build
RUN <<EOF
apk update
apk add \
    build-base \
    git \
    bash \
    jitterentropy-library-dev \
    zstd-dev \
    openssl-dev \
    openssl-libs-static
EOF
WORKDIR /tmp/codeberg.org/forgejo-contrib/forgejo-cli
ARG version
RUN <<EOF
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://codeberg.org/forgejo-contrib/forgejo-cli .
cargo build --release --target "$(uname -m)-unknown-linux-musl"
cp "target/$(uname -m)-unknown-linux-musl/release/fj" "/usr/local/bin/"
EOF

FROM registry.gitlab.com/uniget-org/images/alpine:3.24 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --from=build "/usr/local/bin/fj" "/uniget_bootstrap/bin/"
RUN <<EOF
"${prefix}/bin/fj" completion bash >"${prefix}/share/bash-completion/completions/fj"
"${prefix}/bin/fj" completion fish >"${prefix}/share/fish/vendor_completions.d/fj.fish"
"${prefix}/bin/fj" completion zsh >"${prefix}/share/zsh/vendor-completions/_fj"
EOF