#syntax=docker/dockerfile:1.21.0@sha256:27f9262d43452075f3c410287a2c43f5ef1bf7ec2bb06e8c9eeb1b8d453087bc

FROM registry.gitlab.com/uniget-org/images/build-base:3.23@sha256:d7cab8026e4d67fc0a7d22c33bcc9246cc29c29a78757c3008e3fc821a4f665b AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
RUN --mount=type=cache,target=/var/cache/apk <<EOF
apk update
apk add --update-cache \
    cmake \
    clang
EOF
WORKDIR /tmp/fastgron
ARG name
ARG version
RUN <<EOF
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/adamritter/fastgron .
cmake -B build \
    -DCMAKE_CXX_COMPILER=/usr/bin/clang++ \
    -DCMAKE_EXE_LINKER_FLAGS=-static
cmake --build build
cp build/fastgron "${prefix}/bin/"
EOF