#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM ghcr.io/uniget-org/tools/go:latest AS go
FROM ghcr.io/uniget-org/tools/make:latest AS make

FROM registry.gitlab.com/uniget-org/images/build-base:3.24@sha256:6c6c414a06d0c48a6a05e1b3fe6940529179f7ed617dccbbcf4f2424383b1014 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=go / /usr/local/
COPY --link --from=make / /usr/local/
WORKDIR /go/src/github.com/goccy/go-graphviz
ARG name
ARG version
RUN --mount=type=cache,target=/root/go/pkg/mod <<EOF
check-clone https://github.com/goccy/go-graphviz "v${version}"
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/goccy/go-graphviz .
cd cmd/dot
go build -ldflags '-extldflags "-static"' -o "${prefix}/bin/dot" .
EOF