#syntax=docker/dockerfile:1.9.0@sha256:fe40cf4e92cd0c467be2cfc30657a680ae2398318afd50b0c80585784c604f28

FROM ghcr.io/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "microsoft/sbom-tool" "v${version}" "sbom-tool-linux-x64"
curl --silent --show-error --location --fail --output "${prefix}/bin/sbom-tool" \
    "https://github.com/microsoft/sbom-tool/releases/download/v${version}/sbom-tool-linux-x64"
chmod +x "${prefix}/bin/sbom-tool"
EOF