#syntax=docker/dockerfile:1.8.1

FROM ghcr.io/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]

ARG name
ARG version

RUN <<EOF
check-github-release-asset "rupor-github/wsl-ssh-agent" "v${version}" "wsl-ssh-agent.zip"
curl --silent --show-error --location --fail --remote-name "https://github.com/rupor-github/wsl-ssh-agent/releases/download/v${version}/wsl-ssh-agent.zip"
unzip -q -o -d "/tmp" "wsl-ssh-agent.zip"
rm "wsl-ssh-agent.zip"
mv "/tmp/npiperelay.exe" "${prefix}/bin"
mv "/tmp/wsl-ssh-agent-gui.exe" "${prefix}/bin"
EOF
COPY wsl-ssh-agent-forward.sh /uniget_bootstrap/etc/profile.d/