#syntax=docker/dockerfile:1.10.0@sha256:865e5dd094beca432e8c0a1d5e1c465db5f998dca4e439981029b3b81fb39ed5

FROM ghcr.io/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "open-component-model/ocm" "v${version}" "ocm-${version}-linux-${alt_arch}.tar.gz"
curl --silent --show-error --location --fail "https://github.com/open-component-model/ocm/releases/download/v${version}/ocm-${version}-linux-${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/bin/" --no-same-owner

"${prefix}/bin/ocm" completion bash >"${prefix}/share/bash-completion/completions/ocm"
"${prefix}/bin/ocm" completion fish >"${prefix}/share/fish/vendor_completions.d/ocm.fish"
"${prefix}/bin/ocm" completion zsh >"${prefix}/share/zsh/vendor-completions/_ocm"
EOF