#syntax=docker/dockerfile:1.6.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:da13a27933fac882122e16292dad3e4869a53dbbc52a73b4a5ddfbcde6902a99 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "ogham/exa" "v${version}" "exa-linux-${arch}-v${version}.zip"
url="https://github.com/ogham/exa/releases/download/v${version}/exa-linux-${arch}-v${version}.zip"
filename="$(basename "${url}")"
curl --silent --location --fail --remote-name "${url}"
unzip -q -o -d "/tmp" "${filename}"

mv /tmp/bin/exa "${prefix}/bin/"
mv /tmp/man/exa.1 "${prefix}/share/man/man1/"
mv /tmp/man/exa_colors.5 "${prefix}/share/man/man5/"
mv /tmp/completions/exa.bash "${prefix}/share/bash-completion/completions/exa"
mv /tmp/completions/exa.fish "${prefix}/share/fish/vendor_completions.d/exa.fish"
mv /tmp/completions/exa.zsh  "${prefix}/share/zsh/vendor-completions/_exa"
EOF