#syntax=docker/dockerfile:1.7.1

FROM ghcr.io/uniget-org/images/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "grafana/loki" "v${version}" "logcli-linux-${alt_arch}.zip"
url="https://github.com/grafana/loki/releases/download/v${version}/logcli-linux-${alt_arch}.zip"
filename="$(basename "${url}")"
curl --silent --location --fail --remote-name "${url}"
unzip -q -o -d "${prefix}/bin" "${filename}"
mv "${prefix}/bin/logcli-linux-${alt_arch}" "${prefix}/bin/logcli"
"${prefix}/bin/logcli" --completion-script-bash >"${prefix}/share/bash-completion/completions/logcli"
"${prefix}/bin/logcli" --completion-script-zsh >"${prefix}/share/zsh/vendor-completions/_logcli"
EOF