# yaml-language-server: $schema=https://tools.uniget.dev/schema.yaml
name: argo
version: "4.0.1"
check: ${binary} version | grep ^argo | cut -d' ' -f2 | tr -d v
tags:
- type/cli
- kubernetes
- org/cncf
- cicd
- lang/go
- kubernetes
- k8s
homepage: https://argo-workflows.readthedocs.io/
repository: https://github.com/argoproj/argo-workflows
description: Workflow engine for Kubernetes
renovate:
  datasource: github-releases
  package: argoproj/argo-workflows
  extractVersion: ^v(?<version>.+)$
  priority: low
license:
  name: Apache License 2.0
  link: https://github.com/argoproj/argo-workflows/blob/main/LICENSE
