#syntax=docker/dockerfile:1.19.0@sha256:b6afd42430b15f2d2a4c5a02b919e98a525b785b1aaff16747d2f623364e39b6

FROM ghcr.io/uniget-org/tools/make:latest AS make

FROM registry.gitlab.com/uniget-org/images/build-essential:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=make / /usr/local/
WORKDIR /tmp/libjansson
ARG name
ARG version
RUN <<EOF
check-clone "https://github.com/akheron/jansson" "v${version}"
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/akheron/jansson .
autoreconf -i
./configure \
    --prefix="${prefix}" \
    --enable-shared \
    --enable-static
make -j$(nproc)
make install
EOF