#syntax=docker/dockerfile:1.8.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:6ff62e5ed6b1c33f0ae1644692a354281534a37ec4d752cf480850e19a94d16d AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
case "${alt_arch}" in
    amd64)
        export arch_suffix="${arch}"
        ;;
    arm64)
        export arch_suffix="${alt_arch}"
        ;;
    *)
        echo "ERROR: Unsupported architecture (${alt_arch})."
        exit 1
        ;;
esac

check-github-release-asset "parca-dev/parca" "v${version}" "parca_${version}_Linux_${arch_suffix}.tar.gz"
curl --silent --show-error --location --fail "https://github.com/parca-dev/parca/releases/download/v${version}/parca_${version}_Linux_${arch_suffix}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/bin/" --no-same-owner \
    parca
EOF