#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/ddworken/hishtory/releases/download/v${version}/hishtory-linux-${alt_arch}"
filename="$( basename "${url}" )"

check-github-release-asset "ddworken/hishtory" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/hishtory"


check-github-release-asset "ddworken/hishtory" "v${version}" "hishtory-server-linux-${alt_arch}"
curl --silent --show-error --location --fail --output "${prefix}/bin/hishtory-server" \
    "https://github.com/ddworken/hishtory/releases/download/v${version}/hishtory-server-linux-${alt_arch}"
chmod +x "${prefix}/bin/hishtory-server"

"${prefix}/bin/hishtory" completion bash >"${prefix}/share/bash-completion/completions/hishtory"
"${prefix}/bin/hishtory" completion fish >"${prefix}/share/fish/vendor_completions.d/hishtory.fish"
"${prefix}/bin/hishtory" completion zsh >"${prefix}/share/zsh/vendor-completions/_hishtory"
EOF