#syntax=docker/dockerfile:1.17.0@sha256:e63addfe27b10e394a5f9f1e866961adc70d08573f1cb80f8d1a0999347b3553

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/ddworken/hishtory/releases/download/v${version}/hishtory-linux-${alt_arch}"
filename="$( basename "${url}" )"

check-github-release-asset "ddworken/hishtory" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/hishtory"


check-github-release-asset "ddworken/hishtory" "v${version}" "hishtory-server-linux-${alt_arch}"
curl --silent --show-error --location --fail --output "${prefix}/bin/hishtory-server" \
    "https://github.com/ddworken/hishtory/releases/download/v${version}/hishtory-server-linux-${alt_arch}"
chmod +x "${prefix}/bin/hishtory-server"

"${prefix}/bin/hishtory" completion bash >"${prefix}/share/bash-completion/completions/hishtory"
"${prefix}/bin/hishtory" completion fish >"${prefix}/share/fish/vendor_completions.d/hishtory.fish"
"${prefix}/bin/hishtory" completion zsh >"${prefix}/share/zsh/vendor-completions/_hishtory"
EOF