#syntax=docker/dockerfile:1.27.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/jeremylong/DependencyCheck/releases/download/v${version}/dependency-check-${version}-release.zip"
filename="$( basename "${url}" )"

check-github-release-asset "jeremylong/DependencyCheck" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

unzip -t "${uniget_cache_download}/${filename}"
unzip -q -o -d "${prefix}/opt" "${uniget_cache_download}/${filename}"
ln --symbolic --relative --force "/opt/dependency-check/bin/dependency-check.sh" "${prefix}/bin/dependency-check.sh"
mv "${prefix}/opt/dependency-check/bin/completion-for-dependency-check.sh" "${prefix}/share/bash-completion/completions/dependency-check.sh"
EOF