#syntax=docker/dockerfile:1.13.0@sha256:93bfd3b68c109427185cd78b4779fc82b484b0b7618e36d0f104d4d801e66d25

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/jeremylong/DependencyCheck/releases/download/v${version}/dependency-check-${version}-release.zip"
filename="$( basename "${url}" )"

check-github-release-asset "jeremylong/DependencyCheck" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

unzip -t "${uniget_cache_download}/${filename}"
unzip -q -o -d "${prefix}/opt" "${uniget_cache_download}/${filename}"
ln --symbolic --relative --force "/opt/dependency-check/bin/dependency-check.sh" "${prefix}/bin/dependency-check.sh"
mv "${prefix}/opt/dependency-check/bin/completion-for-dependency-check.sh" "${prefix}/share/bash-completion/completions/dependency-check.sh"
EOF