#syntax=docker/dockerfile:1.9.0@sha256:fe40cf4e92cd0c467be2cfc30657a680ae2398318afd50b0c80585784c604f28

FROM nixos/nix:2.24.4@sha256:338ca39c0c75f10919cd0cf38647ce4543033d2bbdabab4519de5adee45445f8 AS build
ARG name
ARG version
WORKDIR /tmp/crun
RUN git clone --config advice.detachedHead=false --depth 1 --recursive --branch "${version}" https://github.com/containers/crun.git .
RUN <<EOF
mkdir -p /usr/local/bin/ /usr/local/share/man/man1/
nix build -f nix --extra-experimental-features nix-command
cp -rfp ./result/bin/crun /usr/local/bin/
cp *.1 /usr/local/share/man/man1/
EOF

FROM ghcr.io/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
COPY --link --from=build /usr/local/bin/ /uniget_bootstrap/bin/
COPY --link --from=build /usr/local/share/man/man1/ /uniget_bootstrap/share/man/man1/