#syntax=docker/dockerfile:1.21.0@sha256:27f9262d43452075f3c410287a2c43f5ef1bf7ec2bb06e8c9eeb1b8d453087bc

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/grafana/agent/releases/download/v${version}/grafana-agent-linux-${alt_arch}.zip"
filename="$(basename "${url}")"
check-github-release-asset "grafana/agent" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"
unzip -t "${uniget_cache_download}/${filename}"
unzip -q -o -d "${prefix}/bin" "${uniget_cache_download}/${filename}"
mv "${prefix}/bin/grafana-agent-linux-${alt_arch}" "${prefix}/bin/grafana-agent"

url="https://github.com/grafana/agent/releases/download/v${version}/grafana-agentctl-linux-${alt_arch}.zip"
filename="$(basename "${url}")"
check-github-release-asset "grafana/agent" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"
unzip -t "${uniget_cache_download}/${filename}"
unzip -q -o -d "${prefix}/bin" "${uniget_cache_download}/${filename}"
mv "${prefix}/bin/grafana-agentctl-linux-${alt_arch}" "${prefix}/bin/grafana-agentctl"

"${prefix}/bin/grafana-agentctl" completion bash >"${prefix}/share/bash-completion/completions/grafana-agentctl"
"${prefix}/bin/grafana-agentctl" completion fish >"${prefix}/share/fish/vendor_completions.d/grafana-agentctl.fish"
"${prefix}/bin/grafana-agentctl" completion zsh >"${prefix}/share/zsh/vendor-completions/_grafana-agentctl"
EOF
COPY agent.yaml /uniget_bootstrap/etc/grafana-agent/
