#syntax=docker/dockerfile:1.6.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:da13a27933fac882122e16292dad3e4869a53dbbc52a73b4a5ddfbcde6902a99 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
# agent
RUN <<EOF
check-github-release-asset "grafana/agent" "v${version}" "grafana-agent-linux-${alt_arch}.zip"
url="https://github.com/grafana/agent/releases/download/v${version}/grafana-agent-linux-${alt_arch}.zip"
filename="$(basename "${url}")"
curl --silent --location --fail --remote-name "${url}"
unzip -q -o -d "${prefix}/bin" "${filename}"
ls -l "${prefix}/bin"
mv "${prefix}/bin/grafana-agent-linux-${alt_arch}" "${prefix}/bin/grafana-agent"
EOF
# agentctl
RUN <<EOF
check-github-release-asset "grafana/agent" "v${version}" "grafana-agentctl-linux-${alt_arch}.zip"
url="https://github.com/grafana/agent/releases/download/v${version}/grafana-agentctl-linux-${alt_arch}.zip"
filename="$(basename "${url}")"
curl --silent --location --fail --remote-name "${url}"
unzip -q -o -d "${prefix}/bin" "${filename}"
mv "${prefix}/bin/grafana-agentctl-linux-${alt_arch}" "${prefix}/bin/grafana-agentctl"
"${prefix}/bin/grafana-agentctl" completion bash >"${prefix}/share/bash-completion/completions/grafana-agentctl"
"${prefix}/bin/grafana-agentctl" completion fish >"${prefix}/share/fish/vendor_completions.d/grafana-agentctl.fish"
"${prefix}/bin/grafana-agentctl" completion zsh >"${prefix}/share/zsh/vendor-completions/_grafana-agentctl"
EOF