#syntax=docker/dockerfile:1.21.0@sha256:26147acbda4f14c5add9946e2fd2ed543fc402884fd75146bd342a7f6271dc1d

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/knative/client/releases/download/knative-v${version}/kn-linux-${alt_arch}"
filename="$( basename "${url}" )"

check-github-release-asset "knative/client" "knative-v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/kn"

"${prefix}/bin/kn" completion bash >"${prefix}/share/bash-completion/completions/kn"
"${prefix}/bin/kn" completion zsh >"${prefix}/share/zsh/vendor-completions/_kn"
EOF