#syntax=docker/dockerfile:1.15.1@sha256:05e0ad437efefcf144bfbf9d7f728c17818408e6d01432d9e264ef958bbd52f3

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
echo "### Setting library string for ${TARGETPLATFORM}"
case "${arch}" in
    x86_64)
        export lib_suffix=musl
        ;;
    aarch64)
        export lib_suffix=gnu
        ;;
    *)
        echo "ERROR: Unsupported architecture ${arch}."
        exit 1
        ;;
esac
echo "    Using ${lib_suffix}"

url="https://github.com/nushell/nushell/releases/download/${version}/nu-${version}-${arch}-unknown-linux-${lib_suffix}.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "nushell/nushell" "${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin/" --strip-components=1 --no-same-owner
rm -f \
    "${prefix}/bin/LICENSE" \
    "${prefix}/bin/README.txt"
EOF