#syntax=docker/dockerfile:1.7.0

FROM ghcr.io/uniget-org/images/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "estesp/manifest-tool" "v${version}" "binaries-manifest-tool-${version}.tar.gz"
curl --silent --location --fail "https://github.com/estesp/manifest-tool/releases/download/v${version}/binaries-manifest-tool-${version}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/bin" --no-same-owner \
    manifest-tool-linux-${alt_arch}
mv "${prefix}/bin/manifest-tool-linux-${alt_arch}" "${prefix}/bin/manifest-tool"
EOF