#syntax=docker/dockerfile:1.21.0@sha256:26147acbda4f14c5add9946e2fd2ed543fc402884fd75146bd342a7f6271dc1d

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/jenkins-x/jx/releases/download/v${version}/jx-linux-${alt_arch}.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "jenkins-x/jx" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin/" --no-same-owner \
    jx

curl --silent --show-error --location --fail "https://github.com/jenkins-x/jx/archive/refs/tags/v${version}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/share/man/man1/" --strip-components=4 --no-same-owner \
    jx-${version}/docs/man/man1
EOF