#syntax=docker/dockerfile:1.25.0@sha256:0adf442eae370b6087e08edc7c50b552d80ddf261576f4ebd6421006b2461f12

FROM ghcr.io/uniget-org/tools/python-3.12:latest AS python
FROM ghcr.io/uniget-org/tools/shiv:latest AS shiv
FROM ghcr.io/uniget-org/tools/rust:latest AS rust

FROM registry.gitlab.com/uniget-org/images/build-essential:26.04@sha256:8d55aeb6450ccf79e5ed95209d08631f5a4ebe56acf77a43d7abeac8ace093aa AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=python / /usr/local/
COPY --link --from=shiv / /usr/local/
COPY --link --from=rust / /usr/local/
RUN --mount=type=cache,target=/var/cache/apt <<EOF
apt-get update
apt-get -y install --no-install-recommends \
    clang
EOF
ARG name
ARG version
RUN --mount=type=cache,target=/root/.cache/pip <<EOF
export CARGO_HOME=/usr/local/cargo
export RUSTUP_HOME=/usr/local/rustup
shiv --output-file "${prefix}/bin/checkov" --console-script checkov "checkov==${version}"
EOF