[plugins."io.containerd.grpc.v1.cri".containerd]
default_runtime_name = "runc"

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes]

# runc
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
    runtime_type = "io.containerd.runc.v2"

# crun
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.crun]
    runtime_type = "io.containerd.runc.v2"
    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.crun.options]
    BinaryName = "/usr/local/bin/crun"

# gvisor
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.gvisor]
    runtime_type = "io.containerd.runsc.v1"

# kata-containers
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata]
    runtime_type = "io.containerd.kata.v2"

# containerd-shim-spin
[plugins.cri.containerd.runtimes.spin]
  runtime_type = "io.containerd.spin.v2"

# containerd-shim-slight
[plugins.cri.containerd.runtimes.slight]
  runtime_type = "io.containerd.slight.v1"

# containerd-shim-wws
[plugins.cri.containerd.runtimes.wws]
  runtime_type = "io.containerd.wws.v1"

# containerd-shim-lunatic
[plugins.cri.containerd.runtimes.lunatic]
  runtime_type = "io.containerd.lunatic.v1"
