#syntax=docker/dockerfile:1.20.0@sha256:b6afd42430b15f2d2a4c5a02b919e98a525b785b1aaff16747d2f623364e39b6

FROM ghcr.io/uniget-org/tools/nodejs-lts:latest AS nodejs
FROM ghcr.io/uniget-org/tools/npm:latest AS npm

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=nodejs / /usr/local/
COPY --link --from=npm / /usr/local/
WORKDIR /uniget_bootstrap/libexec/n8n
ARG name
ARG version
RUN <<EOF
npm install \
    --omit=dev \
    "n8n@${version}"
ln --symbolic --relative --force "${prefix}/libexec/n8n/node_modules/.bin/n8n" "${prefix}/bin/"
EOF