#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/uniget-org/tools/nodejs:${ref} AS nodejs
FROM ghcr.io/uniget-org/tools/npm:${ref} AS npm

FROM ghcr.io/uniget-org/tools/base:${ref} AS prepare
COPY --link --from=nodejs / /
COPY --link --from=npm / /
WORKDIR ${prefix}${target}/libexec/n8n
ARG name
ARG version
RUN <<EOF
npm install \
    --omit=dev \
    "n8n@${version}"
ln --symbolic --relative --force "${prefix}${target}/libexec/n8n/node_modules/.bin/n8n" "${prefix}${target}/bin/"
EOF