#syntax=docker/dockerfile:1.7.1

FROM ghcr.io/uniget-org/images/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
curl --silent --show-error --location --fail --output "${prefix}/etc/profile.d/kubectl-aliases" \
    "https://github.com/ahmetb/kubectl-aliases/raw/master/.kubectl_aliases"
EOF