#syntax=docker/dockerfile:1.6.0

FROM nicholasdille/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "cyberark/kubeletctl" "v${version}" "kubeletctl_linux_${alt_arch}"
curl --silent --location --fail --output "${prefix}${target}/bin/kubeletctl" \
    "https://github.com/cyberark/kubeletctl/releases/download/v${version}/kubeletctl_linux_${alt_arch}"
chmod +x "${prefix}${target}/bin/kubeletctl"
EOF