#syntax=docker/dockerfile:1.8.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:dc6c0030ff36d8c83922c5c24088c89faf3cb4f0b21540e231f35408453b76c3 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "Trendyol/kink" "v${version}" "kink_${version}_Linux-${arch}.tar.gz"
curl --silent --show-error --location --fail "https://github.com/Trendyol/kink/releases/download/v${version}/kink_${version}_Linux-${arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/bin" --no-same-owner \
    kink
"${prefix}/bin/kink" completion bash >"${prefix}/share/bash-completion/completions/kink"
"${prefix}/bin/kink" completion fish >"${prefix}/share/fish/vendor_completions.d/kink.fish"
"${prefix}/bin/kink" completion zsh >"${prefix}/share/zsh/vendor-completions/_kink"
EOF