#syntax=docker/dockerfile:1.6.0

ARG ref=main

FROM ghcr.io/uniget-org/tools/base:${ref} AS prepare
ARG name
ARG version
RUN <<EOF
check-github-release-asset "antonmedv/walk" "v${version}" "walk_linux_${alt_arch}"
curl --silent --location --fail --output "${prefix}${target}/bin/walk" \
    "https://github.com/antonmedv/walk/releases/download/v${version}/walk_linux_${alt_arch}"
chmod +x "${prefix}${target}/bin/walk"
EOF