#syntax=docker/dockerfile:1.13.0@sha256:426b85b823c113372f766a963f68cfd9cd4878e1bcc0fda58779127ee98a28eb

FROM ghcr.io/uniget-org/tools/make:latest AS make

FROM registry.gitlab.com/uniget-org/images/build-essential:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=make / /usr/local/
WORKDIR /tmp/libnfnetlink
ARG name
ARG version
RUN <<EOF
check-clone "https://git.netfilter.org/libnfnetlink/" "libnfnetlink-${version}"
git clone -q --config advice.detachedHead=false --depth 1 --branch "libnfnetlink-${version}" git://git.netfilter.org/libnfnetlink .
./autogen.sh
./configure \
    --prefix="${prefix}" \
    --enable-shared \
    --enable-static
make install
EOF