#syntax=docker/dockerfile

FROM ghcr.io/uniget-org/tools/make:latest AS make

FROM registry.gitlab.com/uniget-org/images/build-essential:26.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=make / /usr/local/
WORKDIR /tmp/libnfnetlink
ARG name
ARG version
RUN <<EOF
url="https://www.netfilter.org/pub/libnfnetlink/libnfnetlink-${version}.tar.bz2"

check-download "${url}"
curl --silent --show-error --location --fail --output "/tmp/libnfnetlink-${version}.tar.bz2" \
    "${url}"

tar --file="/tmp/libnfnetlink-${version}.tar.bz2" --list
tar --file="/tmp/libnfnetlink-${version}.tar.bz2" --extract --bzip2 --strip-components=1 --no-same-owner

./configure \
    --prefix="${prefix}" \
    --enable-shared \
    --enable-static
make install
EOF