#syntax=docker/dockerfile:1.13.0@sha256:426b85b823c113372f766a963f68cfd9cd4878e1bcc0fda58779127ee98a28eb

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
COPY <<EOF /uniget_bootstrap/etc/profile.d/konf.sh
case "\$(basename "\${SHELL}")" in
    bash)
        source <(konf-go shellwrapper bash)
        ;;
    zsh)
        source <(konf-go shellwrapper zsh)
        ;;
esac
EOF
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/SimonTheLeg/konf-go/releases/download/v${version}/konf-go_${version}_linux_${alt_arch}.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "SimonTheLeg/konf-go" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin/" --no-same-owner \
    konf-go
"${prefix}/bin/konf-go" completion bash >"${prefix}/share/bash-completion/completions/konf"
"${prefix}/bin/konf-go" completion zsh >"${prefix}/share/zsh/vendor-completions/_konf"
EOF