#syntax=docker/dockerfile:1.6.0

FROM ghcr.io/uniget-org/images/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
curl --silent --location --fail --output "${prefix}/bin/minio" \
    "https://dl.min.io/server/minio/release/linux-${alt_arch}/minio.RELEASE.${version}"
chmod +x "${prefix}/bin/minio"
EOF