#syntax=docker/dockerfile:1.6.0

FROM nicholasdille/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]

ARG name
ARG version

RUN <<EOF
check-github-release-asset "danielfoehrKn/kubeswitch" "${version}" "switcher_linux_${alt_arch}"
curl --silent --location --fail --output "${prefix}${target}/bin/switcher" \
    "https://github.com/danielfoehrKn/kubeswitch/releases/download/${version}/switcher_linux_${alt_arch}"
chmod +x "${prefix}${target}/bin/switcher"

curl --silent --location --fail --output "${prefix}${target}/bin/switch.sh" \
    "https://github.com/danielfoehrKn/kubeswitch/releases/download/${version}/switch.sh"
chmod +x "${prefix}${target}/bin/switch.sh"

curl --silent --location --fail --output "${prefix}${target}/share/bash-completion/completions/${name}" \
    "https://github.com/danielfoehrKn/kubeswitch/raw/${version}/hack/switch/switch.sh"
curl --silent --location --fail --output "${prefix}${target}/share/fish/vendor_completions.d/${name}.fish" \
    "https://github.com/danielfoehrKn/kubeswitch/raw/${version}/hack/switch/switch.fish"
EOF