#syntax=docker/dockerfile:1.8.1

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:178a01206383923b589ecfe3bace55431c4b8528086909ffcdc1ef88de4da10f AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]

ARG name
ARG version

RUN <<EOF
check-github-release-asset "firecracker-microvm/firectl" "v${version}" "firectl-v${version}"
curl --silent --show-error --location --fail --output "${prefix}/bin/firectl" \
    "https://github.com/firecracker-microvm/firectl/releases/download/v${version}/firectl-v${version}"
chmod +x "${prefix}/bin/firectl"
EOF