#syntax=docker/dockerfile:1.7.0

FROM ghcr.io/uniget-org/images/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]

ARG name
ARG version

RUN <<EOF
check-github-release-asset "firecracker-microvm/firectl" "v${version}" "firectl-v${version}"
curl --silent --location --fail --output "${prefix}/bin/firectl" \
    "https://github.com/firecracker-microvm/firectl/releases/download/v${version}/firectl-v${version}"
chmod +x "${prefix}/bin/firectl"
EOF