#syntax=docker/dockerfile:1.6.0

FROM ghcr.io/uniget-org/images/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "chainguard-dev/bomshell" "v${version}" "bomshell-linux-${alt_arch}"
curl --silent --location --fail --output "${prefix}/bin/bomshell" \
    "https://github.com/chainguard-dev/bomshell/releases/download/v${version}/bomshell-linux-${alt_arch}"
chmod +x "${prefix}/bin/bomshell"
EOF