#syntax=docker/dockerfile:1.13.0@sha256:93bfd3b68c109427185cd78b4779fc82b484b0b7618e36d0f104d4d801e66d25

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/projectdiscovery/tlsx/releases/download/v${version}/tlsx_${version}_linux_${alt_arch}.zip"
filename="$( basename "${url}" )"

check-github-release-asset "projectdiscovery/tlsx" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

unzip -t "${uniget_cache_download}/${filename}"
unzip -q -o -d "${prefix}/bin" "${uniget_cache_download}/${filename}" \
    tlsx
EOF