#syntax=docker/dockerfile:1.17.1@sha256:e2dd261f92e4b763d789984f6eab84be66ab4f5f08052316d8eb8f173593acf7

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/theupdateframework/go-tuf/releases/download/v${version}/tuf-client_${version}_linux_amd64.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "theupdateframework/go-tuf" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin/" --no-same-owner \
    tuf-client

check-github-release-asset "theupdateframework/go-tuf" "v${version}" "tuf_${version}_linux_amd64.tar.gz"
curl --silent --show-error --location --fail "https://github.com/theupdateframework/go-tuf/releases/download/v${version}/tuf_${version}_linux_amd64.tar.gz" \
| tar --extract --gzip --directory="${prefix}/bin/" --no-same-owner \
    tuf
EOF