#syntax=docker/dockerfile:1.14.0@sha256:4c68376a702446fc3c79af22de146a148bc3367e73c25a5803d453b6b3f722fb

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
check-github-release-asset "tinygo-org/tinygo" "v${version}" "tinygo${version}.linux-${alt_arch}.tar.gz"
mkdir -p "${prefix}/opt"
curl --silent --show-error --location --fail "https://github.com/tinygo-org/tinygo/releases/download/v${version}/tinygo${version}.linux-${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/opt/" --no-same-owner
ln --symbolic --relative --force "${prefix}/opt/tinygo/bin/tinygo" "${prefix}/bin/tinygo"
EOF