#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:b0b654de801604e256237f2c27a907a4b61b59ebd83423ad0e0e465c0a3ba9cd AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
for DISTRIB_CODENAME in noble resolute; do
    url="https://github.com/PentHertz/LUKSbox/releases/download/v${version}/luksbox-v${version}-${arch}-linux-${DISTRIB_CODENAME}.tar.gz"
    filename="$( basename "${url}" )"

    check-github-release-asset "PentHertz/LUKSbox" "v${version}" "${filename}"
    curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
        "${url}"

    tar --file="${uniget_cache_download}/${filename}" --list
    tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}" --no-same-owner \
        ./luksbox \
        ./luksbox-gui \
        ./share

    mkdir -p "${prefix}/libexec/luksbox/${DISTRIB_CODENAME}"
    mv \
        "${prefix}/luksbox" \
        "${prefix}/luksbox-gui" \
        "${prefix}/libexec/luksbox/${DISTRIB_CODENAME}/"
done

ln --symbolic --relative --force "${prefix}/libexec/luksbox/resolute/luksbox" "${prefix}/bin/luksbox"
ln --symbolic --relative --force "${prefix}/libexec/luksbox/resolute/luksbox-gui" "${prefix}/bin/luksbox-gui"

mv "${prefix}/share/applications/com.penthertz.luksbox.desktop" "${prefix}/share/applications/com.penthertz.luksbox.desktop.go-template"
sed -i 's|Exec=luksbox-gui|Exec={{ .Target }}/luksbox-gui|' "${prefix}/share/applications/com.penthertz.luksbox.desktop.go-template"
EOF