#syntax=docker/dockerfile:1.8.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:6ff62e5ed6b1c33f0ae1644692a354281534a37ec4d752cf480850e19a94d16d AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "kubernetes-sigs/tejolote" "v${version}" "tejolote-${alt_arch}-linux"
curl --silent --show-error --location --fail --output "${prefix}/bin/tejolote" \
    "https://github.com/kubernetes-sigs/tejolote/releases/download/v${version}/tejolote-${alt_arch}-linux"
chmod +x "${prefix}/bin/tejolote"

"${prefix}/bin/tejolote" completion bash >"${prefix}/share/bash-completion/completions/tejolote"
"${prefix}/bin/tejolote" completion fish >"${prefix}/share/fish/vendor_completions.d/tejolote.fish"
"${prefix}/bin/tejolote" completion zsh >"${prefix}/share/zsh/vendor-completions/_tejolote"
EOF