#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:b0b654de801604e256237f2c27a907a4b61b59ebd83423ad0e0e465c0a3ba9cd AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
set -e -x

curl --silent --show-error --location --fail --output "${prefix}/bin/pacstall" \
    "https://github.com/pacstall/pacstall/raw/${version}/pacstall"
chmod +x "${prefix}/bin/pacstall"

curl --silent --show-error --location --fail --output "${prefix}/share/man/man8/pacstall.8" \
    "https://github.com/pacstall/pacstall/raw/${version}/misc/man/pacstall.8"
curl --silent --show-error --location --fail --output "${prefix}/share/man/man5/pacstall.5" \
    "https://github.com/pacstall/pacstall/raw/${version}/misc/man/pacstall.5"

scripts="$(
    curl --silent --show-error --location --fail "https://api.github.com/repos/pacstall/pacstall/contents/misc/scripts?ref=${version}" | jq --raw-output '.[].name'
)"
for script in ${scripts}; do
    curl --silent --show-error --location --fail --output "${prefix}/share/pacstall/scripts/${script}" --create-dirs \
        "https://github.com/pacstall/pacstall/raw/${version}/misc/scripts/${script}"
    chmod +x "${prefix}/share/pacstall/scripts/${script}"
done

curl --silent --show-error --location --fail --output "${prefix}/share/bash-completion/completions/pacstall" --create-dirs \
    "https://github.com/pacstall/pacstall/raw/${version}/misc/completion/bash"
curl --silent --show-error --location --fail --output "${prefix}/share/fish/vendor_completions.d/pacstall.fish" --create-dirs \
    "https://github.com/pacstall/pacstall/raw/${version}/misc/completion/fish"

mkdir -p "${prefix}/share/pacstall/repo"
echo "https://raw.githubusercontent.com/pacstall/pacstall-programs/master" >"${prefix}/share/pacstall/repo/pacstallrepo"
EOF