#syntax=docker/dockerfile:1.21.0@sha256:27f9262d43452075f3c410287a2c43f5ef1bf7ec2bb06e8c9eeb1b8d453087bc

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
set -e -x

curl --silent --show-error --location --fail --output "${prefix}/bin/pacstall" \
    "https://github.com/pacstall/pacstall/raw/${version}/pacstall"
chmod +x "${prefix}/bin/pacstall"

curl --silent --show-error --location --fail --output "${prefix}/share/man/man8/pacstall.8" \
    "https://github.com/pacstall/pacstall/raw/${version}/misc/man/pacstall.8"
curl --silent --show-error --location --fail --output "${prefix}/share/man/man5/pacstall.5" \
    "https://github.com/pacstall/pacstall/raw/${version}/misc/man/pacstall.5"

scripts="$(
    curl --silent --show-error --location --fail "https://api.github.com/repos/pacstall/pacstall/contents/misc/scripts?ref=${version}" | jq --raw-output '.[].name'
)"
for script in ${scripts}; do
    curl --silent --show-error --location --fail --output "${prefix}/share/pacstall/scripts/${script}" --create-dirs \
        "https://github.com/pacstall/pacstall/raw/${version}/misc/scripts/${script}"
    chmod +x "${prefix}/share/pacstall/scripts/${script}"
done

curl --silent --show-error --location --fail --output "${prefix}/share/bash-completion/completions/pacstall" --create-dirs \
    "https://github.com/pacstall/pacstall/raw/${version}/misc/completion/bash"
curl --silent --show-error --location --fail --output "${prefix}/share/fish/vendor_completions.d/pacstall.fish" --create-dirs \
    "https://github.com/pacstall/pacstall/raw/${version}/misc/completion/fish"

mkdir -p "${prefix}/share/pacstall/repo"
echo "https://raw.githubusercontent.com/pacstall/pacstall-programs/master" >"${prefix}/share/pacstall/repo/pacstallrepo"
EOF