#syntax=docker/dockerfile:1.27.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
GEYSER_VERSION="$(echo "${version}" | cut -d. -f1-3)"
GEYSER_BUILD="$(echo "${version}" | cut -d. -f4)"

url="https://download.geysermc.org/v2/projects/geyser/versions/${GEYSER_VERSION}/builds/${GEYSER_BUILD}/downloads/spigot"
filename="geyser-spigot.jar"
check-download "${url}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"
mkdir -p "${prefix}/opt/geyser"
install --mode=0644 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/opt/geyser/geyser.jar"

url="https://download.geysermc.org/v2/projects/geyser/versions/${GEYSER_VERSION}/builds/${GEYSER_BUILD}/downloads/standalone"
filename="geyser-standalone.jar"
check-download "${url}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"
mkdir -p "${prefix}/opt/geyser"
install --mode=0644 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/opt/geyser/geyser-standalone.jar"
EOF