#syntax=docker/dockerfile:1.22.0@sha256:4a43a54dd1fedceb30ba47e76cfcf2b47304f4161c0caeac2db1c61804ea3c91

FROM ghcr.io/uniget-org/tools/node-lts:latest AS node

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
COPY --link --from=node / /usr/local/
WORKDIR /uniget_bootstrap/libexec/srt
ARG name
ARG version
RUN <<EOF
npm install \
    --omit=dev \
    "@anthropic-ai/sandbox-runtime@${version}"
ln --symbolic --relative --force "${prefix}/libexec/srt/node_modules/.bin/srt" "${prefix}/bin/"
EOF