#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/build-essential:26.04@sha256:0761326451efd5adfeaa56278c455d16cf8d5e4303b3fd3d99031af25b3da6c8 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
WORKDIR /tmp/htop
ARG name
ARG version
RUN <<EOF
apt-get update
apt-get -y install --no-install-recommends \
    autoconf \
    automake \
    libcap-dev \
    libtool \
    pkg-config \
    libsensors-dev \
    libncursesw5-dev
EOF
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/htop-dev/htop/releases/download/${version}/htop-${version}.tar.xz"
filename="$( basename "${url}" )"

check-github-release-asset "htop-dev/htop" "${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --extract --xz --strip-components=1 --no-same-owner
./configure \
    --prefix="${prefix}" \
    --enable-static \
    --enable-capabilities \
    --enable-sensors \
    --with-proc=/proc
make -j$(nproc)
make install
EOF
