#syntax=docker/dockerfile:1.6.0

FROM ghcr.io/uniget-org/tools/go-md2man:latest AS go-md2man

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:da13a27933fac882122e16292dad3e4869a53dbbc52a73b4a5ddfbcde6902a99 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
apt-get update
apt-get -y install --no-install-recommends \
    git \
    make \
    gcc \
    pkgconf \
    btrfs-progs \
    libbtrfs-dev \
    libassuan-dev \
    lvm2 \
    libdevmapper-dev \
    libc-dev \
    libgpgme-dev \
    libprotobuf-dev \
    libprotobuf-c-dev \
    libseccomp-dev \
    libselinux-dev \
    libostree-dev \
    openssl \
    iptables \
    bash \
    go-md2man
EOF
WORKDIR /tmp/conmon
RUN git clone --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/containers/conmon.git .
RUN <<EOF
mkdir -p "${prefix}/share/man/man8"
make -j$(nproc) git-vars bin/conmon \
    PKG_CONFIG='pkg-config --static' \
    CFLAGS='-std=c99 -Os -Wall -Wextra -Werror -static' \
    LDFLAGS='-s -w -static'
make -j$(nproc) -C docs GOMD2MAN=go-md2man
mv bin/conmon "${prefix}/bin/conmon"
mv docs/conmon.8 "${prefix}/share/man/man8"
EOF
COPY default.yaml ${prefix}/etc/containers/registries.d/default.yaml
COPY policy.json ${prefix}/etc/containers/policy.json
COPY policy.conf ${prefix}/etc/containers/policy.conf
COPY registry.json ${prefix}/etc/containers/registries.json
COPY storage.conf ${prefix}/etc/containers/storage.conf