#syntax=docker/dockerfile:1.21.0@sha256:26147acbda4f14c5add9946e2fd2ed543fc402884fd75146bd342a7f6271dc1d

FROM ghcr.io/uniget-org/tools/make:latest AS make
FROM ghcr.io/uniget-org/tools/rust:latest AS rust

FROM registry.gitlab.com/uniget-org/images/build-essential:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
RUN --mount=type=cache,target=/var/cache/apt <<EOF
apt-get install -y --no-install-recommends \
    protobuf-compiler \
    libseccomp-dev \
    sudo \
    cmake
EOF
COPY --link --from=rust / /usr/local/
WORKDIR /tmp/github.com/spinframework/containerd-shim-spin
ARG name
ARG version
RUN --mount=type=cache,target=/target \
    --mount=type=cache,target=/usr/local/cargo/registry <<EOF
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/spinframework/containerd-shim-spin .
export CARGO_HOME=/usr/local/cargo
export CARGO_TARGET_DIR=/target
export RUSTUP_HOME=/usr/local/rustup
#export RUSTFLAGS='-C target-feature=+crt-static'
make -j$(nproc) build-cargo
cp /target/release/containerd-shim-spin-v2 "${prefix}/bin/"
EOF
