#syntax=docker/dockerfile:1.11.1@sha256:10c699f1b6c8bdc8f6b4ce8974855dd8542f1768c26eb240237b8f1c9c6c9976

FROM registry.gitlab.com/uniget-org/images/build-base:3.20 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
RUN --mount=type=cache,target=/var/cache/apk <<EOF
apk add --update-cache \
    curl-static \
    expat-static \
    gettext-static \
    zlib-static \
    zlib-dev \
    openssl-libs-static \
    openssl-dev \
    ncurses-dev \
    tcl \
    asciidoc \
    xmlto
EOF
WORKDIR /tmp/git
ARG name
ARG version
RUN <<EOF
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/git/git .
export CFLAGS="${CFLAGS} -static"
make configure
./configure --prefix="${prefix}"
make -j$(nproc) all
make -j$(nproc) doc
make install install-doc install-html
EOF