# yaml-language-server: $schema=https://tools.uniget.dev/schema.yaml
name: gitlab-ci-pipelines-exporter-systemd
license:
  name: MIT License
  link: https://github.com/uniget-org/tools/blob/main/LICENSE
version: "0.1.0"
binary: "false"
check: "" # No binary to check
runtime_dependencies:
- gitlab-ci-pipelines-exporter
- docker-compose-systemd
platforms:
- linux/amd64
- linux/arm64
tags:
- category/development
- lang/go
- type/cli
- gitlab
- standard/prometheus
- exporter
homepage: https://uniget.dev
repository: https://github.com/uniget-org/tools
description: compose file for gitlab-ci-pipelines-exporter with systemd
