#syntax=docker/dockerfile:1.17.0@sha256:e63addfe27b10e394a5f9f1e866961adc70d08573f1cb80f8d1a0999347b3553

FROM ghcr.io/uniget-org/tools/make:latest AS make

FROM registry.gitlab.com/uniget-org/images/build-base:3.21 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/apk <<EOF
apk add --update-cache \
    talloc-dev \
    talloc-static \
    linux-headers \
    bsd-compat-headers \
    py3-docutils
EOF
COPY --link --from=make / /usr/local/
WORKDIR /tmp/proot
RUN <<EOF
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/proot-me/proot .
make -C src -j$(nproc) LDFLAGS="-static -ltalloc"
make -C doc proot/man.1
cp src/proot "${prefix}/bin/"
cp doc/proot/man.1 "${prefix}/share/man/man1/proot.1"
EOF