#syntax=docker/dockerfile:1.11.1@sha256:1f2be5a2aa052cbd9aedf893d17c63277c3d1c51b3fb0f3b029c6b34f658d057

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://dist.neo4j.org/cypher-shell/cypher-shell-${version}.zip"
filename="$(basename "${url}")"

curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

mkdir -p "${prefix}/opt"
unzip -t "${uniget_cache_download}/${filename}"
unzip -q -o -d "${prefix}/opt/" "${uniget_cache_download}/${filename}"

mv "${prefix}/opt/cypher-shell-${version}" "${prefix}/opt/cypher-shell"
ln --symbolic --relative --force "/opt/cypher-shell/bin/cypher-shell" "${prefix}/bin/"
EOF