#syntax=docker/dockerfile:1.21.0@sha256:27f9262d43452075f3c410287a2c43f5ef1bf7ec2bb06e8c9eeb1b8d453087bc

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
echo "### Setting architecture string for ${TARGETPLATFORM}"
case "${arch}" in
    x86_64)
        export arch_suffix="x64"
        ;;
    aarch64)
        export arch_suffix="${arch}"
        ;;
    *)
        echo "ERROR: Unsupported architecture ${arch}."
        exit 1
        ;;
esac
echo "    Using ${arch_suffix}"

real_version="$(
    echo "${version}" \
    | sed -E 's/^([[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+)-([[:digit:]]+)$/\1+\2/'
)"
echo "### Using OpenJDK version ${real_version}"

MAJOR_VERSION="$(echo "${real_version}" | sed -E 's/^([0-9]+)(\.[0-9]\.[0-9]+)?\+([0-9]+)$/\1/')"
echo "    Major version: ${MAJOR_VERSION}"
version_url_encoded="$(echo "${real_version}" | sed 's/+/%2B/g')"
echo "    URL encoded version: ${version_url_encoded}"
version_filename="$(echo "${real_version}" | sed 's/+/_/g')"
echo "    Filename version: ${version_filename}"

url="https://github.com/adoptium/temurin${MAJOR_VERSION}-binaries/releases/download/jdk-${version_url_encoded}/OpenJDK${MAJOR_VERSION}U-jre_${arch_suffix}_linux_hotspot_${version_filename}.tar.gz"
filename="$(basename "${url}")"

check-github-release-asset "adoptium/temurin${MAJOR_VERSION}-binaries" "jdk-${real_version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

mkdir -p "${prefix}/opt/openjdk-jre"
tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/opt/openjdk-jre" --strip-components=1 --no-same-owner

cd "${prefix}/opt/openjdk-jre/bin"
find . -type f -executable \
| while read -r BINARY; do
    ln --symbolic --relative --force "${prefix}/opt/openjdk-jre/bin/${BINARY:2}" "${prefix}/bin/${BINARY:2}"
done
EOF