#syntax=docker/dockerfile:1.27.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/newren/git-filter-repo/releases/download/v${version}/git-filter-repo-${version}.tar.xz"
filename="$( basename "${url}" )"

check-github-release-asset "newren/git-filter-repo" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --xz --directory="/tmp/" --strip-components=1 --no-same-owner \
    "git-filter-repo-${version}/git-filter-repo" \
    "git-filter-repo-${version}/Documentation/man1/git-filter-repo.1" \
    "git-filter-repo-${version}/Documentation/html/git-filter-repo.html"

mkdir -p "${prefix}/share/doc/git/html/"
mv /tmp/git-filter-repo "${prefix}/bin/"
mv /tmp/Documentation/man1/git-filter-repo.1 "${prefix}/share/man/man1/"
mv /tmp/Documentation/html/git-filter-repo.html "${prefix}/share/doc/git/html/"
EOF