#syntax=docker/dockerfile:1.25.0@sha256:0adf442eae370b6087e08edc7c50b552d80ddf261576f4ebd6421006b2461f12

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:e949a11db56b186fbed29acb3e6b04119b90e981d1eb1fff68013ba83a0ab38f AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/GrantBirki/hub/releases/download/v${version}/hub-linux-${alt_arch}-${version}.tgz"
filename="$( basename "${url}" )"

check-github-release-asset "github/hub" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}" --strip-components=1 --no-same-owner
rm -f \
    "${prefix}/LICENSE" \
    "${prefix}/install" \
    "${prefix}/README.md" \
    "${prefix}/share/man/man1/*.txt"
mv "${prefix}/etc/hub.bash_completion.sh" "${prefix}/share/bash-completion/completions/hub"
mv "${prefix}/etc/hub.fish_completion"    "${prefix}/share/fish/vendor_completions.d/hub.fish"
mv "${prefix}/etc/hub.zsh_completion"     "${prefix}/share/zsh/vendor-completions/_hub"
rm -rf \
    "${prefix}/share/doc/hub-doc" \
    "${prefix}/share/vim"
EOF