#syntax=docker/dockerfile:1.8.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:dc6c0030ff36d8c83922c5c24088c89faf3cb4f0b21540e231f35408453b76c3 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]

ARG name
ARG version

RUN <<EOF
check-github-release-asset "github/hub" "v${version}" "hub-linux-${alt_arch}-${version}.tgz"
curl --silent --show-error --location --fail "https://github.com/GrantBirki/hub/releases/download/v${version}/hub-linux-${alt_arch}-${version}.tgz" \
| tar --extract --gzip --directory="${prefix}" --strip-components=1 --no-same-owner
rm -f \
    "${prefix}/LICENSE" \
    "${prefix}/install" \
    "${prefix}/README.md" \
    "${prefix}/share/man/man1/*.txt"
mv "${prefix}/etc/hub.bash_completion.sh" "${prefix}/share/bash-completion/completions/hub"
mv "${prefix}/etc/hub.fish_completion"    "${prefix}/share/fish/vendor_completions.d/hub.fish"
mv "${prefix}/etc/hub.zsh_completion"     "${prefix}/share/zsh/vendor-completions/_hub"
rm -rf \
    "${prefix}/share/doc/hub-doc" \
    "${prefix}/share/vim"
EOF