#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:b0b654de801604e256237f2c27a907a4b61b59ebd83423ad0e0e465c0a3ba9cd AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
COPY --chmod=0755 install-docker-ai.sh "/uniget_bootstrap/bin/"
RUN <<EOF
DOCKER_DESKTOP_VERSION="$(
    echo "${version}" \
    | cut -d- -f2
)"
sed -i "s/docker_desktop_version:=DD_VERSION/docker_desktop_version:=${DOCKER_DESKTOP_VERSION}/" "/uniget_bootstrap/bin/install-docker-ai.sh"
EOF