#syntax=docker/dockerfile:1.25.0@sha256:0adf442eae370b6087e08edc7c50b552d80ddf261576f4ebd6421006b2461f12

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:cc8b2a023c3777e8b654c98d4bebc58827f8fcb73c4ce309d9ffa01b432954a9 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
COPY --chmod=0755 install-docker-ai.sh "/uniget_bootstrap/bin/"
RUN <<EOF
DOCKER_DESKTOP_VERSION="$(
    echo "${version}" \
    | cut -d- -f2
)"
sed -i "s/docker_desktop_version:=DD_VERSION/docker_desktop_version:=${DOCKER_DESKTOP_VERSION}/" "/uniget_bootstrap/bin/install-docker-ai.sh"
EOF