#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM ghcr.io/uniget-org/tools/zig:latest AS zig

FROM registry.gitlab.com/uniget-org/images/build-essential:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
apt-get update
apt-get -y install --no-install-recommends \
    gpg \
    blueprint-compiler \
    debhelper \
    devscripts \
    pandoc \
    libonig-dev \
    libbz2-dev \
    libgtk-layer-shell-dev \
    libgtk-4-dev \
    libadwaita-1-dev \
    minisign \
    libxml2-utils
EOF
#COPY --link --from=zig / /
WORKDIR /tmp
RUN <<EOF
curl --silent --show-error --location --fail --remote-name "https://release.files.ghostty.org/${version}/ghostty-${version}.tar.gz"
curl --silent --show-error --location --fail --remote-name "https://release.files.ghostty.org/${version}/ghostty-${version}.tar.gz.minisig"
minisign -Vm "ghostty-${version}.tar.gz" -P "RWQlAjJC23149WL2sEpT/l0QKy7hMIFhYdQOFy0Z7z7PbneUgvlsnYcV"
EOF
WORKDIR /tmp/ghostty
RUN <<EOF
tar --extract --gzip --file="/tmp/ghostty-${version}.tar.gz" --strip-components=1
EOF
WORKDIR /tmp
RUN <<EOF
ZIG_VERSION="$( grep .minimum_zig_version /tmp/ghostty/build.zig.zon | cut -d\" -f2 )"
curl --silent --show-error --location --fail --remote-name "https://ziglang.org/download/${ZIG_VERSION}/zig-${arch}-linux-${ZIG_VERSION}.tar.xz"
curl --silent --show-error --location --fail --remote-name "https://ziglang.org/download/${ZIG_VERSION}/zig-${arch}-linux-${ZIG_VERSION}.tar.xz.minisig"
minisign -Vm "zig-${arch}-linux-${ZIG_VERSION}.tar.xz" -P "RWSGOq2NVecA2UPNdBUZykf1CCb147pkmdtYxgb3Ti+JO/wCYvhbAb/U"
tar --extract --xz --directory=/opt --file="zig-${arch}-linux-${ZIG_VERSION}.tar.xz"
ln --symbolic --relative --force "/opt/zig-${arch}-linux-${ZIG_VERSION}/zig" /usr/local/bin/zig
zig version
EOF
WORKDIR /tmp/ghostty
RUN <<EOF
zig build \
    --summary all \
    --prefix "${prefix}" \
    -Doptimize=ReleaseFast \
    -Dcpu=baseline \
    -Dpie=true \
    -Demit-docs \
    -Dversion-string=${version} \
    -fno-sys=gtk4-layer-shell
EOF
RUN <<EOF
rm -f \
    "${prefix}/share/applications/com.mitchellh.ghostty.desktop" \
    "${prefix}/share/dbus-1/services/com.mitchellh.ghostty.service" \
    "${prefix}/share/kio/servicemenus/com.mitchellh.ghostty.desktop" \
    "${prefix}/share/systemd/user/app-com.mitchellh.ghostty.service"
EOF
COPY share /uniget_bootstrap/share/
