#syntax=docker/dockerfile:1.6.0

FROM nicholasdille/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]

ARG name
ARG version

RUN <<EOF
check-download "https://github.com/fidian/ansi/raw/${version}/ansi"

curl --silent --location --fail --output "${prefix}${target}/bin/ansi" \
    "https://github.com/fidian/ansi/raw/${version}/ansi"
chmod +x "${prefix}${target}/bin/ansi"
EOF