#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM ghcr.io/uniget-org/tools/make:latest AS make

FROM registry.gitlab.com/uniget-org/images/build-essential:26.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --from=make / /usr/local
RUN <<EOF
apt-get update
apt-get install -y \
    libcrypt-dev
EOF
ARG name
ARG version
WORKDIR /tmp/capsudo
RUN --mount=type=cache,target=/root/.cache <<SCRIPT
check-clone "https://github.com/kaniini/capsudo" "v${version}"
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/kaniini/capsudo .
make LDFLAGS=-static
mkdir -p "${prefix}/bin"
cp capsudo capsudod "${prefix}/bin/"
SCRIPT
