#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://storage.googleapis.com/gvisor/releases/release/${version}/${arch}/runsc"
filename="$( basename "${url}" )"

check-download "${url}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/runsc"


check-download "https://storage.googleapis.com/gvisor/releases/release/${version}/${arch}/containerd-shim-runsc-v1"
curl --silent --show-error --location --fail --output "${prefix}/bin/containerd-shim-runsc-v1" \
    "https://storage.googleapis.com/gvisor/releases/release/${version}/${arch}/containerd-shim-runsc-v1"
chmod +x "${prefix}/bin/containerd-shim-runsc-v1"
EOF