#syntax=docker/dockerfile:1.6.0

FROM nicholasdille/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "maaslalani/slides" "v${version}" "slides_${version}_linux_${alt_arch}.tar.gz"
curl --silent --location --fail "https://github.com/maaslalani/slides/releases/download/v${version}/slides_${version}_linux_${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}${target}/bin" --no-same-owner \
    slides
EOF