#syntax=docker/dockerfile:1.7.0

FROM ghcr.io/uniget-org/images/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
case "${alt_arch}" in
    amd64)
        export arch_suffix="musl"
        ;;
    arm64)
        export arch_suffix="${arch}"
        ;;
    *)
        echo "ERROR: Unsupported architecture (${alt_arch})."
        exit 1
        ;;
esac

check-github-release-asset "extrawurst/gitui" "v${version}" "gitui-linux-${arch_suffix}.tar.gz"

echo "### Downloading gitui ${version}"
curl --silent --location --fail "https://github.com/extrawurst/gitui/releases/download/v${version}/gitui-linux-${arch_suffix}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/bin/" --no-same-owner
EOF