#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
VELOCITY_VERSION_COMPONENTS=1
VELOCITY_BUILD_INDEX=2
if grep -q "SNAPSHOT" <<< "${version}"; then
    VELOCITY_VERSION_COMPONENTS=1-2
    VELOCITY_BUILD_INDEX=3
fi

VELOCITY_VERSION="$(echo "${version}" | cut -d- -f${VELOCITY_VERSION_COMPONENTS})"
VELOCITY_BUILD="$(echo "${version}" | cut -d- -f"${VELOCITY_BUILD_INDEX}")"
echo "VELOCITY_VERSION=${VELOCITY_VERSION}"
echo "VELOCITY_BUILD=${VELOCITY_BUILD}"

url="$(
    curl --silent --show-error --location --fail --url "https://fill.papermc.io/v3/projects/velocity/versions/${VELOCITY_VERSION}/builds/${VELOCITY_BUILD}" \
    | jq --raw-output '.downloads."server:default".url'
)"
echo "url=${url}"
filename="$( basename "${url}" )"
echo "filename=${filename}"

check-download "${url}"
curl --silent --show-error --location --fail --output "/tmp/${filename}" \
    "${url}"

mkdir -p "${prefix}/opt/velocity"
install --mode=0644 \
    "/tmp/${filename}" \
    "${prefix}/opt/velocity/velocity.jar"
EOF