#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM ghcr.io/uniget-org/tools/go:latest AS go
FROM ghcr.io/uniget-org/tools/make:latest AS make

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=go / /usr/local/
COPY --link --from=make / /usr/local/
WORKDIR /go/src/github.com/Kapro-dev/kapro
ARG name
ARG version
RUN --mount=type=cache,target=/root/go/pkg/mod <<EOF
check-clone "https://github.com/Kapro-dev/kapro" "v${version}"
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/Kapro-dev/kapro .
go build -trimpath -ldflags="-s -w" -o "${prefix}/bin/kapro" ./cmd/kapro
EOF
RUN <<EOF
"${prefix}/bin/kapro" completion bash >"${prefix}/share/bash-completion/completions/kapro" 2>/dev/null || true
"${prefix}/bin/kapro" completion fish >"${prefix}/share/fish/vendor_completions.d/kapro.fish" 2>/dev/null || true
"${prefix}/bin/kapro" completion zsh  >"${prefix}/share/zsh/vendor-completions/_kapro" 2>/dev/null || true
EOF
