#syntax=docker/dockerfile:1.27.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
WORKDIR /tmp/lsd
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/lsd-rs/lsd/releases/download/v${version}/lsd-v${version}-${arch}-unknown-linux-musl.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "lsd-rs/lsd" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --strip-components=1 --no-same-owner
mv lsd "${prefix}/bin/"
mv lsd.1 "${prefix}/share/man/man1/"

mv autocomplete/lsd.bash-completion "${prefix}/share/bash-completion/completions/lsd"
mv autocomplete/lsd.fish "${prefix}/share/fish/vendor_completions.d/"
mv autocomplete/_lsd "${prefix}/share/zsh/vendor-completions/"
EOF