#syntax=docker/dockerfile:1.13.0@sha256:426b85b823c113372f766a963f68cfd9cd4878e1bcc0fda58779127ee98a28eb

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
WORKDIR /tmp/lsd
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/lsd-rs/lsd/releases/download/v${version}/lsd-v${version}-${arch}-unknown-linux-musl.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "lsd-rs/lsd" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --strip-components=1 --no-same-owner
mv lsd "${prefix}/bin/"
mv lsd.1 "${prefix}/share/man/man1/"

mv autocomplete/lsd.bash-completion "${prefix}/share/bash-completion/completions/lsd"
mv autocomplete/lsd.fish "${prefix}/share/fish/vendor_completions.d/"
mv autocomplete/_lsd "${prefix}/share/zsh/vendor-completions/"
EOF