#syntax=docker/dockerfile:1.27.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
mkdir -p "${prefix}/share/source-sans"

url="https://github.com/adobe-fonts/source-sans/releases/download/${version}R/WOFF-source-sans-${version}R.zip"
filename="$(basename "${url}")"
check-github-release-asset "adobe-fonts/source-sans" "${version}R" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"
unzip -t "${uniget_cache_download}/${filename}"
unzip -q -o -d "${prefix}/share/source-sans" "${uniget_cache_download}/${filename}"

url="https://github.com/adobe-fonts/source-sans/releases/download/${version}R/WOFF2-source-sans-${version}R.zip"
filename="$(basename "${url}")"
check-github-release-asset "adobe-fonts/source-sans" "${version}R" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"
unzip -t "${uniget_cache_download}/${filename}"
unzip -q -o -d "${prefix}/share/source-sans" "${uniget_cache_download}/${filename}"

rm -rf "${prefix}/share/source-sans/__MACOSX"
find "${prefix}/share/source-sans" -type f -name \.DS_Store -delete

curl --silent --show-error --location --fail --output "${prefix}/share/source-sans/source-sans-3.css" \
    "https://github.com/adobe-fonts/source-sans/raw/${version}R/source-sans-3.css"
EOF