#syntax=docker/dockerfile:1.7.1

FROM ghcr.io/uniget-org/images/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
mkdir -p "${prefix}/share/source-sans"

url="https://github.com/adobe-fonts/source-sans/releases/download/${version}R/WOFF-source-sans-${version}R.zip"
check-github-release-asset "adobe-fonts/source-sans" "${version}R" "WOFF-source-sans-${version}R.zip"
filename="$(basename "${url}")"
curl --silent --show-error --location --fail --remote-name "${url}"
unzip -q -o -d "${prefix}/share/source-sans" "${filename}"

url="https://github.com/adobe-fonts/source-sans/releases/download/${version}R/WOFF2-source-sans-${version}R.zip"
check-github-release-asset "adobe-fonts/source-sans" "${version}R" "WOFF2-source-sans-${version}R.zip"
filename="$(basename "${url}")"
curl --silent --show-error --location --fail --remote-name "${url}"
unzip -q -o -d "${prefix}/share/source-sans" "${filename}"

rm -rf "${prefix}/share/source-sans/__MACOSX"
find "${prefix}/share/source-sans" -type f -name \.DS_Store -delete

curl --silent --show-error --location --fail --output "${prefix}/share/source-sans/source-sans-3.css" \
    "https://github.com/adobe-fonts/source-sans/raw/${version}R/source-sans-3.css"
EOF