#syntax=docker/dockerfile:1.21.0@sha256:26147acbda4f14c5add9946e2fd2ed543fc402884fd75146bd342a7f6271dc1d

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
case "${alt_arch}" in
    amd64)
        export arch_suffix="${arch}"
        ;;
    arm64)
        export arch_suffix="${alt_arch}"
        ;;
    *)
        echo "ERROR: Unsupported architecture (${alt_arch})."
        exit 1
        ;;
esac
echo "    Using ${arch_suffix}"

url="https://github.com/kudobuilder/kuttl/releases/download/v${version}/kuttl_${version}_linux_${arch_suffix}.tar.gz"
filename="$(basename "${url}")"

check-github-release-asset "kudobuilder/kuttl" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin/" --no-same-owner \
    kubectl-kuttl

"${prefix}/bin/kubectl-kuttl" completion bash >"${prefix}/share/bash-completion/completions/kubectl-kuttl"
"${prefix}/bin/kubectl-kuttl" completion fish >"${prefix}/share/fish/vendor_completions.d/kubectl-kuttl.fish"
"${prefix}/bin/kubectl-kuttl" completion zsh >"${prefix}/share/zsh/vendor-completions/_kubectl-kuttl"
EOF