#syntax=docker/dockerfile:1.6.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:da13a27933fac882122e16292dad3e4869a53dbbc52a73b4a5ddfbcde6902a99 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "derailed/popeye" "v${version}" "popeye_Linux_${alt_arch}.tar.gz"
curl --silent --location --fail "https://github.com/derailed/popeye/releases/download/v${version}/popeye_Linux_${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/bin/" --no-same-owner \
    popeye
"${prefix}/bin/popeye" completion bash >"${prefix}/share/bash-completion/completions/popeye"
"${prefix}/bin/popeye" completion fish >"${prefix}/share/fish/vendor_completions.d/popeye.fish"
"${prefix}/bin/popeye" completion zsh >"${prefix}/share/zsh/vendor-completions/_popeye"
EOF