#syntax=docker/dockerfile:1.15.1@sha256:05e0ad437efefcf144bfbf9d7f728c17818408e6d01432d9e264ef958bbd52f3

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/chmln/sd/releases/download/v${version}/sd-v${version}-${arch}-unknown-linux-musl.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "chmln/sd" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin/" --strip-components=1 --no-same-owner

mv "${prefix}/bin/completions/sd.bash" "${prefix}/share/bash-completion/completions/sd"
mv "${prefix}/bin/completions/sd.fish" "${prefix}/share/fish/vendor_completions.d/sd.fish"
mv "${prefix}/bin/completions/_sd" "${prefix}/share/zsh/vendor-completions/_sd"
rm -rf "${prefix}/bin/completions/"

mv "${prefix}/bin/sd.1" "${prefix}/share/man/man1/"

rm -f \
    "${prefix}/bin/README.md" \
    "${prefix}/bin/LICENSE" \
    "${prefix}/bin/CHANGELOG.md" \
EOF