#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS ubuntu2604

FROM ubuntu2604 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
echo "### Setting architecture string for ${TARGETPLATFORM}"
case "${arch}" in
    x86_64)
        export arch_suffix="${arch}"
        ;;
    aarch64)
        export arch_suffix="${alt_arch}"
        ;;
    *)
        echo "ERROR: Unsupported architecture ${arch}."
        exit 1
        ;;
esac
echo "    Using ${arch_suffix}"

url="https://github.com/github/github-mcp-server/releases/download/v${version}/github-mcp-server_Linux_${arch_suffix}.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "github/github-mcp-server" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin" --no-same-owner \
    github-mcp-server
EOF
RUN <<EOF
"${prefix}/bin/github-mcp-server" completion bash >"${prefix}/share/bash-completion/completions/github-mcp-server"
"${prefix}/bin/github-mcp-server" completion fish >"${prefix}/share/fish/vendor_completions.d/github-mcp-server.fish"
"${prefix}/bin/github-mcp-server" completion zsh >"${prefix}/share/zsh/vendor-completions/_github-mcp-server"
EOF