#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
MINECRAFT_VERSION="$(echo "${version}" | cut -d- -f1)"
PAPER_BUILD="$(echo "${version}" | cut -d- -f2)"
echo "Downloading papar ${MINECRAFT_VERSION} build ${PAPER_BUILD}"

url="$(
    curl --silent --show-error --location --fail https://fill.papermc.io/v3/projects/paper/versions/${MINECRAFT_VERSION}/builds/${PAPER_BUILD} \
    | jq -r '.downloads."server:default".url'
)"
filename="$(basename "${url}")"

check-download "${url}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

mkdir -p "${prefix}/opt/papermc"
install --mode=0644 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/opt/papermc/paper.jar"
EOF