#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM registry.gitlab.com/uniget-org/images/alpine:3.24@sha256:3a9a59f6df17a6d831f3ccd5f27663d3e0c9821cf14f69da207f17421903a2c2 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://repo.katenary.io/api/packages/Katenary/generic/katenary/${version}/katenary-linux-${alt_arch}"
filename="$( basename "${url}" )"

check-download "${url}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/katenary"

"${prefix}/bin/katenary" completion bash >"${prefix}/share/bash-completion/completions/katenary"
"${prefix}/bin/katenary" completion fish >"${prefix}/share/fish/vendor_completions.d/katenary.fish"
"${prefix}/bin/katenary" completion zsh >"${prefix}/share/zsh/vendor-completions/_katenary"
EOF
