#syntax=docker/dockerfile:1.17.0@sha256:e63addfe27b10e394a5f9f1e866961adc70d08573f1cb80f8d1a0999347b3553

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
echo "### Setting architecture string for ${TARGETPLATFORM}"
case "${arch}" in
    x86_64)
        export arch_suffix="${arch}"
        ;;
    aarch64)
        export arch_suffix="${alt_arch}"
        ;;
    *)
        echo "ERROR: Unsupported architecture ${arch}."
        exit 1
        ;;
esac
echo "    Using ${arch_suffix}"

url="https://github.com/charmbracelet/mods/releases/download/v${version}/mods_${version}_Linux_${arch_suffix}.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "charmbracelet/mods" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin/" --strip-components=1 --no-same-owner \
    "mods_${version}_Linux_${arch_suffix}/mods" \
    "mods_${version}_Linux_${arch_suffix}/completions"

mv "${prefix}/bin/completions/mods.bash" "${prefix}/share/bash-completion/completions/mods"
mv "${prefix}/bin/completions/mods.fish" "${prefix}/share/fish/vendor_completions.d/mods.fish"
mv "${prefix}/bin/completions/mods.zsh"  "${prefix}/share/zsh/vendor-completions/_mods"
rmdir "${prefix}/bin/completions"
EOF
