#syntax=docker/dockerfile:1.9.0@sha256:fe40cf4e92cd0c467be2cfc30657a680ae2398318afd50b0c80585784c604f28

FROM ghcr.io/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
WORKDIR /tmp/bat
ARG name
ARG version
RUN <<EOF
check-github-release-asset "sharkdp/bat" "v${version}" "bat-v${version}-x86_64-unknown-linux-gnu.tar.gz"
curl --silent --show-error --location --fail "https://github.com/sharkdp/bat/releases/download/v${version}/bat-v${version}-x86_64-unknown-linux-gnu.tar.gz" \
| tar --extract --gzip --strip-components=1 --no-same-owner
mv bat "${prefix}/bin/"
mv bat.1 "${prefix}/share/man/man1/"
mv autocomplete/bat.bash "${prefix}/share/bash-completion/completions/bat"
mv autocomplete/bat.fish "${prefix}/share/fish/vendor_completions.d/"
mv autocomplete/bat.zsh "${prefix}/share/zsh/vendor-completions/_bat"
EOF