#syntax=docker/dockerfile:1.24.0@sha256:2780b5c3bab67f1f76c781860de469442999ed1a0d7992a5efdf2cffc0e3d769

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:99a2bccd1ad68bfc5b1d1eb356cf54b7dd94e45c5216b89c87b9e21c70e12b9f AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
COPY docker-compose@.service.go-template /uniget_bootstrap/etc/systemd/system/
COPY <<EOF /uniget_bootstrap/etc/docker-compose/README
Please see usage notes
EOF
COPY docker-compose@.service.go-template /uniget_bootstrap/etc/systemd/user/
RUN <<EOF
sed -i "s|WorkingDirectory=/etc/docker-compose/%i|WorkingDirectory=%h/.config/docker-compose/%i|g" "${prefix}/etc/systemd/user/docker-compose@.service.go-template"
EOF
