#syntax=docker/dockerfile

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
COPY docker-compose@.service.go-template /uniget_bootstrap/etc/systemd/system/
COPY <<EOF /uniget_bootstrap/etc/docker-compose/README
Please see usage notes
EOF
COPY docker-compose@.service.go-template /uniget_bootstrap/etc/systemd/user/
RUN <<EOF
sed -i "s|WorkingDirectory=/etc/docker-compose/%i|WorkingDirectory=%h/.config/docker-compose/%i|g" "${prefix}/etc/systemd/user/docker-compose@.service.go-template"
EOF
