#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="$(
    curl --silent --show-error --location --fail "https://codeberg.org/api/v1/repos/forgejo/forgejo/releases" \
    | jq --raw-output --arg version "${version}" --arg alt_arch "${alt_arch}" '
        .[] 
        | select(.tag_name == "v\($version)")
        | .assets[]
        | select(.name == "forgejo-\($version)-linux-\($alt_arch).xz")
        | .browser_download_url
    '
)"
if test -z "${url}"; then
    echo "ERROR: Unable to determine download URL."
    exit 1
fi
filename="$(basename "${url}")"

check-download "${url}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

xz --decompress "${uniget_cache_download}/${filename}" >"${prefix}/bin/forgejo"
chmod +x "${prefix}/bin/forgejo"
EOF