#syntax=docker/dockerfile:1.19.0@sha256:b6afd42430b15f2d2a4c5a02b919e98a525b785b1aaff16747d2f623364e39b6

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="$(
    curl --silent --show-error --location --fail "https://codeberg.org/api/v1/repos/forgejo/forgejo/releases" \
    | jq --raw-output --arg version "${version}" --arg alt_arch "${alt_arch}" '
        .[] 
        | select(.tag_name == "v\($version)")
        | .assets[]
        | select(.name == "forgejo-\($version)-linux-\($alt_arch).xz")
        | .browser_download_url
    '
)"
test -n "${url}"
filename="$(basename "${url}")"

check-download "${url}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

xz --decompress "${uniget_cache_download}/${filename}" >"${prefix}/bin/forgejo"
chmod +x "${prefix}/bin/forgejo"
EOF