#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM ghcr.io/uniget-org/tools/python-3.12:latest AS python
FROM ghcr.io/uniget-org/tools/pipx:latest AS pipx

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=python / /usr/local/
COPY --link --from=pipx / /usr/local/
WORKDIR /tmp/pass-git-helper
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/languitar/pass-git-helper/archive/refs/tags/v${version}.tar.gz"
filename="$(basename "${url}")"

check-download "${url}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --strip-components=1 --no-same-owner

printenv | sort
export PIPX_HOME="${prefix}/libexec/pipx"
export PIPX_BIN_DIR="${prefix}/bin"
pipx install .
ln --symbolic --relative --force "${prefix}/libexec/pipx/venvs/pass-git-helper/bin/pass-git-helper" "${prefix}/bin/pass-git-helper"
sed -i "s|#\!${prefix}/|#\!/|" "${prefix}/libexec/pipx/venvs/pass-git-helper/bin/pass-git-helper"
EOF
