#syntax=docker/dockerfile

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/raesene/zeedumper/releases/download/v${version}/zeedumper_${version}_linux_${alt_arch}.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "raesene/zeedumper" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin" --no-same-owner \
    zeedumper
EOF
RUN <<EOF
"${prefix}/bin/zeedumper" completion bash >"${prefix}/share/bash-completion/completions/zeedumper"
"${prefix}/bin/zeedumper" completion fish >"${prefix}/share/fish/vendor_completions.d/zeedumper.fish"
"${prefix}/bin/zeedumper" completion zsh >"${prefix}/share/zsh/vendor-completions/_zeedumper"
EOF