#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM ghcr.io/uniget-org/tools/make:latest AS make
FROM ghcr.io/uniget-org/tools/libmnl:latest AS libmnl

FROM registry.gitlab.com/uniget-org/images/build-essential:26.04@sha256:0761326451efd5adfeaa56278c455d16cf8d5e4303b3fd3d99031af25b3da6c8 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=make / /usr/local/
COPY --link --from=libmnl / /usr/local/
WORKDIR /tmp/libnftnl
ARG name
ARG version
RUN <<EOF
check-clone "https://git.netfilter.org/libnftnl.git" "libnftnl-${version}"
git clone --config advice.detachedHead=false --depth 1 --branch "libnftnl-${version}" https://git.netfilter.org/libnftnl.git .
EOF
RUN <<EOF
export PKG_CONFIG_PATH="/lib/pkgconfig:${PKG_CONFIG_PATH}"
./autogen.sh
./configure \
    --prefix="${prefix}" \
    --enable-static=yes \
    --enable-shared=yes
make -j$(nproc)
make install
EOF