#syntax=docker/dockerfile

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04 AS ubuntu2604

FROM ubuntu2604 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/ruuda/rcl/releases/download/v${version}/rcl-${version}-${arch}-unknown-linux-gnu"
filename="$( basename "${url}" )"

check-download "${url}"
check-github-release-asset "ruuda/rcl" "v${version}" "${filename}"

curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" "${url}"
install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/rcl"
EOF
