#syntax=docker/dockerfile:1.9.0@sha256:fe40cf4e92cd0c467be2cfc30657a680ae2398318afd50b0c80585784c604f28

FROM ghcr.io/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "git-lfs/git-lfs" "v${version}" "git-lfs-linux-${alt_arch}-v${version}.tar.gz"
curl --silent --show-error --location --fail "https://github.com/git-lfs/git-lfs/releases/download/v${version}/git-lfs-linux-${alt_arch}-v${version}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/share/" --strip-components=1 --no-same-owner \
    git-lfs-${version}/git-lfs \
    git-lfs-${version}/man
mv "${prefix}/share/git-lfs" "${prefix}/bin/"

"${prefix}/bin/git-lfs" completion bash >"${prefix}/share/bash-completion/completions/git-lfs"
"${prefix}/bin/git-lfs" completion fish >"${prefix}/share/fish/vendor_completions.d/git-lfs.fish"
"${prefix}/bin/git-lfs" completion zsh >"${prefix}/share/zsh/vendor-completions/_git-lfs"
EOF