#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM ghcr.io/uniget-org/tools/go:latest AS go

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=go / /usr/local/
WORKDIR /go/src/github.com/dimonomid/nerdlog
ARG name
ARG version
RUN --mount=type=cache,target=/root/go/pkg/mod <<EOF
check-clone "https://github.com/dimonomid/nerdlog" "v${version}"
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/dimonomid/nerdlog .
go build \
    -ldflags "\
        -X 'github.com/dimonomid/nerdlog/version.version=${version}' \
        -X 'github.com/dimonomid/nerdlog/version.commit=$(git rev-parse HEAD)' \
        -X 'github.com/dimonomid/nerdlog/version.date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")' \
        -X 'github.com/dimonomid/nerdlog/version.builtBy=uniget' \
    " \
    -o "${prefix}/bin/nerdlog" \
    ./cmd/nerdlog
EOF