#syntax=docker/dockerfile:1.7.1

FROM ghcr.io/uniget-org/images/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "cert-manager/cert-manager" "v${version}" "cmctl-linux-${alt_arch}.tar.gz"
curl --silent --location --fail "https://github.com/cert-manager/cert-manager/releases/download/v${version}/cmctl-linux-${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/bin" --no-same-owner \
    cmctl

check-github-release-asset "cert-manager/cert-manager" "v${version}" "kubectl-cert_manager-linux-${alt_arch}.tar.gz"
curl --silent --location --fail "https://github.com/cert-manager/cert-manager/releases/download/v${version}/kubectl-cert_manager-linux-${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/bin" --no-same-owner \
    kubectl-cert_manager

"${prefix}/bin/cmctl" completion bash >"${prefix}/share/bash-completion/completions/cmctl"
"${prefix}/bin/cmctl" completion fish >"${prefix}/share/fish/vendor_completions.d/cmctl.fish"
"${prefix}/bin/cmctl" completion zsh >"${prefix}/share/zsh/vendor-completions/_cmctl"
EOF