#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM registry.gitlab.com/uniget-org/images/build-base:3.24 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
RUN <<EOF
apk add \
    bison \
    libevent-static \
    libevent-dev \
    ncurses-static \
    pkgconf
EOF
WORKDIR /tmp/tmux
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/tmux/tmux/releases/download/${version}/tmux-${version}.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "tmux/tmux" "${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --strip-components=1 --no-same-owner
EOF
RUN <<EOF
./configure --prefix="${prefix}" --enable-static
make -j$(nproc)
make install
EOF
