#syntax=docker/dockerfile

FROM registry.gitlab.com/uniget-org/images/build-essential:26.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/apt <<EOF
apt-get update
apt-get -y install --no-install-recommends \
    libneon27-dev
EOF
WORKDIR /tmp/davfs2
RUN <<EOF
url="https://github.com/alisarctl/davfs2/releases/download/rel-${version//./-}/davfs2-${version}.tar.gz"
curl --silent --show-error --location --fail "${url}" \
| tar --extract --gzip --strip-components=1
./configure --prefix="${prefix}"
make -j$(nproc)
make install
EOF