#syntax=docker/dockerfile:1.25.0@sha256:0adf442eae370b6087e08edc7c50b552d80ddf261576f4ebd6421006b2461f12

FROM ghcr.io/uniget-org/tools/python-3.12:latest AS python
FROM ghcr.io/uniget-org/tools/shiv:latest AS shiv

#FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
FROM registry.gitlab.com/uniget-org/images/build-essential:26.04@sha256:0b5fe6bafd59a2d7777c0ca188f6973d95dbd270d79c96c23473fb55efe57a99 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
COPY --link --from=python / /usr/local/
COPY --link --from=shiv / /usr/local/
RUN --mount=type=cache,target=/var/cache/apt <<EOF
apt-get update
apt-get -y install --no-install-recommends \
    clang
EOF
RUN --mount=type=cache,target=/root/.cache/pip <<EOF
shiv --output-file "${prefix}/bin/openllm" --console-script openllm "openllm==${version}"
EOF