#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM ghcr.io/uniget-org/tools/python-3.12:latest AS python
FROM ghcr.io/uniget-org/tools/shiv:latest AS shiv

#FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
FROM registry.gitlab.com/uniget-org/images/build-essential:26.04@sha256:e01323d1547d9efab438820253dd234aa6b45d03b2e067dcc710cb5caa7a37a9 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
COPY --link --from=python / /usr/local/
COPY --link --from=shiv / /usr/local/
RUN --mount=type=cache,target=/var/cache/apt <<EOF
apt-get update
apt-get -y install --no-install-recommends \
    clang
EOF
RUN --mount=type=cache,target=/root/.cache/pip <<EOF
shiv --output-file "${prefix}/bin/openllm" --console-script openllm "openllm==${version}"
EOF