#syntax=docker/dockerfile:1.8.0

FROM ghcr.io/uniget-org/tools/make:latest AS make

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:178a01206383923b589ecfe3bace55431c4b8528086909ffcdc1ef88de4da10f AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=make / /usr/local/
WORKDIR /tmp/wslu
ARG name
ARG version
RUN <<EOF
curl --silent --show-error --location --fail "https://github.com/wslutilities/wslu/archive/refs/tags/v${version}.tar.gz" \
| tar --extract --gzip --strip-components=1
make -j$(nproc) all
make install "DESTDIR=${prefix}" "PREFIX="
EOF