#syntax=docker/dockerfile:1.17.1@sha256:38387523653efa0039f8e1c89bb74a30504e76ee9f565e25c9a09841f9427b05

FROM ghcr.io/uniget-org/tools/go:latest AS go

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=go / /usr/local/
WORKDIR /go/src/github.com/valyentdev/cli
ARG name
ARG version
RUN --mount=type=cache,target=/root/go/pkg/mod <<EOF
check-clone "https://github.com/valyentdev/cli" "v${version}"
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/valyentdev/cli .
go build -o "${prefix}/bin/valyent" .

"${prefix}/bin/valyent" completion bash >"${prefix}/share/bash-completion/completions/valyent"
"${prefix}/bin/valyent" completion fish >"${prefix}/share/fish/vendor_completions.d/valyent.fish"
"${prefix}/bin/valyent" completion zsh >"${prefix}/share/zsh/vendor-completions/_valyent"
EOF