#syntax=docker/dockerfile:1.23.0@sha256:2780b5c3bab67f1f76c781860de469442999ed1a0d7992a5efdf2cffc0e3d769

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:99a2bccd1ad68bfc5b1d1eb356cf54b7dd94e45c5216b89c87b9e21c70e12b9f AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
COPY --chmod=0755 install-docker-init.sh "/uniget_bootstrap/bin/"
RUN <<EOF
DOCKER_DESKTOP_VERSION="$(
    echo "${version}" \
    | cut -d- -f2
)"
sed -i "s/docker_desktop_version:=DD_VERSION/docker_desktop_version:=${DOCKER_DESKTOP_VERSION}/" "/uniget_bootstrap/bin/install-docker-init.sh"
EOF