#syntax=docker/dockerfile:1.6.0

FROM ghcr.io/uniget-org/images/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "csdev/ezghsa" "v${version}" "ezghsa-${version}-linux-${alt_arch}"
curl --silent --location --fail --output "${prefix}/bin/ezghsa" \
    "https://github.com/csdev/ezghsa/releases/download/v${version}/ezghsa-${version}-linux-${alt_arch}"
chmod +x "${prefix}/bin/ezghsa"
EOF