#syntax=docker/dockerfile:1.7.0

FROM ghcr.io/uniget-org/images/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
mkdir -p "${prefix}/opt/scala"
curl --silent --location --fail "https://downloads.lightbend.com/scala/${version}/scala-${version}.tgz" \
| tar --extract --gzip --directory="${prefix}/opt/scala" --strip-components=1 --no-same-owner
ln --symbolic --relative --force "${prefix}/opt/scala/bin/scala" "${prefix}/bin/scala"
EOF