#syntax=docker/dockerfile:1.10.0@sha256:865e5dd094beca432e8c0a1d5e1c465db5f998dca4e439981029b3b81fb39ed5

FROM ghcr.io/uniget-org/tools/make:latest AS make

FROM registry.gitlab.com/uniget-org/images/build-base:3.20 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
RUN --mount=type=cache,target=/var/cache/apk <<EOF
apk add --update-cache \
    linux-headers
EOF
COPY --link --from=make / /usr/local/
WORKDIR /tmp/libmnl
ARG name
ARG version
RUN <<EOF
check-clone "https://git.netfilter.org/libmnl" "libmnl-${version}"
git clone --config advice.detachedHead=false --depth 1 --branch "libmnl-${version}" git://git.netfilter.org/libmnl .
EOF
RUN <<EOF
./autogen.sh
./configure \
    --prefix="${prefix}" \
    --enable-static=yes \
    --enable-shared=yes
make -j$(nproc)
make install
EOF