#syntax=docker/dockerfile:1.27.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM ghcr.io/uniget-org/tools/cosign:latest AS cosign

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=cosign / /usr/local/
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://dl.k8s.io/release/v${version}/bin/linux/${alt_arch}/kube-scheduler"
filename="$( basename "${url}" )"

check-download "${url}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

echo "Verifying keyless signature for kube-scheduler"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}.sig" \
    "${url}.sig"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}.cert" \
    "${url}.cert"

COSIGN_EXPERIMENTAL=1 cosign verify-blob "${uniget_cache_download}/${filename}" \
    --signature "${uniget_cache_download}/${filename}.sig" \
    --certificate "${uniget_cache_download}/${filename}.cert" \
    --certificate-oidc-issuer https://accounts.google.com \
    --certificate-identity krel-staging@k8s-releng-prod.iam.gserviceaccount.com

install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/kube-scheduler"
EOF