#syntax=docker/dockerfile:1.6.0

FROM ghcr.io/uniget-org/tools/cosign:latest AS cosign

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:da13a27933fac882122e16292dad3e4869a53dbbc52a73b4a5ddfbcde6902a99 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --from=cosign / /usr/local/
ARG name
ARG version
RUN <<EOF
curl --silent --location --fail --output "${prefix}/bin/kube-scheduler" \
    "https://storage.googleapis.com/kubernetes-release/release/v${version}/bin/linux/${alt_arch}/kube-scheduler"
chmod +x "${prefix}/bin/kube-scheduler"

echo "Verifying keyless signature for kube-scheduler"
curl --silent --location --fail --output "/tmp/kube-scheduler.sig" \
    "https://dl.k8s.io/release/v${version}/bin/linux/${alt_arch}/kube-scheduler.sig"
curl --silent --location --fail --output "/tmp/kube-scheduler.cert" \
    "https://dl.k8s.io/release/v${version}/bin/linux/${alt_arch}/kube-scheduler.cert"
COSIGN_EXPERIMENTAL=1 cosign verify-blob "${prefix}/bin/kube-scheduler" \
    --signature "/tmp/kube-scheduler.sig" \
    --certificate "/tmp/kube-scheduler.cert" \
    --certificate-oidc-issuer https://accounts.google.com \
    --certificate-identity krel-staging@k8s-releng-prod.iam.gserviceaccount.com
rm -f \
    "/tmp/kube-scheduler.sig" \
    "/tmp/kube-scheduler.cert"
EOF