#syntax=docker/dockerfile:1.6.0

FROM ghcr.io/uniget-org/images/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]

ARG name
ARG version

RUN <<EOF
curl --silent --location --fail --output "${prefix}/bin/lectl" \
    "https://github.com/sahsanu/lectl/raw/v${version}/lectl"
chmod +x "${prefix}/bin/lectl"
EOF