#syntax=docker/dockerfile:1.17.0@sha256:e2dd261f92e4b763d789984f6eab84be66ab4f5f08052316d8eb8f173593acf7

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
echo "### Setting suffix based on architecture"
case "${arch}" in
    x86_64)
        export arch_suffix=musl
        ;;
    aarch64)
        export arch_suffix=gnu
        ;;
    *)
        echo "ERROR: Unsupported architecture ${arch}."
        exit 1
        ;;
esac
echo "    Using ${arch_suffix}"

url="https://github.com/dathere/qsv/releases/download/${version}/qsv-${version}-${arch}-unknown-linux-${arch_suffix}.zip"
filename="$(basename "${url}")"

check-github-release-asset "dathere/qsv" "${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

unzip -t "${uniget_cache_download}/${filename}"
unzip -q -o -d "${prefix}/bin" "${uniget_cache_download}/${filename}" \
    qsv
EOF