#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM ghcr.io/uniget-org/tools/make:latest AS make

FROM registry.gitlab.com/uniget-org/images/build-base:3.24@sha256:bfcf3e99a47ac1b07f9dd40db914d12a3a15f5b886a9e7f35a60be58c9d294bc AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
RUN --mount=type=cache,target=/var/cache/apk <<EOF
apk add --update-cache \
    zlib-dev \
    zlib-static
EOF
COPY --link --from=make / /usr/local/
WORKDIR /tmp/pigz
ARG name
ARG version
RUN <<EOF
check-clone https://github.com/madler/pigz "v${version}"
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/madler/pigz .
make -j$(nproc) all LDFLAGS=-static
cp pigz pigzj pigzt pigzn "${prefix}/bin/"
cp pigz.1 "${prefix}/share/man/man1/"
EOF