#syntax=docker/dockerfile

FROM rust:alpine AS build
RUN <<EOF
apk update
apk add \
    build-base \
    git \
    bash \
    openssl-dev \
    openssl-libs-static \
    zstd-dev \
    zlib-dev \
    jitterentropy-library-dev \
    protobuf \
    protobuf-dev
EOF
WORKDIR /tmp/github.com/calfonso/rusternetes
ARG version
RUN <<EOF
git clone https://github.com/calfonso/rusternetes .
git checkout "${version}"
cargo build --release --target "$(uname -m)-unknown-linux-musl"
cp "target/$(uname -m)-unknown-linux-musl/release/api-server" "/usr/local/bin/"
cp "target/$(uname -m)-unknown-linux-musl/release/controller-manager" "/usr/local/bin/"
cp "target/$(uname -m)-unknown-linux-musl/release/kube-proxy" "/usr/local/bin/"
cp "target/$(uname -m)-unknown-linux-musl/release/kubectl" "/usr/local/bin/"
cp "target/$(uname -m)-unknown-linux-musl/release/kubelet" "/usr/local/bin/"
cp "target/$(uname -m)-unknown-linux-musl/release/rusternetes" "/usr/local/bin/"
cp "target/$(uname -m)-unknown-linux-musl/release/scheduler" "/usr/local/bin/"
EOF

FROM registry.gitlab.com/uniget-org/images/build-base:3.24 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --from=build "/usr/local/bin/api-server" "/uniget_bootstrap/bin/"
COPY --from=build "/usr/local/bin/controller-manager" "/uniget_bootstrap/bin/"
COPY --from=build "/usr/local/bin/kube-proxy" "/uniget_bootstrap/bin/"
COPY --from=build "/usr/local/bin/kubectl" "/uniget_bootstrap/bin/"
COPY --from=build "/usr/local/bin/kubelet" "/uniget_bootstrap/bin/"
COPY --from=build "/usr/local/bin/rusternetes" "/uniget_bootstrap/bin/"
COPY --from=build "/usr/local/bin/scheduler" "/uniget_bootstrap/bin/"
RUN <<EOF
"${prefix}/bin/kubectl" completion bash >"${prefix}/share/bash-completion/completions/kubectl"
"${prefix}/bin/kubectl" completion fish >"${prefix}/share/fish/vendor_completions.d/kubectl.fish"
"${prefix}/bin/kubectl" completion zsh >"${prefix}/share/zsh/vendor-completions/_kubectl"
EOF