#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM registry.gitlab.com/uniget-org/images/build-base:3.24 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
apk update
# libssl-dev: required for TLS support in Rust crates
# protobuf-compiler: provides protoc for compiling .proto files
# libprotobuf-dev: provides well-known proto types (e.g. google/protobuf/any.proto)
apk add \
    rust \
    cargo \
    musl-dev \
    openssl-dev \
    openssl-libs-static \
    libzstd-dev \
    zlib1g-dev \
    libjitterentropy3-dev \
    protobuf-compiler \
    libprotobuf-dev
EOF
WORKDIR /tmp/github.com/calfonso/rusternetes
RUN <<EOF
git clone https://github.com/calfonso/rusternetes .
git checkout "${version}"
cargo build --release --target "${arch}-unknown-linux-musl"
cp "target/${arch}-unknown-linux-musl/release/api-server" "${prefix}/bin/"
cp "target/${arch}-unknown-linux-musl/release/controller-manager" "${prefix}/bin/"
cp "target/${arch}-unknown-linux-musl/release/kube-proxy" "${prefix}/bin/"
cp "target/${arch}-unknown-linux-musl/release/kubectl" "${prefix}/bin/"
cp "target/${arch}-unknown-linux-musl/release/kubelet" "${prefix}/bin/"
cp "target/${arch}-unknown-linux-musl/release/rusternetes" "${prefix}/bin/"
cp "target/${arch}-unknown-linux-musl/release/scheduler" "${prefix}/bin/"
EOF
RUN <<EOF
"${prefix}/bin/kubectl" completion bash >"${prefix}/share/bash-completion/completions/kubectl"
"${prefix}/bin/kubectl" completion fish >"${prefix}/share/fish/vendor_completions.d/kubectl.fish"
"${prefix}/bin/kubectl" completion zsh >"${prefix}/share/zsh/vendor-completions/_kubectl"
EOF