#syntax=docker/dockerfile:1.25.0@sha256:0adf442eae370b6087e08edc7c50b552d80ddf261576f4ebd6421006b2461f12

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:059b11407572b2fd733e7bcd1c528852394d7fe1abef7119a1a97356983cab76 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/Code-Hex/Neo-cowsay/releases/download/v${version}/cowsay_${version}_Linux_x86_64.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "Code-Hex/Neo-cowsay" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin/" --no-same-owner \
    cowsay \
    cowthink
curl --silent --show-error --location --fail --output "${prefix}/share/man/man1/cowsay.1" \
    "https://github.com/Code-Hex/Neo-cowsay/raw/v${version}/doc/cowsay.1"
curl --silent --show-error --location --fail "https://github.com/Code-Hex/Neo-cowsay/archive/refs/tags/v${version}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/share" --strip-components=1 --no-same-owner \
    "Neo-cowsay-${version}/cows"
EOF