#syntax=docker/dockerfile:1.8.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:6ff62e5ed6b1c33f0ae1644692a354281534a37ec4d752cf480850e19a94d16d AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
echo "### Setting architecture string for ${TARGETPLATFORM}"
case "${arch}" in
    x86_64)
        export arch_suffix="${arch}"
        ;;
    aarch64)
        export arch_suffix="${alt_arch}"
        ;;
    *)
        echo "ERROR: Unsupported architecture ${arch}."
        exit 1
        ;;
esac
echo "    Using ${arch_suffix}"

check-github-release-asset "ibuildthecloud/catgpt" "v${version}" "catgpt_Linux_${arch_suffix}.tar.gz"
curl --silent --show-error --location --fail "https://github.com/ibuildthecloud/catgpt/releases/download/v${version}/catgpt_Linux_${arch_suffix}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/bin/" --strip-components=1 --no-same-owner \
    "catgpt_Linux_${arch_suffix}/catgpt"
EOF