#syntax=docker/dockerfile:1.27.0@sha256:bde3983e9c939224420ddaf6b784cc30e09b035a4dea01f581230c50809f372e

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/rancher/fleet/releases/download/v${version}/fleet-linux-${alt_arch}"
filename="$( basename "${url}" )"

check-github-release-asset "rancher/fleet" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/fleet"


check-github-release-asset "rancher/fleet" "v${version}" "fleetagent-linux-${alt_arch}"
curl --silent --show-error --location --fail --output "${prefix}/bin/fleetagent" \
    "https://github.com/rancher/fleet/releases/download/v${version}/fleetagent-linux-${alt_arch}"
chmod +x "${prefix}/bin/fleetagent"

check-github-release-asset "rancher/fleet" "v${version}" "fleetcontroller-linux-${alt_arch}"
curl --silent --show-error --location --fail --output "${prefix}/bin/fleetcontroller" \
    "https://github.com/rancher/fleet/releases/download/v${version}/fleetcontroller-linux-${alt_arch}"
chmod +x "${prefix}/bin/fleetcontroller"

curl --silent --show-error --location --fail "https://github.com/rancher/fleet/releases/download/v${version}/fleet-crd-${version}.tgz" \
| tar --extract --gzip --directory="${prefix}/share/" --no-same-owner

curl --silent --show-error --location --fail "https://github.com/rancher/fleet/releases/download/v${version}/fleet-agent-${version}.tgz" \
| tar --extract --gzip --directory="${prefix}/share/" --no-same-owner

curl --silent --show-error --location --fail "https://github.com/rancher/fleet/releases/download/v${version}/fleet-${version}.tgz" \
| tar --extract --gzip --directory="${prefix}/share/" --no-same-owner

"${prefix}/bin/fleet" completion bash >"${prefix}/share/bash-completion/completions/fleet"
"${prefix}/bin/fleet" completion fish >"${prefix}/share/fish/vendor_completions.d/fleet.fish"
"${prefix}/bin/fleet" completion zsh >"${prefix}/share/zsh/vendor-completions/_fleet"
EOF