#syntax=docker/dockerfile:1.7.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:98429d8ee1c7cf7d06f65b692870d983f0965f1c1cdffa1dd04ef878b56293b6 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "rancher/fleet" "v${version}" "fleet-linux-${alt_arch}"
curl --silent --location --fail --output "${prefix}/bin/fleet" \
    "https://github.com/rancher/fleet/releases/download/v${version}/fleet-linux-${alt_arch}"
chmod +x "${prefix}/bin/fleet"

check-github-release-asset "rancher/fleet" "v${version}" "fleetagent-linux-${alt_arch}"
curl --silent --location --fail --output "${prefix}/bin/fleetagent" \
    "https://github.com/rancher/fleet/releases/download/v${version}/fleetagent-linux-${alt_arch}"
chmod +x "${prefix}/bin/fleetagent"

check-github-release-asset "rancher/fleet" "v${version}" "fleetcontroller-linux-${alt_arch}"
curl --silent --location --fail --output "${prefix}/bin/fleetcontroller" \
    "https://github.com/rancher/fleet/releases/download/v${version}/fleetcontroller-linux-${alt_arch}"
chmod +x "${prefix}/bin/fleetcontroller"

curl --silent --location --fail "https://github.com/rancher/fleet/releases/download/v${version}/fleet-crd-${version}.tgz" \
| tar --extract --gzip --directory="${prefix}/share/" --no-same-owner

curl --silent --location --fail "https://github.com/rancher/fleet/releases/download/v${version}/fleet-agent-${version}.tgz" \
| tar --extract --gzip --directory="${prefix}/share/" --no-same-owner

curl --silent --location --fail "https://github.com/rancher/fleet/releases/download/v${version}/fleet-${version}.tgz" \
| tar --extract --gzip --directory="${prefix}/share/" --no-same-owner

"${prefix}/bin/fleet" completion bash >"${prefix}/share/bash-completion/completions/fleet"
"${prefix}/bin/fleet" completion fish >"${prefix}/share/fish/vendor_completions.d/fleet.fish"
"${prefix}/bin/fleet" completion zsh >"${prefix}/share/zsh/vendor-completions/_fleet"
EOF