# yaml-language-server: $schema=https://tools.uniget.dev/schema.yaml
name: docker-compose-v1
description: Define and run multi-container applications with Docker (v1)
license:
  name: Apache License 2.0
  link: https://github.com/docker/compose/blob/main/LICENSE
homepage: https://docs.docker.com/compose/
repository: https://github.com/docker/compose
version: "1.29.2"
tags:
- org/docker
- standard/docker
- container/compose
- standard/compose
- type/cli
- lang/python
- docker
check: ${binary} version --short
platforms:
- linux/amd64
renovate:
  datasource: github-releases
  package: docker/compose
  extractVersion: ^(?<version>1\.\d+\.\d+)$
binary: docker-compose
conflicts_with:
- docker-compose-switch
