#syntax=docker/dockerfile:1.15.1@sha256:05e0ad437efefcf144bfbf9d7f728c17818408e6d01432d9e264ef958bbd52f3

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/metalbear-co/mirrord/releases/download/${version}/mirrord_linux_${arch}"
filename="$( basename "${url}" )"

check-github-release-asset "metalbear-co/mirrord" "${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/mirrord"
EOF
RUN <<EOF
"${prefix}/bin/mirrord" completions bash >"${prefix}/share/bash-completion/completions/mirrord"
"${prefix}/bin/mirrord" completions fish >"${prefix}/share/fish/vendor_completions.d/mirrord.fish"
"${prefix}/bin/mirrord" completions zsh >"${prefix}/share/zsh/vendor-completions/_mirrord"
EOF