#syntax=docker/dockerfile:1.6.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:da13a27933fac882122e16292dad3e4869a53dbbc52a73b4a5ddfbcde6902a99 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "mvisonneau/gitlab-ci-pipelines-exporter" "v${version}" "gitlab-ci-pipelines-exporter_v${version}_linux_${alt_arch}.tar.gz"
curl --silent --location --fail "https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/download/v${version}/gitlab-ci-pipelines-exporter_v${version}_linux_${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/bin/" --no-same-owner \
    gitlab-ci-pipelines-exporter \
    helpers

mv "${prefix}/bin/helpers/autocomplete/bash" "${prefix}/share/bash-completion/completions/gitlab-ci-pipelines-exporter"
mv "${prefix}/bin/helpers/autocomplete/zsh" "${prefix}/share/zsh/vendor-completions/_gitlab-ci-pipelines-exporter"
mv "${prefix}/bin/helpers/manpages/gitlab-ci-pipelines-exporter.1.gz" "${prefix}/share/man/man1/"
rm -rf "${prefix}/bin/helpers"
EOF
