#syntax=docker/dockerfile:1.27.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/download/v${version}/gitlab-ci-pipelines-exporter_v${version}_linux_${alt_arch}.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "mvisonneau/gitlab-ci-pipelines-exporter" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin/" --no-same-owner \
    gitlab-ci-pipelines-exporter \
    helpers

mv "${prefix}/bin/helpers/autocomplete/bash" "${prefix}/share/bash-completion/completions/gitlab-ci-pipelines-exporter"
mv "${prefix}/bin/helpers/autocomplete/zsh" "${prefix}/share/zsh/vendor-completions/_gitlab-ci-pipelines-exporter"
rm -rf "${prefix}/bin/helpers"
EOF
COPY gitlab-ci-pipelines-exporter.yaml /uniget_bootstrap/etc/gitlab-ci-pipelines-exporter/
