#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM ghcr.io/uniget-org/tools/python-3.12:latest AS python
FROM ghcr.io/uniget-org/tools/pipx:latest AS pipx

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:b0b654de801604e256237f2c27a907a4b61b59ebd83423ad0e0e465c0a3ba9cd AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=python / /usr/local/
COPY --link --from=pipx / /usr/local/
ARG name
ARG version
RUN --mount=type=cache,target=/root/.cache/pip <<EOF
export PIPX_HOME="${prefix}/libexec/pipx"
export PIPX_BIN_DIR="${prefix}/bin"
pipx install "glances==${version}"
pipx-fix-venv-pyvenv-cfg glances
ln --symbolic --relative --force "${prefix}/libexec/pipx/venvs/glances/bin/glances" "${prefix}/bin/glances"
mv "${prefix}/libexec/pipx/venvs/glances/bin/glances" "${prefix}/libexec/pipx/venvs/glances/bin/glances.go-template"
sed -i "s|#\!${prefix}|#\!{{ .Target }}|" "${prefix}/libexec/pipx/venvs/glances/bin/glances.go-template"
EOF
