#syntax=docker/dockerfile:1.6.0

FROM ghcr.io/uniget-org/images/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
COPY fuse-overlayfs-snapshotter.service /uniget_bootstrap/etc/systemd/system/
RUN <<EOF
check-github-release-asset "containerd/fuse-overlayfs-snapshotter" "v${version}" "containerd-fuse-overlayfs-${version}-linux-${alt_arch}.tar.gz"
curl --silent --location --fail "https://github.com/containerd/fuse-overlayfs-snapshotter/releases/download/v${version}/containerd-fuse-overlayfs-${version}-linux-${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/bin" --no-same-owner
EOF