#syntax=docker/dockerfile:1.25.0@sha256:0adf442eae370b6087e08edc7c50b552d80ddf261576f4ebd6421006b2461f12

FROM ghcr.io/uniget-org/tools/make:latest AS make

FROM registry.gitlab.com/uniget-org/images/build-essential:26.04@sha256:e01323d1547d9efab438820253dd234aa6b45d03b2e067dcc710cb5caa7a37a9 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=make / /usr/local/

WORKDIR /uniget_bootstrap/libexec/pyenv
ARG name
ARG version
RUN <<EOF
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://github.com/pyenv/pyenv .
src/configure
make -C src
EOF

RUN <<EOF
cp man/man1/pyenv.1 "${prefix}/share/man/man1/"
ln --symbolic --relative --force "${prefix}/libexec/pyenv/bin/pyenv" "${prefix}/bin/pyenv"
cp completions/pyenv.bash "${prefix}/share/bash-completion/completions/pyenv"
cp completions/pyenv.fish "${prefix}/share/fish/vendor_completions.d/pyenv.fish"
cp completions/pyenv.zsh "${prefix}/share/zsh/vendor-completions/_pyenv"
EOF

RUN <<EOF
git clone https://github.com/pyenv/pyenv-doctor.git "${prefix}/libexec/pyenv/plugins/pyenv-doctor"
git clone https://github.com/pyenv/pyenv-virtualenv.git "${prefix}/libexec/pyenv/plugins/pyenv-virtualenv"
EOF
