#syntax=docker/dockerfile:1.27.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM ghcr.io/uniget-org/tools/make:latest AS make
FROM ghcr.io/uniget-org/tools/go:latest AS go

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:0e9f873df6c03f698322571475f367a694d7eff9077e5019ae764e5106a6da16 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
COPY --link --from=go / /usr/local/
COPY --link --from=make / /usr/local/
WORKDIR /go/src/gitlab.com/gitlab-org/step-runner
ARG name
ARG version
ARG GOBIN=/usr/local/bin
RUN --mount=type=cache,target=/root/go/pkg/mod <<EOF
check-clone "https://gitlab.com/gitlab-org/step-runner" "v${version}"
git clone -q --config advice.detachedHead=false --depth 1 --branch "v${version}" https://gitlab.com/gitlab-org/step-runner .
make build
cp "out/bin/step-runner-linux-${alt_arch}" "${prefix}/bin/step-runner"
EOF
RUN <<EOF
"${prefix}/bin/step-runner" completion bash >"${prefix}/share/bash-completion/completions/step-runner"
"${prefix}/bin/step-runner" completion fish >"${prefix}/share/fish/vendor_completions.d/step-runner.fish"
"${prefix}/bin/step-runner" completion zsh >"${prefix}/share/zsh/vendor-completions/_step-runner"
EOF