#syntax=docker/dockerfile:1.8.1

FROM ghcr.io/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "micro/micro" "v${version}" "micro-v${version}-linux-${alt_arch}.tar.gz"
curl --silent --show-error --location --fail "https://github.com/micro/micro/releases/download/v${version}/micro-v${version}-linux-${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/bin/" --no-same-owner \
    micro

curl --silent --fail --show-error --location --output "${prefix}/etc/systemd/system/micro.service.go-template" \
    "https://github.com/micro/micro/raw/v${version}/scripts/systemd/micro.service"
sed -i -E "s|^ExecStart=/usr/local/bin/microd|ExecStart={{ .Target }}/bin/micro|" "${prefix}/etc/systemd/system/micro.service.go-template"
EOF