#syntax=docker/dockerfile:1.15.1@sha256:05e0ad437efefcf144bfbf9d7f728c17818408e6d01432d9e264ef958bbd52f3

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
WORKDIR /uniget_bootstrap/share/fonts/NerdFonts
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
for font in CascadiaCode; do
    url="https://github.com/ryanoasis/nerd-fonts/releases/download/v${version}/${font}.zip"
    filename="$(basename "${url}")"

    check-github-release-asset "ryanoasis/nerd-fonts" "v${version}" "${filename}"
    curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
        "${url}"
    unzip -q -o "${uniget_cache_download}/${filename}"
done
EOF
