#syntax=docker/dockerfile:1.21.0@sha256:27f9262d43452075f3c410287a2c43f5ef1bf7ec2bb06e8c9eeb1b8d453087bc

FROM ghcr.io/uniget-org/tools/python-3.12:latest AS python
FROM ghcr.io/uniget-org/tools/pipx:latest AS pipx

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=python / /usr/local/
COPY --link --from=pipx / /usr/local/
ARG name
ARG version
RUN --mount=type=cache,target=/root/.cache/pip <<EOF
export PIPX_HOME="${prefix}/libexec/pipx"
export PIPX_BIN_DIR="${prefix}/bin"
pipx install holmesgpt=="${version}"
pipx-fix-venv-pyvenv-cfg holmesgpt
ln --symbolic --relative --force "${prefix}/libexec/pipx/venvs/holmesgpt/bin/holmes" "${prefix}/bin/"
sed -i "s|#\!${prefix}/|#\!/|" "${prefix}/libexec/pipx/venvs/holmesgpt/bin/holmes"
EOF