#syntax=docker/dockerfile:1.21.0@sha256:26147acbda4f14c5add9946e2fd2ed543fc402884fd75146bd342a7f6271dc1d

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]

COPY --chmod=0755 \
    init.sh \
    check-download.sh \
    check-github-release-asset.sh \
    check-clone.sh \
    pipx-fix-pyvenv-cfg.sh \
    /uniget_bootstrap/etc/profile.d/
