#syntax=docker/dockerfile:1.7.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:98429d8ee1c7cf7d06f65b692870d983f0965f1c1cdffa1dd04ef878b56293b6 AS prepare
COPY --chmod=0755 \
    init.sh \
    check-download.sh \
    check-github-release-asset.sh \
    check-clone.sh \
    /uniget_bootstrap/etc/profile.d/
