#syntax=docker/dockerfile:1.6.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:da13a27933fac882122e16292dad3e4869a53dbbc52a73b4a5ddfbcde6902a99 AS prepare
COPY --chmod=0755 \
    init.sh \
    check-download.sh \
    check-github-release-asset.sh \
    check-clone.sh \
    /uniget_bootstrap/etc/profile.d/
