#syntax=docker/dockerfile:1.8.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:dc6c0030ff36d8c83922c5c24088c89faf3cb4f0b21540e231f35408453b76c3 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "anchore/grype" "v${version}" "grype_${version}_linux_${alt_arch}.tar.gz"
curl --silent --show-error --location --fail "https://github.com/anchore/grype/releases/download/v${version}/grype_${version}_linux_${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/bin" --no-same-owner \
    grype
"${prefix}/bin/grype" completion bash >"${prefix}/share/bash-completion/completions/grype"
"${prefix}/bin/grype" completion fish >"${prefix}/share/fish/vendor_completions.d/grype.fish"
"${prefix}/bin/grype" completion zsh >"${prefix}/share/zsh/vendor-completions/_grype"
EOF