#syntax=docker/dockerfile:1.9.0@sha256:fe40cf4e92cd0c467be2cfc30657a680ae2398318afd50b0c80585784c604f28

FROM ghcr.io/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
curl --silent --show-error --location --fail "https://github.com/hakimel/reveal.js/archive/refs/tags/${version}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/share/" --no-same-owner
mv "${prefix}/share/reveal.js-${version}" "${prefix}/share/reveal.js"
EOF