#syntax=docker/dockerfile:1.23.0@sha256:4a43a54dd1fedceb30ba47e76cfcf2b47304f4161c0caeac2db1c61804ea3c91

FROM ghcr.io/uniget-org/tools/make:latest AS make
#FROM ghcr.io/uniget-org/tools/curl:latest AS curl

FROM registry.gitlab.com/uniget-org/images/build-base:3.23@sha256:d7cab8026e4d67fc0a7d22c33bcc9246cc29c29a78757c3008e3fc821a4f665b AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
RUN --mount=type=cache,target=/var/cache/apk <<EOF
apk update
apk add \
    curl-dev \
    curl-static
EOF
COPY --link --from=make / /usr/local/
#COPY --link --from=curl / /usr/
WORKDIR /tmp/trurl
ARG name
ARG version
RUN <<EOF
git clone -q --config advice.detachedHead=false --depth 1 --branch "trurl-${version}" https://github.com/curl/trurl .
make
cp trurl "${prefix}/bin/"
EOF