#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM ghcr.io/uniget-org/tools/make:latest AS make
#FROM ghcr.io/uniget-org/tools/curl:latest AS curl

FROM registry.gitlab.com/uniget-org/images/build-base:3.23@sha256:f7249e6aa6e7ef57669af5bce04f734a4ad7395f3dc6df76dadf338dfeab8eb5 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
RUN --mount=type=cache,target=/var/cache/apk <<EOF
apk update
apk add \
    curl-dev \
    curl-static
EOF
COPY --link --from=make / /usr/local/
#COPY --link --from=curl / /usr/
WORKDIR /tmp/trurl
ARG name
ARG version
RUN <<EOF
git clone -q --config advice.detachedHead=false --depth 1 --branch "trurl-${version}" https://github.com/curl/trurl .
make
cp trurl "${prefix}/bin/"
EOF