#syntax=docker/dockerfile:1.26.0@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:b0b654de801604e256237f2c27a907a4b61b59ebd83423ad0e0e465c0a3ba9cd AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
case "${alt_arch}" in
    amd64)
        export arch_suffix="x86_64"
        ;;
    arm64)
        export arch_suffix="aarch64"
        ;;
    *)
        echo "ERROR: Unsupported architecture (${alt_arch})."
        exit 1
        ;;
esac
echo "    Using ${arch_suffix}"

url="https://github.com/theryangeary/choose/releases/download/v${version}/choose-${arch_suffix}-unknown-linux-gnu"
filename="$( basename "${url}" )"

check-github-release-asset "theryangeary/choose" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/choose"
EOF
