#syntax=docker/dockerfile:1.7.1

FROM ghcr.io/uniget-org/images/ubuntu:22.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "norouter/norouter" "v${version}" "norouter-Linux-${arch}.tgz"
curl --silent --location --fail "https://github.com/norouter/norouter/releases/download/v${version}/norouter-Linux-${arch}.tgz" \
| tar --extract --gzip --directory="${prefix}/bin" --no-same-owner \
    norouter
EOF