#syntax=docker/dockerfile:1.25.0@sha256:0adf442eae370b6087e08edc7c50b552d80ddf261576f4ebd6421006b2461f12

FROM ghcr.io/uniget-org/tools/node-lts:latest AS node

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04@sha256:cc8b2a023c3777e8b654c98d4bebc58827f8fcb73c4ce309d9ffa01b432954a9 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
COPY --link --from=node / /usr/local/
WORKDIR /uniget_bootstrap/libexec/claude
ARG name
ARG version
RUN <<EOF
npm install \
    --omit=dev \
    "@anthropic-ai/claude-code@${version}"
ln --symbolic --relative --force "${prefix}/libexec/claude/node_modules/.bin/claude" "${prefix}/bin/"
EOF