#syntax=docker/dockerfile:1.6.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:da13a27933fac882122e16292dad3e4869a53dbbc52a73b4a5ddfbcde6902a99 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "carvel-dev/kapp" "v${version}" "kapp-linux-${alt_arch}"
curl --silent --location --fail --output "${prefix}/bin/kapp" \
    "https://github.com/carvel-dev/kapp/releases/download/v${version}/kapp-linux-${alt_arch}"
chmod +x "${prefix}/bin/kapp"
"${prefix}/bin/kapp" completion bash >"${prefix}/share/bash-completion/completions/kapp"
"${prefix}/bin/kapp" completion fish >"${prefix}/share/fish/vendor_completions.d/kapp.fish"
"${prefix}/bin/kapp" completion zsh >"${prefix}/share/zsh/vendor-completions/_kapp"
EOF