name: Automerge

on:
  workflow_run:
    workflows:
    - Test-Linux
    types:
    - completed

jobs:

  foo:
    name: Debug
    runs-on: ubuntu-22.04
  steps:
  - name: Contexts
    env:
      REF: ${{ github.event.workflow_run.head_branch }}
    run: |
      echo "head_branch: ${REF}"

  test:
    name: Renovate
    if: github.event.workflow_run.conclusion == 'success'
    permissions:
      issues: read
      pull-requests: write
    runs-on: ubuntu-22.04
    steps:

    - name: Install uniget
      uses: uniget-org/uniget-action@main
      with:
        prefix: helper
        tools: gojq

    - name: Test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR: ${{ github.event.pull_request.number }}
      run: |
        set -o errexit -o pipefail

        if test -z "${PR}"; then
            echo "ERROR: Failed to retrieve PR number from event payload"
            exit 1
        fi

        PR_JSON="$(
            curl --silent --show-error --fail --header "Authorization: token ${GITHUB_TOKEN}" \
                --url "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR}" \
            | jq --compact-output '.'
        )"
        if ! jq --raw-output '.labels[].name' <<<"${PR_JSON}" | grep -q "^type/renovate$"; then
            echo "PR ${PR} does not have label type/renovate. Skipping"
            exit
        fi

        MERGEABLE_STATE="$(
            jq --raw-output '.mergeable_state' <<<"${PR_JSON}"
        )"
        if test "${MERGEABLE_STATE}" == "unknown"; then
            PR_JSON="$(
                curl --silent --show-error --fail --header "Authorization: token ${GITHUB_TOKEN}" \
                    --url "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR}" \
                | jq --compact-output '.'
            )"
        fi
        case "${MERGEABLE_STATE}" in
            blocked)
                echo "PR ${PR} is blocked and can not be merged"
                exit
                ;;
            clean)
                echo "PR ${PR} is clean and can be merged"
                ;;
            *)
                echo "ERROR: Unknown mergeable_state ${MERGEABLE_STATE} for PR ${PR}"
                exit 1
                ;;
        esac
        echo "PR ${PR} is ready for auto-merge"

        echo "Merging PR ${PR}..."
        if ! curl --silent --show-error --fail --request PUT --header "Authorization: token ${GITHUB_TOKEN}" \
                --url "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR}/merge" \
                --data '{"merge_method": "rebase"}'; then
            echo "ERROR: Unable to merge PR ${PR}"
            continue
        fi
        echo "PR ${PR} has been merged"

        HEAD_REF="$( jq --raw-output '.head.ref' <<<"${PR_JSON}" )"
        echo "HEAD reference in PR ${PR} is ${HEAD_REF}"

        echo "Deleting branch ${HEAD_REF}..."
        if ! curl --silent --show-error --fail --request DELETE --header "Authorization: token ${GITHUB_TOKEN}" \
                --url "https://api.github.com/repos/${GITHUB_REPOSITORY}/git/refs/heads/${HEAD_REF}"; then
            echo "ERROR: Unable to delete branch ${HEAD_REF} from PR ${PR}"
            continue
        fi
        echo "Branch ${HEAD_REF} has been deleted"
