name: Automerge

on:
  workflow_call:

jobs:

  renovate:
    name: Renovate
    permissions:
      issues: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-22.04
    steps:

    - name: Install uniget
      uses: uniget-org/uniget-action@main
      with:
        prefix: helper
        tools: gojq

    - name: Automerge renovate PRs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR: ${{ github.event.pull_request.number }}
      run: |
        set -o errexit -o pipefail

        if test -z "${PR}"; then
            echo "ERROR: Missing PR number"
            exit 1
        fi
        
        echo "Running on PR ${PR}"
        PR_JSON="$(
            curl --silent --show-error --fail --header "Authorization: token ${GITHUB_TOKEN}" \
                --url "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR}"
        )"
        
        if ! jq --raw-output '.labels[].name' <<<"${PR_JSON}" | grep -q "^type/renovate$"; then
            echo "PR ${PR} does not have label type/renovate. Skipping"
            exit
        fi

        MERGEABLE_STATE="$( jq --raw-output '.mergeable_state' <<<"${PR_JSON}" )"
        MAX_ATTEMPTS=3
        ATTEMPT=0
        #test "${ATTEMPT}" -lt "${MAX_ATTEMPTS}"
        while test "${MERGEABLE_STATE}" == "unknown" || test "${MERGEABLE_STATE}" == "null"; do
            echo "Got mergeable state: ${MERGEABLE_STATE}"
            PR_JSON="$(
                curl --silent --show-error --fail --header "Authorization: token ${GITHUB_TOKEN}" \
                    --url "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR}" \
                | jq --compact-output '.'
            )"
            MERGEABLE_STATE="$( jq --raw-output '.mergeable_state' <<<"${PR_JSON}" )"
            ATTEMPT=$(( ATTEMPT + 1 ))
        done
        case "${MERGEABLE_STATE}" in
            blocked)
                echo "PR ${PR} is blocked and can not be merged"
                exit
                ;;
            clean)
                echo "PR ${PR} is clean and can be merged"
                ;;
            *)
                echo "ERROR: Unknown mergeable_state ${MERGEABLE_STATE} for PR ${PR}"
                exit 1
                ;;
        esac
        echo "PR ${PR} is ready for auto-merge"

        echo "Merging PR ${PR}..."
        if ! curl --silent --show-error --fail --request PUT --header "Authorization: token ${GITHUB_TOKEN}" \
                --url "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR}/merge" \
                --data '{"merge_method": "rebase"}'; then
            echo "ERROR: Unable to merge PR ${PR}"
            exit 1
        fi
        echo "PR ${PR} has been merged"

        echo "Fetching head ref for PR ${PR}..."
        REF="$( jq --raw-output '.head.ref' <<<"${PR_JSON}" )"

        echo "Deleting branch ${REF}..."
        if ! curl --silent --show-error --fail --request DELETE --header "Authorization: token ${GITHUB_TOKEN}" \
                --url "https://api.github.com/repos/${GITHUB_REPOSITORY}/git/refs/heads/${REF}"; then
            echo "ERROR: Unable to delete branch ${REF} from PR ${PR}"
            exit 1
        fi
        echo "Branch ${REF} has been deleted"
