name: GHCR cleanup

on:
  schedule:
  - cron: "34 3 * * *"
  push:
    branches:
    - "main"
    paths:
    - ".github/workflows/ghcr-cleanup.yml"
  workflow_dispatch:

jobs:

  test:
    name: GHCR cleanup
    permissions:
      packages: write
    runs-on: ubuntu-24.04
    steps:

    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0

    - name: Install uniget
      uses: uniget-org/uniget-action@2139e70435b6bd47834b7be785d7cb90bf18be6b # v1.0.5
      with:
        prefix: helper

    - name: Cleanup
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        make clean-registry-untagged