name: GHCR cleanup

on:
  schedule:
  - cron: "34 3 * * *"
  push:
    branches:
    - "main"
    paths:
    - ".github/workflows/ghcr-cleanup.yml"
  workflow_dispatch:

jobs:

  test:
    name: GHCR cleanup
    permissions:
      packages: write
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install uniget
      uses: uniget-org/uniget-action@v1
      with:
        prefix: helper

    - name: Cleanup
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        make clean-registry-untagged