name: Renovate-Test
on:
  workflow_dispatch:

concurrency:
  group: renovate-test

jobs:

  renovate:
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:

    #- name: Checkout code
    #  uses: actions/checkout@v4

    - name: Inject custom config
      run: |
        mkdir -p config
        cat <<"EOF" >config/renovate-small.json
        {
          "$schema": "https://docs.renovatebot.com/renovate-schema.json",
          "customManagers": [
            {
              "customType": "regex",
              "datasourceTemplate": "github-tags",
              "depNameTemplate": "moby/moby",
              "extractVersionTemplate": "^v(?<version>.+?)$",
              "fileMatch": ["^tools/docker/manifest.yaml$"],
              "matchStrings": ["version: \"?(?<currentValue>.*?)\"?\\n"]
            }
          ],
          "digest": {"labels": ["bump/digest", "type/renovate"]},
          "enabledManagers": ["custom.regex", "dockerfile"],
          "extends": [
            ":dependencyDashboard",
            ":semanticPrefixFixDepsChoreOthers",
            ":ignoreModulesAndTests",
            ":docker",
            "docker:enableMajor",
            "docker:pinDigests",
            ":ignoreUnstable",
            ":pinVersions",
            ":separateMajorReleases",
            ":separatePatchReleases",
            ":semanticCommits"
          ],
          "major": {"labels": ["bump/major", "type/renovate"]},
          "minor": {"labels": ["bump/minor", "type/renovate"]},
          "packageRules": [
            {
              "matchPackageNames": ["ghcr.io/uniget-org/tools/base"],
              "enabled": false
            }
          ],
          "patch": {"labels": ["bump/patch", "type/renovate"]},
          "pin": {"labels": ["bump/pin", "type/renovate"]},
          "prConcurrentLimit": 0,
          "prHourlyLimit": 0,
          "rebaseLabel": "renovate/rebase",
          "rebaseWhen": "conflicted",
          "recreateWhen": "auto",
          "stopUpdatingLabel": "renovate/stop-updating",
          "timezone": "Europe/Berlin",
          "useBaseBranchConfig": "merge"
        }
        EOF

    - name: Self-hosted Renovate
      env:
        LOG_LEVEL: debug
        RENOVATE_TOKEN: ${{ secrets.BOT_RENOVATE }}
      run: |
        docker run --interactive --rm \
            --env LOG_LEVEL \
            --env RENOVATE_TOKEN="${RENOVATE_TOKEN}" \
            --env RENOVATE_REQUIRE_CONFIG=ignored \
            --env RENOVATE_CONFIG_FILE=/renovate_config/renovate-small.json \
            --volume $PWD/config:/renovate_config \
            renovate/renovate:slim \
                --dry-run=full \
                "${GITHUB_REPOSITORY}"
