name: Scan

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of tool to scan'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  scout:
    name: Scout
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-22.04
    steps:

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: uniget-bot
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Analyze for critical and high CVEs
      id: docker-scout-cves
      uses: docker/scout-action@v0.23.4
      with:
        command: cves
        image: ghcr.io/${{ github.repository }}/${{ inputs.name}}:latest
        #dockerhub-user: ${{ secrets.DOCKERHUB_USER }}
        #dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}
        sarif-file: sarif.output.json
        summary: true
      
    - name: Upload SARIF result
      id: upload-sarif
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: sarif.output.json
