name: Test-Linux

on:
  pull_request:
    types:
    - opened
    - synchronize
    #- labeled
    #- reopened
    paths:
    - tools/**
    - .github/workflows/*

jobs:

  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install uniget
      uses: uniget-org/uniget-action@main
      with:
        prefix: helper
        tools: gojq regclient

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: uniget-bot
        password: ${{ secrets.BOT_PACKAGES }}

    - name: Test
      env:
        DOCKER_BUILDKIT: 1
        IS_PR: ${{ github.event_name == 'pull_request' }}
        PR: ${{ github.event.pull_request.number }}
      run: |
        set -o errexit
        if ${IS_PR}; then
            echo "### This is PR ${PR}"
            TOOLS="$(
                curl https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR}/files \
                    --silent \
                    --fail \
                    --header "Accept: application/vnd.github.v3+json" \
                    --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
                | jq --raw-output '.[] | select(.status != "removed") | .filename' \
                | grep -E '^tools/[^/]+/' \
                | cut -d/ -f2 \
                | uniq \
                | xargs echo
            )"
            echo "### Got TOOLS=${TOOLS}"
        fi

        if test -z "${TOOLS}"; then
            echo "### No tools changed"
            exit 0
        fi

        echo "### Building all tools"
        for TOOL in ${TOOLS}; do
            echo "### Building ${TOOL}"
            VERSION=test make ${TOOL} PUSH=true
        done

        echo "### Checking if all tools are public"
        PRIVATE_TOOLS=""
        for TOOL in ${TOOLS}; do
            if curl --url "https://api.github.com/orgs/${GITHUB_REPOSITORY_OWNER}/packages?package_type=container&visibility=public&per_page=100" \
                        --silent \
                        --fail \
                        --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                    | jq --raw-output '.[].name' \
                    | grep -q "^tools\/${TOOL}\$"; then
                echo "### ${TOOL} is not public"
                PRIVATE_TOOLS="${PRIVATE_TOOLS}${TOOL} "
            fi
        done
        if test -n "${PRIVATE_TOOLS}"; then
            echo "### The following tools are not public: ${PRIVATE_TOOLS}"
            exit 1
        fi

    - name: Store logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: logs.zip
        path: "**/build.log"

  automerge:
    name: Test
    needs:
    - test
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: ./.github/workflows/automerge.yml
