name: Test-Workflow-Call

on:
  pull_request:
    types:
    - opened
    - synchronize

jobs:

  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
    - name: Workflow call
      uses: ./.github/workflows/automerge.yml
    