name: Test-Workflow-Call

on:
  pull_request:
    types:
    - opened
    - synchronize

jobs:

  test:
    name: Test
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: ./.github/workflows/automerge.yml
    