#syntax=docker/dockerfile:1.21.0@sha256:27f9262d43452075f3c410287a2c43f5ef1bf7ec2bb06e8c9eeb1b8d453087bc

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/rancher/k3d/releases/download/v${version}/k3d-linux-${alt_arch}"
filename="$( basename "${url}" )"

check-github-release-asset "rancher/k3d" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/k3d"

"${prefix}/bin/k3d" completion bash >"${prefix}/share/bash-completion/completions/k3d"
"${prefix}/bin/k3d" completion fish >"${prefix}/share/fish/vendor_completions.d/k3d.fish"
"${prefix}/bin/k3d" completion zsh >"${prefix}/share/zsh/vendor-completions/_k3d"
EOF
