#syntax=docker/dockerfile:1.27.1@sha256:4edf897a3ffa55b89f906fc8cc78afdb3f1834cc9c7083565e611a8a7d5fe99e

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version

RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/prometheus/prometheus-mcp/releases/download/v${version}/prometheus-mcp-server_${version}_linux_${alt_arch}.tar.gz"
filename="$( basename "${url}" )"

check-download "${url}"
check-github-release-asset "prometheus/prometheus-mcp" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin/" --no-same-owner \
    prometheus-mcp-server
EOF