#syntax=docker/dockerfile:1.27.1@sha256:4edf897a3ffa55b89f906fc8cc78afdb3f1834cc9c7083565e611a8a7d5fe99e

FROM registry.gitlab.com/uniget-org/images/build-essential:26.04 AS build-essential2604

FROM registry.gitlab.com/uniget-org/images/ubuntu:26.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
echo "### Setting architecture string for ${TARGETPLATFORM}"
case "${arch}" in
    amd64|x86_64)
        export arch_suffix="${arch}-unknown-linux-musl"
        ;;
    arm64|aarch64)
        export arch_suffix="${arch}-unknown-linux-gnu"
        ;;
    *)
        echo "ERROR: Unsupported architecture ${arch}."
        exit 1
        ;;
esac
echo "    Using ${arch_suffix}"

url="https://github.com/nolabs-ai/nono/releases/download/v${version}/nono-v${version}-${arch_suffix}.tar.gz"
filename="$( basename "${url}" )"

check-github-release-asset "nolabs-ai/nono" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

tar --file="${uniget_cache_download}/${filename}" --list
tar --file="${uniget_cache_download}/${filename}" --extract --gzip --directory="${prefix}/bin/" --no-same-owner
EOF