#syntax=docker/dockerfile:1.20.0@sha256:b6afd42430b15f2d2a4c5a02b919e98a525b785b1aaff16747d2f623364e39b6

FROM registry.gitlab.com/uniget-org/images/ubuntu:24.04 AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN --mount=type=cache,target=/var/cache/uniget/download <<EOF
url="https://github.com/loft-sh/vcluster/releases/download/v${version}/vcluster-linux-${alt_arch}"
filename="$( basename "${url}" )"

check-github-release-asset "loft-sh/vcluster" "v${version}" "${filename}"
curl --silent --show-error --location --fail --output "${uniget_cache_download}/${filename}" \
    "${url}"

install --mode=0755 \
    "${uniget_cache_download}/${filename}" \
    "${prefix}/bin/vcluster"


"${prefix}/bin/vcluster" completion bash >"${prefix}/share/bash-completion/completions/vcluster"
"${prefix}/bin/vcluster" completion fish >"${prefix}/share/fish/vendor_completions.d/vcluster.fish"
"${prefix}/bin/vcluster" completion zsh >"${prefix}/share/zsh/vendor-completions/_vcluster"
EOF