#syntax=docker/dockerfile:1.8.0

FROM ghcr.io/uniget-org/images/ubuntu:24.04@sha256:6ff62e5ed6b1c33f0ae1644692a354281534a37ec4d752cf480850e19a94d16d AS prepare
COPY --from=ghcr.io/uniget-org/tools/uniget-build:latest \
    /etc/profile.d/ \
    /etc/profile.d/
SHELL [ "bash", "-clo", "errexit" ]
ARG name
ARG version
RUN <<EOF
check-github-release-asset "ossf/scorecard" "v${version}" "scorecard_${version}_linux_${alt_arch}.tar.gz"
curl --silent --show-error --location --fail "https://github.com/ossf/scorecard/releases/download/v${version}/scorecard_${version}_linux_${alt_arch}.tar.gz" \
| tar --extract --gzip --directory="${prefix}/bin" --no-same-owner \
    scorecard-linux-${alt_arch}
mv "${prefix}/bin/scorecard-linux-${alt_arch}" "${prefix}/bin/scorecard"
"${prefix}/bin/scorecard" completion bash | sed 's|./scorecard|scorecard|g' >"${prefix}/share/bash-completion/completions/scorecard"
"${prefix}/bin/scorecard" completion fish | sed 's|./scorecard|scorecard|g' >"${prefix}/share/fish/vendor_completions.d/scorecard.fish"
"${prefix}/bin/scorecard" completion zsh  | sed 's|./scorecard|scorecard|g' >"${prefix}/share/zsh/vendor-completions/_scorecard"
EOF